(in-package #:qed.nucleo)

(defun heroi-madeira (heroi) (getf (heroi-inventario heroi) :wood 0))
(defun (setf heroi-madeira) (valor heroi)
  (setf (getf (heroi-inventario heroi) :wood) valor))
(defun quantidade-material (heroi material)
  (getf (heroi-inventario heroi) material 0))
(defun (setf quantidade-material) (valor heroi material)
  (setf (getf (heroi-inventario heroi) material) valor))

(defun inimigo-p (entidade)
  (and entidade (eq (entidade-categoria entidade) :inimigo)))
(defun recurso-p (entidade)
  (and entidade (eq (entidade-categoria entidade) :recurso)))
(defun corresponde-tipo-p (entidade tipo)
  (and entidade
       (case tipo
         (:inimigo (inimigo-p entidade))
         (:recurso (recurso-p entidade))
         (otherwise (eq tipo (entidade-tipo entidade))))))

(defun construcao-pronta-p (heroi id)
  (not (null (member id (heroi-construcoes heroi)))))
(defun objetivo-pronto-p (heroi id)
  (case id
    (:eight-slimes (>= (getf (heroi-abates heroi) :slime 0) 8))
    (:six-sentinels (>= (getf (heroi-abates heroi) :sentinel 0) 6))
    (:guardian (>= (getf (heroi-abates heroi) :guardian 0) 1))
    (otherwise (construcao-pronta-p heroi id))))
(defun custos-disponiveis-p (heroi custos)
  (loop for (material quantidade) on custos by #'cddr
        always (>= (quantidade-material heroi material) quantidade)))
(defun situacao-construcao (heroi id)
  (let ((dados (especificacao-construcao id)))
    (cond ((construcao-pronta-p heroi id) :construida)
          ((not (every (lambda (requisito) (objetivo-pronto-p heroi requisito))
                       (getf dados :requisitos))) :requisitos)
          ((not (custos-disponiveis-p heroi (getf dados :custos))) :materiais)
          (t :disponivel))))
(defun construir (mundo id)
  "Compra atômica: nenhum material é descontado antes da validação completa."
  (let* ((heroi (mundo-heroi mundo)) (dados (especificacao-construcao id))
         (situacao (situacao-construcao heroi id)))
    (unless (eq situacao :disponivel) (return-from construir (values nil situacao)))
    (loop for (material quantidade) on (getf dados :custos) by #'cddr
          do (decf (quantidade-material heroi material) quantidade))
    (push id (heroi-construcoes heroi))
    (case id
      (:shelter (incf (heroi-hp-max heroi) 25))
      (:arsenal nil)
      (:observatory (incf (heroi-mana-max heroi) 20)))
    (clrhash (mundo-falhas mundo))
    (registrar mundo (format nil "~A construído." (getf dados :nome)) :construcao id)
    (atualizar-campanha mundo)
    (values t :construida)))

(defun bonus-dano (heroi) (if (construcao-pronta-p heroi :arsenal) 4 0))
(defun oficina-pronta-p (heroi) (construcao-pronta-p heroi :workshop))
(defun coletavel-p (mundo entidade)
  (and entidade (recurso-p entidade) (plusp (entidade-hp entidade))
       (or (eq (entidade-tipo entidade) :wood)
           (oficina-pronta-p (mundo-heroi mundo)))))

(defun passagem-bloqueada-p (mundo passagem)
  (not (construcao-pronta-p (mundo-heroi mundo) (getf passagem :construcao))))
(defun colisoes-passagens (mundo)
  (loop for passagem in (getf *campanha* :passagens)
        when (passagem-bloqueada-p mundo passagem)
          collect (list (getf passagem :x) 160 16 96 -1)))
(defun passagem-entre-p (mundo a b)
  (some (lambda (passagem)
          (and (passagem-bloqueada-p mundo passagem)
               (< (min a b) (getf passagem :x) (max a b))))
        (getf *campanha* :passagens)))

(defun regiao-atual (mundo)
  (let ((x (heroi-x (mundo-heroi mundo))))
    (or (find-if (lambda (regiao)
                   (<= (getf regiao :inicio) x
                       (+ (getf regiao :inicio) (getf regiao :largura) -1)))
                 (mundo-regioes mundo))
        (first (mundo-regioes mundo)))))
(defun atualizar-campanha (mundo)
  (let* ((heroi (mundo-heroi mundo)) (regiao (regiao-atual mundo))
         (id (getf regiao :id)))
    (pushnew id (heroi-regioes-descobertas heroi))
    (setf (heroi-objetivos heroi)
          (remove nil
            (list (and (construcao-pronta-p heroi :shelter) :shelter)
                  (and (objetivo-pronto-p heroi :eight-slimes) :eight-slimes)
                  (and (construcao-pronta-p heroi :workshop) :workshop)
                  (and (construcao-pronta-p heroi :arsenal) :arsenal)
                  (and (objetivo-pronto-p heroi :six-sentinels) :six-sentinels)
                  (and (construcao-pronta-p heroi :observatory) :observatory)
                  (and (objetivo-pronto-p heroi :guardian) :guardian))))))

(defun etapa-campanha (heroi)
  (cond ((objetivo-pronto-p heroi :guardian) :concluida)
        ((construcao-pronta-p heroi :observatory) :guardian)
        ((and (construcao-pronta-p heroi :arsenal)
              (objetivo-pronto-p heroi :six-sentinels)
              (custos-disponiveis-p heroi (getf (especificacao-construcao :observatory) :custos))) :observatory)
        ((construcao-pronta-p heroi :arsenal) :sentinels)
        ((construcao-pronta-p heroi :workshop) :arsenal)
        ((and (construcao-pronta-p heroi :shelter)
              (objetivo-pronto-p heroi :eight-slimes)
              (custos-disponiveis-p heroi (getf (especificacao-construcao :workshop) :custos))) :workshop)
        ((construcao-pronta-p heroi :shelter) :slimes)
        (t :shelter)))
(defun resumo-campanha (heroi)
  (case (etapa-campanha heroi)
    (:shelter (format nil "Abrigo: ~D/30 madeira" (heroi-madeira heroi)))
    (:slimes (format nil "Slimes: ~D/8; Oficina: ~D/50 madeira"
                     (min 8 (getf (heroi-abates heroi) :slime 0)) (heroi-madeira heroi)))
    (:workshop "Oficina disponível no Acampamento")
    (:arsenal (if (custos-disponiveis-p heroi (getf (especificacao-construcao :arsenal) :custos))
                  "Arsenal disponível no Acampamento"
                  (format nil "Arsenal: ~D/30 madeira, ~D/20 ferro"
                          (heroi-madeira heroi) (quantidade-material heroi :iron-ore))))
    (:sentinels (format nil "Sentinelas: ~D/6; ferro: ~D/20; cristais: ~D/10"
                        (min 6 (getf (heroi-abates heroi) :sentinel 0))
                        (quantidade-material heroi :iron-ore)
                        (quantidade-material heroi :arcane-crystal)))
    (:observatory "Observatório disponível no Acampamento")
    (:guardian "Derrote o Guardião do Observatório")
    (otherwise "Campanha concluída")))

(defun alvo-da-missao (mundo)
  (let ((heroi (mundo-heroi mundo)))
    (case (etapa-campanha heroi)
      (:shelter (when (< (heroi-madeira heroi) 30) (mais-proxima mundo :wood)))
      (:slimes (if (< (getf (heroi-abates heroi) :slime 0) 8)
                   (mais-proxima mundo :slime) (mais-proxima mundo :wood)))
      (:arsenal (cond ((< (heroi-madeira heroi) 30) (mais-proxima mundo :wood))
                      ((< (quantidade-material heroi :iron-ore) 20) (mais-proxima mundo :iron-ore))))
      (:sentinels (cond ((< (getf (heroi-abates heroi) :sentinel 0) 6) (mais-proxima mundo :sentinel))
                        ((< (quantidade-material heroi :iron-ore) 20) (mais-proxima mundo :iron-ore))
                        ((< (quantidade-material heroi :arcane-crystal) 10) (mais-proxima mundo :arcane-crystal))))
      (:guardian (mais-proxima mundo :guardian))
      (otherwise nil))))

(defun mudar-animacao (entidade animacao)
  (setf (entidade-animacao entidade) animacao (entidade-tempo-animacao entidade) 0))
(defun ferir-heroi (mundo dano)
  (let ((heroi (mundo-heroi mundo)))
    (decf (heroi-hp heroi) dano)
    (setf (heroi-ferimento heroi) 0.4)
    (adicionar-efeito mundo :ferimento (heroi-x heroi) (- (heroi-y heroi) 32) :valor dano)))
(defun restaurar-entidade (mundo entidade)
  (let ((dados (especificacao-especie (entidade-tipo entidade))))
    (setf (entidade-hp entidade) (getf dados :hp)
          (entidade-x entidade) (entidade-origem-x entidade)
          (entidade-y entidade) (altura-chao mundo (entidade-origem-x entidade))
          (entidade-fase entidade) :idle (entidade-tempo-fase entidade) 0)
    (mudar-animacao entidade :idle)))
(defun derrotar-entidade (mundo entidade)
  (let* ((heroi (mundo-heroi mundo)) (dados (especificacao-especie (entidade-tipo entidade)))
         (tipo (entidade-tipo entidade)))
    (incf (getf (heroi-abates heroi) tipo 0))
    (conceder-xp mundo (getf dados :xp))
    (setf (entidade-retorno entidade) (getf dados :retorno)
          (entidade-fase entidade) :idle (entidade-tempo-fase entidade) 0)
    (mudar-animacao entidade :death)
    (registrar mundo (format nil "~A derrotado." (getf dados :nome)))
    (atualizar-campanha mundo)))
(defun reiniciar-chefe (mundo)
  (let ((chefe (find :guardian (mundo-entidades mundo) :key #'entidade-tipo)))
    (when (and chefe (not (objetivo-pronto-p (mundo-heroi mundo) :guardian)))
      (restaurar-entidade mundo chefe))))
(defun atualizar-inimigo-anunciado (mundo entidade dados)
  (let ((heroi (mundo-heroi mundo)))
    (case (entidade-fase entidade)
      (:idle
       (let ((distancia-atual (distancia heroi entidade)))
         (cond
           ((and (<= distancia-atual (+ (getf dados :alcance) 8))
                 (linha-livre-p mundo entidade))
            (setf (entidade-fase entidade) :windup (entidade-tempo-fase entidade) 0)
            (mudar-animacao entidade :windup))
           ((and (< distancia-atual (getf dados :deteccao))
                 (not (passagem-entre-p mundo (entidade-x entidade) (heroi-x heroi))))
            (let* ((direcao (signum (- (heroi-x heroi) (entidade-x entidade))))
                   (novo-x (+ (entidade-x entidade) (* direcao (getf dados :velocidade) +passo+)))
                   (novo-y (altura-chao mundo novo-x)))
              (when (<= (abs (- novo-y (entidade-y entidade))) 64)
                (setf (entidade-x entidade) novo-x (entidade-y entidade) novo-y)))))))
      (:windup
       (incf (entidade-tempo-fase entidade) +passo+)
       (let ((duracao (if (and (eq (entidade-tipo entidade) :guardian)
                               (< (entidade-hp entidade) (/ (getf dados :hp) 2)))
                          9/10 (getf dados :preparacao))))
         (when (>= (entidade-tempo-fase entidade) duracao)
           (when (and (< (distancia heroi entidade) (getf dados :alcance))
                      (linha-livre-p mundo entidade))
             (ferir-heroi mundo (getf dados :dano)))
           (setf (entidade-fase entidade) :recovery (entidade-tempo-fase entidade) 0)
           (mudar-animacao entidade :recovery))))
      (:recovery
       (incf (entidade-tempo-fase entidade) +passo+)
       (when (>= (entidade-tempo-fase entidade) (getf dados :recuperacao))
         (setf (entidade-fase entidade) :idle (entidade-tempo-fase entidade) 0)
         (mudar-animacao entidade :idle))))))
