(in-package #:qed.nucleo)

(defconstant +passo+ 1/60)

(defstruct (entidade (:constructor criar-entidade) (:copier copiar-entidade))
  (id 0) (tipo :slime) (x 0) (y 240) (vx 0) (vy 0) (hp 35)
  (retorno 0) (molhada nil) (recarga 0) (animacao :idle) (tempo-animacao 0))

(defstruct (heroi (:constructor criar-heroi) (:copier copiar-heroi))
  (classe :fighter) (x 48) (y 240) (vx 0) (vy 0) (hp 100) (hp-max 100)
  (mana 80) (mana-max 80) (xp 0) (madeira 0) (estado :idle) (morte 0)
  (ferimento 0) (tempo-animacao 0) acao (desbloqueios nil) (slots 4) (direcao 1)
  (conhecimentos nil) (pontos-bonus 0))

(defstruct (intencao (:constructor criar-intencao))
  acoes nome (prioridade 0) (mana 0) (duracao 0) (passos 0) prova (idioma :pt))
(defstruct (execucao (:constructor criar-execucao))
  intencao restantes alvos-movimento (tempo 0) (iniciada nil))
(defstruct (resultado (:constructor criar-resultado))
  intencao (motivo :nenhuma-correspondencia) detalhes falhas (passos 0) prova)
(defstruct (mundo (:constructor criar-mundo) (:copier copiar-mundo))
  heroi entidades (tick 0) eventos efeitos
  plataformas
  (falhas (make-hash-table :test 'equal)) diagnostico ultimo-resultado)

(defun carregar-plataformas ()
  "Converte o tilemap distribuído com o jogo em faixas de colisão sólidas."
  (let ((*read-eval* nil))
    (with-open-file (fluxo (asdf:system-relative-pathname "qed/core" "dados/clareira.sexp"))
      (let* ((dados (read fluxo)) (linhas (getf dados :linhas)) (retangulos nil) (identificador 1))
        (unless (and (= (getf dados :versao) 1) (= (getf dados :tile) 16)
                     (= (length linhas) 17) (every (lambda (linha) (= (length linha) 90)) linhas))
          (error "Tilemap da clareira inválido."))
        (loop for linha in linhas for y from 0 do
          (loop with inicio = nil for x from 0 to 90
                for solido = (and (< x 90) (char= (char linha x) #\#)) do
            (when (and solido (null inicio)) (setf inicio x))
            (when (and inicio (not solido))
              (push (list (* inicio 16) (* y 16) (* (- x inicio) 16) 16
                          (if (>= y 15) 0 (incf identificador))) retangulos)
              (setf inicio nil))))
        (nreverse retangulos)))))

(defun novo-mundo (&optional (classe :fighter))
  (criar-mundo :heroi (criar-heroi :classe classe) :plataformas (carregar-plataformas)
    :entidades (list (criar-entidade :id 1 :tipo :wood :x 200 :hp 1)
                     (criar-entidade :id 2 :tipo :slime :x 310)
                     (criar-entidade :id 3 :tipo :wood :x 610 :hp 1)
                     (criar-entidade :id 4 :tipo :slime :x 710 :molhada t)
                     (criar-entidade :id 5 :tipo :wood :x 1000 :hp 1)
                     (criar-entidade :id 6 :tipo :slime :x 1280))))

(defun fotografar (mundo)
  "Cópia dos fatos consultáveis. Avaliadores nunca recebem objetos mutáveis do jogo."
  (let ((copia (copiar-mundo mundo)))
    (setf (mundo-heroi copia) (copiar-heroi (mundo-heroi mundo))
          (mundo-entidades copia) (mapcar #'copiar-entidade (mundo-entidades mundo))
          (mundo-falhas copia) (copiar-tabela (mundo-falhas mundo)))
    copia))

(defun copiar-tabela (tabela)
  ;; Implementação local para manter o núcleo dependente apenas de CL/UIOP.
  (let ((copia (make-hash-table :test (hash-table-test tabela))))
    (maphash (lambda (chave valor) (setf (gethash chave copia) valor)) tabela)
    copia))

(defun registrar (mundo mensagem &rest propriedades)
  (push (append (list (mundo-tick mundo) mensagem) propriedades) (mundo-eventos mundo))
  (when (> (length (mundo-eventos mundo)) 80)
    (setf (mundo-eventos mundo) (subseq (mundo-eventos mundo) 0 80))))

(defun buscar-entidade (mundo identificador)
  (find identificador (mundo-entidades mundo) :key #'entidade-id :test #'equal))

(defun distancia (heroi entidade)
  (sqrt (+ (expt (- (heroi-x heroi) (entidade-x entidade)) 2)
           (expt (- (heroi-y heroi) (entidade-y entidade)) 2))))

(defun mais-proxima (mundo tipo)
  (first (stable-sort
          (remove-if-not (lambda (entidade)
                           (and (eq tipo (entidade-tipo entidade))
                                (plusp (entidade-hp entidade))))
                         (copy-list (mundo-entidades mundo)))
          (lambda (a b)
            (let ((da (distancia (mundo-heroi mundo) a))
                  (db (distancia (mundo-heroi mundo) b)))
              (or (< da db) (and (= da db) (< (entidade-id a) (entidade-id b)))))))))

(defun altura-chao (mundo x)
  (loop for (esquerda topo largura) in (mundo-plataformas mundo)
        when (<= esquerda x (+ esquerda largura)) minimize topo into altura
        finally (return (or altura 240))))

(defun rota-para (mundo x)
  "Grafo de superfícies da fase: arestas de caminhada e salto, no máximo 64 px de subida."
  (when (and (realp x) (<= 12 x 1428))
    (let* ((inicio (heroi-x (mundo-heroi mundo))) (direcao (if (> x inicio) 1 -1))
           (obstaculos (remove-if-not
                         (lambda (plataforma)
                           (and (/= 0 (fifth plataforma))
                                (< (min inicio x) (+ (first plataforma) (third plataforma)))
                                (> (max inicio x) (first plataforma))))
                         (mundo-plataformas mundo))))
      (when (every (lambda (p) (<= (- 240 (second p)) 64)) obstaculos)
        (append
         (mapcar (lambda (p) (list :salto (if (plusp direcao)
                                             (- (first p) 20)
                                             (+ (first p) (third p) 20))))
                 (sort (copy-list obstaculos) (if (plusp direcao) #'< #'>) :key #'first))
         (list (list :andar x)))))))

(defun alcancavel-p (mundo alvo)
  (and alvo (rota-para mundo (if (entidade-p alvo) (entidade-x alvo) alvo)) t))

(defun linha-livre-p (mundo entidade)
  (and entidade (plusp (entidade-hp entidade))
       (let* ((heroi (mundo-heroi mundo))
              (xa (heroi-x heroi)) (ya (- (heroi-y heroi) 16))
              (xb (entidade-x entidade)) (yb (- (entidade-y entidade) 12)))
         (loop for fracao from 0 to 20
               for x = (+ xa (* (/ fracao 20) (- xb xa)))
               for y = (+ ya (* (/ fracao 20) (- yb ya)))
               never (some (lambda (p)
                             (destructuring-bind (px py largura altura id) p
                               (declare (ignore id))
                               (and (< px x (+ px largura)) (< py y (+ py altura)))))
                           (mundo-plataformas mundo))))))

(defun marcos-progressao (classe)
  (declare (ignore classe))
  '((30 "ponto") (60 "ponto") (100 "ponto")))
(defun proximo-marco (heroi)
  (find-if (lambda (marco) (> (first marco) (heroi-xp heroi)))
           (marcos-progressao (heroi-classe heroi))))
(defun adicionar-efeito (mundo tipo x y &key valor (duracao 1.2))
  (push (list :tipo tipo :x x :y y :tempo 0 :duracao duracao :valor valor)
        (mundo-efeitos mundo)))
(defun conceder-xp (mundo pontos)
  (let* ((heroi (mundo-heroi mundo)) (anterior (heroi-xp heroi)))
    (incf (heroi-xp heroi) pontos)
    (atualizar-desbloqueios heroi)
    (dolist (marco (marcos-progressao (heroi-classe heroi)))
      (when (< anterior (first marco) (1+ (heroi-xp heroi)))
        (registrar mundo "Novo conhecimento disponível." :desbloqueio (second marco))))
    (adicionar-efeito mundo :xp (heroi-x heroi) (- (heroi-y heroi) 38) :valor pontos)))

(defun cancelar-acao (mundo &optional (motivo "Ação interrompida."))
  (let ((heroi (mundo-heroi mundo)))
    (when (heroi-acao heroi) (registrar mundo motivo))
    (setf (heroi-acao heroi) nil (heroi-estado heroi) :idle (heroi-vx heroi) 0)))

(defun acoes-validas-p (mundo intencao)
  (let ((heroi (mundo-heroi mundo)))
    (and (>= (heroi-mana heroi) (intencao-mana intencao))
         (every (lambda (acao)
                  (let ((alvo (buscar-entidade mundo (second acao))))
                    (case (first acao)
                      (:esperar t)
                      (:mover (alcancavel-p mundo (or alvo (second acao))))
                      (:coletar (and alvo (eq (entidade-tipo alvo) :wood) (plusp (entidade-hp alvo))))
                      ((:fugir :atacar :magia) (and alvo (eq (entidade-tipo alvo) :slime) (plusp (entidade-hp alvo))))
                      (otherwise nil))))
                (intencao-acoes intencao)))))

(defun iniciar-intencao (mundo intencao)
  (when (acoes-validas-p mundo intencao)
    (setf (heroi-acao (mundo-heroi mundo))
          (criar-execucao :intencao intencao :restantes (copy-tree (intencao-acoes intencao))
                         :alvos-movimento (loop for acao in (intencao-acoes intencao)
                                                when (and (eq (first acao) :mover)
                                                          (buscar-entidade mundo (second acao)))
                                                  collect (second acao))))
    t))

(defun mover-heroi (mundo destino)
  (let* ((heroi (mundo-heroi mundo)) (diferenca (- destino (heroi-x heroi)))
         (direcao (signum diferenca)))
    (setf (heroi-vx heroi) (* direcao 72) (heroi-estado heroi) :walk)
    (unless (zerop direcao) (setf (heroi-direcao heroi) direcao))
    (when (and (= (heroi-vy heroi) 0)
               (< (altura-chao mundo (+ (heroi-x heroi) (* direcao 22)))
                  (heroi-y heroi)))
      (setf (heroi-vy heroi) -300 (heroi-estado heroi) :jump))
    (when (< (abs diferenca) 3) (setf (heroi-vx heroi) 0) t)))

(defun subir-proxima-acao (heroi execucao)
  (pop (execucao-restantes execucao))
  (setf (execucao-tempo execucao) 0 (execucao-iniciada execucao) nil)
  (unless (execucao-restantes execucao)
    (setf (heroi-acao heroi) nil (heroi-estado heroi) :idle)))

(defun executar-acao (mundo)
  (let* ((heroi (mundo-heroi mundo)) (execucao (heroi-acao heroi)))
    (when execucao
      (let* ((acao (first (execucao-restantes execucao))) (tipo (first acao))
             (alvo (buscar-entidade mundo (second acao)))
             (intencao (execucao-intencao execucao)))
        (when (and (not (execucao-iniciada execucao))
                   (or (member tipo '(:fugir :coletar :atacar :magia))
                       (and (eq tipo :mover) (member (second acao) (execucao-alvos-movimento execucao))))
                   (or (null alvo) (not (plusp (entidade-hp alvo)))))
          (cancelar-acao mundo "O alvo deixou de existir.")
          (return-from executar-acao))
        (incf (execucao-tempo execucao) +passo+)
        (setf (heroi-vx heroi) 0)
        (case tipo
          (:mover
           (if (alcancavel-p mundo (or alvo (second acao)))
               (when (mover-heroi mundo (if alvo (entidade-x alvo) (second acao)))
                 (subir-proxima-acao heroi execucao))
               (cancelar-acao mundo "Não há caminho até o destino.")))
          (:fugir
           (let ((destino (max 12 (min 1428 (+ (heroi-x heroi)
                                  (* (if (< (entidade-x alvo) (heroi-x heroi)) 1 -1) 100))))))
             (mover-heroi mundo destino)
             (when (>= (execucao-tempo execucao) 1) (subir-proxima-acao heroi execucao))))
          (:esperar
           (setf (heroi-estado heroi) :idle)
           (when (>= (execucao-tempo execucao) (or (second acao) 0.5))
             (subir-proxima-acao heroi execucao)))
          ((:coletar :atacar :magia)
           (let ((alcance (if (eq tipo :magia) 160 30)))
             (unless (or (execucao-iniciada execucao)
                         (and (<= (distancia heroi alvo) alcance)
                          (or (not (eq tipo :magia)) (linha-livre-p mundo alvo)))
                         )
               (cancelar-acao mundo "O alvo saiu do alcance ou da linha de visão.")
               (return-from executar-acao)))
           (setf (heroi-estado heroi) (case tipo (:coletar :gather) (:magia :cast) (t :attack)))
           (when (and alvo (/= (entidade-x alvo) (heroi-x heroi)))
             (setf (heroi-direcao heroi) (signum (- (entidade-x alvo) (heroi-x heroi)))))
           ;; O efeito ocorre no impacto; a recuperação visual termina depois.
           (when (and (not (execucao-iniciada execucao))
                      (>= (execucao-tempo execucao)
                          (case tipo (:coletar 0.4) (:atacar 0.3)
                            (t (intencao-duracao intencao)))))
             (when (eq tipo :magia)
               (when (< (heroi-mana heroi) (intencao-mana intencao))
                 (cancelar-acao mundo "Mana insuficiente ao concluir a conjuração.")
                 (return-from executar-acao))
               (decf (heroi-mana heroi) (intencao-mana intencao)))
             (setf (execucao-iniciada execucao) t)
             (if (eq tipo :coletar)
                 (progn (incf (heroi-madeira heroi)) (conceder-xp mundo 2)
                        (setf (entidade-hp alvo) 0 (entidade-retorno alvo) 6)
                        (registrar mundo "Madeira coletada: +2 XP."))
                 (progn
                   (setf (entidade-animacao alvo) :hurt (entidade-tempo-animacao alvo) 0)
                   (when (eq tipo :magia)
                     (adicionar-efeito mundo (third acao) (entidade-x alvo) (- (entidade-y alvo) 16) :duracao 0.4))
                   (let ((dano (cond ((equal (third acao) "lightning") 40)
                               ((eq tipo :magia) 24)
                               ((equal (third acao) ":heavy-strike") 28) (t 18))))
                     (decf (entidade-hp alvo) dano)
                     (adicionar-efeito mundo :dano (entidade-x alvo) (- (entidade-y alvo) 32) :valor dano))
                   (when (<= (entidade-hp alvo) 0)
                     (conceder-xp mundo 10)
                     (setf (entidade-retorno alvo) 8 (entidade-animacao alvo) :death (entidade-tempo-animacao alvo) 0)
                     (registrar mundo "Slime derrotado: +10 XP.")))))
           (when (>= (execucao-tempo execucao)
                     (if (eq tipo :magia) (intencao-duracao intencao) 0.6))
             (subir-proxima-acao heroi execucao))))))))

(defun aplicar-fisica (mundo)
  (let* ((heroi (mundo-heroi mundo)) (antes-x (heroi-x heroi)) (antes-y (heroi-y heroi)))
    (incf (heroi-vy heroi) (* 600 +passo+))
    (setf (heroi-x heroi) (max 12 (min 1428 (+ antes-x (* (heroi-vx heroi) +passo+)))))
    (incf (heroi-y heroi) (* (heroi-vy heroi) +passo+))
    (dolist (p (mundo-plataformas mundo))
      (destructuring-bind (px py largura altura id) p
        (declare (ignore id))
        (when (and (< (- (heroi-x heroi) 7) (+ px largura)) (> (+ (heroi-x heroi) 7) px)
                   (<= antes-y py) (>= (heroi-y heroi) py) (>= (heroi-vy heroi) 0))
          (setf (heroi-y heroi) py (heroi-vy heroi) 0))
        (when (and (< (- (heroi-x heroi) 7) (+ px largura)) (> (+ (heroi-x heroi) 7) px)
                   (>= (- antes-y 26) (+ py altura)) (< (- (heroi-y heroi) 26) (+ py altura))
                   (minusp (heroi-vy heroi)))
          (setf (heroi-y heroi) (+ py altura 26) (heroi-vy heroi) 0))
        (when (and (< (- (heroi-y heroi) 26) (+ py altura)) (> (heroi-y heroi) (+ py 1)))
          (cond ((and (<= (+ antes-x 7) px) (> (+ (heroi-x heroi) 7) px))
                 (setf (heroi-x heroi) (- px 7)))
                ((and (>= (- antes-x 7) (+ px largura))
                      (< (- (heroi-x heroi) 7) (+ px largura)))
                 (setf (heroi-x heroi) (+ px largura 7)))))))
    (unless (zerop (heroi-vy heroi)) (setf (heroi-estado heroi) :jump))))

(defun atualizar-inimigos (mundo)
  (let ((heroi (mundo-heroi mundo)))
    (dolist (entidade (mundo-entidades mundo))
      (incf (entidade-tempo-animacao entidade) +passo+)
      (when (and (plusp (entidade-hp entidade))
                 (or (and (eq (entidade-animacao entidade) :hurt)
                          (>= (entidade-tempo-animacao entidade) 0.25))
                     (and (eq (entidade-animacao entidade) :attack)
                          (>= (entidade-tempo-animacao entidade) 0.4))))
        (setf (entidade-animacao entidade) :idle
              (entidade-tempo-animacao entidade) 0))
      (if (<= (entidade-hp entidade) 0)
          (progn (decf (entidade-retorno entidade) +passo+)
                 (when (<= (entidade-retorno entidade) 0)
                   (setf (entidade-hp entidade) (if (eq (entidade-tipo entidade) :wood) 1 35)
                         (entidade-animacao entidade) :idle (entidade-tempo-animacao entidade) 0)))
          (when (eq (entidade-tipo entidade) :slime)
            (setf (entidade-recarga entidade) (max 0 (- (entidade-recarga entidade) +passo+)))
            (when (and (< (distancia heroi entidade) 26) (<= (entidade-recarga entidade) 0)
                       (plusp (heroi-hp heroi)))
              (decf (heroi-hp heroi) 7)
              (adicionar-efeito mundo :ferimento (heroi-x heroi) (- (heroi-y heroi) 32) :valor 7)
              (setf (entidade-recarga entidade) 1 (heroi-ferimento heroi) 0.4
                    (entidade-animacao entidade) :attack (entidade-tempo-animacao entidade) 0)))))))

(defun avancar (mundo avaliador)
  "Executa exatamente um tick. AVALIADOR recebe apenas uma fotografia dos fatos."
  (incf (mundo-tick mundo))
  (dolist (efeito (mundo-efeitos mundo)) (incf (getf efeito :tempo) +passo+))
  (setf (mundo-efeitos mundo) (remove-if (lambda (efeito) (>= (getf efeito :tempo) (getf efeito :duracao 0.4))) (mundo-efeitos mundo)))
  (setf (heroi-ferimento (mundo-heroi mundo)) (max 0 (- (heroi-ferimento (mundo-heroi mundo)) +passo+)))
  (let* ((heroi (mundo-heroi mundo)) (estado-anterior (heroi-estado heroi)))
    (cond
      ((not (plusp (heroi-hp heroi)))
       (unless (eq (heroi-estado heroi) :death)
         (cancelar-acao mundo "Autômato derrotado.")
         (setf (heroi-morte heroi) 3 (heroi-estado heroi) :death))
       (decf (heroi-morte heroi) +passo+)
       (when (<= (heroi-morte heroi) 0)
         (setf (heroi-hp heroi) (heroi-hp-max heroi) (heroi-x heroi) 48
               (heroi-y heroi) 240 (heroi-vy heroi) 0 (heroi-estado heroi) :idle)))
      (t
       (setf (heroi-mana heroi) (min (heroi-mana-max heroi) (+ (heroi-mana heroi) (* 4 +passo+))))
       ;; Recupera-se em segurança também ao esperar ou se deslocar, sem
       ;; depender do intervalo de um tick entre intenções consecutivas.
       (when (and (> (distancia-seguranca mundo) 90)
                  (not (and (heroi-acao heroi)
                            (member (caar (execucao-restantes (heroi-acao heroi)))
                                    '(:atacar :magia :coletar)))))
         (setf (heroi-hp heroi) (min (heroi-hp-max heroi) (+ (heroi-hp heroi) (* 3 +passo+)))))
       (let* ((resultado (funcall avaliador (fotografar mundo)))
              (intencao (resultado-intencao resultado)) (atual (heroi-acao heroi)))
         (setf (mundo-ultimo-resultado mundo) resultado (mundo-diagnostico mundo) (resultado-motivo resultado))
         (dolist (falha (resultado-falhas resultado))
           (setf (gethash (first falha) (mundo-falhas mundo)) (+ (mundo-tick mundo) 60))
           (adicionar-efeito mundo :fizzle (heroi-x heroi) (- (heroi-y heroi) 42) :duracao 0.8)
           (registrar mundo (format nil "Fizzle: ~A — ~A" (first falha) (second falha))
                      :nome (first falha) :motivo (second falha) :idioma (third falha)))
         (when (and intencao
                    (or (null atual)
                        (and (or (zerop (execucao-tempo atual))
                                 (not (member (first (first (execucao-restantes atual))) '(:atacar :magia :coletar))))
                             (> (intencao-prioridade intencao)
                                (intencao-prioridade (execucao-intencao atual))))))
           (when atual (cancelar-acao mundo))
           (iniciar-intencao mundo intencao)))
       (executar-acao mundo)
       (aplicar-fisica mundo)
       (atualizar-inimigos mundo)))
    (setf (heroi-tempo-animacao heroi)
          (if (eq estado-anterior (heroi-estado heroi))
              (+ (heroi-tempo-animacao heroi) +passo+) 0)))
  mundo)

(defun distancia-seguranca (mundo)
  (let ((alvo (mais-proxima mundo :slime)))
    (if alvo (distancia (mundo-heroi mundo) alvo) 9999)))
(defun simular (mundo avaliador segundos)
  (dotimes (indice (round (* segundos 60)) mundo)
    (declare (ignorable indice)) (avancar mundo avaliador)))
(defun estado-resumido (mundo)
  (let ((heroi (mundo-heroi mundo)))
    (list :tick (mundo-tick mundo) :classe (heroi-classe heroi)
          :x (heroi-x heroi) :y (heroi-y heroi) :hp (heroi-hp heroi)
          :mana (heroi-mana heroi) :xp (heroi-xp heroi) :madeira (heroi-madeira heroi))))
