(in-package #:qed.nucleo)

(defconstant +passo+ 1/60)

(defstruct (entidade (:constructor criar-entidade) (:copier copiar-entidade))
  (id 0) (tipo :slime) (x 0) (y 240) (vx 0) (vy 0) (hp 35)
  (categoria :inimigo) (origem-x 0) (fase :idle) (tempo-fase 0)
  (retorno 0) (molhada nil) (recarga 0) (animacao :idle) (tempo-animacao 0))

(defstruct (heroi (:constructor criar-heroi) (:copier copiar-heroi))
  (classe :fighter) (x 48) (y 240) (vx 0) (vy 0) (hp 100) (hp-max 100)
  (mana 80) (mana-max 80) (xp 0) (inventario (list :wood 0 :iron-ore 0 :arcane-crystal 0))
  (construcoes nil) (objetivos nil) (regioes-descobertas (list :clareira))
  (abates (list :slime 0 :sentinel 0 :guardian 0)) (estado :idle) (morte 0)
  (ferimento 0) (tempo-animacao 0) acao (desbloqueios nil) (slots 4) (direcao 1)
  (conhecimentos nil) (pontos-bonus 0))

(defstruct (intencao (:constructor criar-intencao))
  acoes nome (prioridade 0) (mana 0) (duracao 0) (passos 0) prova (idioma :pt))
(defstruct (execucao (:constructor criar-execucao))
  intencao restantes alvos-movimento (tempo 0) (iniciada nil))
(defstruct (resultado (:constructor criar-resultado))
  intencao (motivo :nenhuma-correspondencia) detalhes falhas (passos 0) prova)
(defstruct (mundo (:constructor criar-mundo) (:copier copiar-mundo))
  heroi entidades (tick 0) eventos efeitos
  plataformas (largura 3360) regioes zonas-umidas
  (falhas (make-hash-table :test 'equal)) diagnostico ultimo-resultado)

(defun carregar-plataformas (&optional (arquivo "clareira.sexp") (origem 0))
  "Converte um tilemap de dados em faixas de colisão, com coordenadas globais."
  (let* ((dados (ler-catalogo arquivo)) (linhas (getf dados :linhas))
         (largura (getf dados :largura)) (altura (getf dados :altura))
         (retangulos nil) (identificador (1+ origem)))
    (unless (and (= (getf dados :versao) 1) (= (getf dados :tile) 16)
                 (= (length linhas) altura) (every (lambda (l) (= (length l) largura)) linhas))
      (error "Tilemap inválido: ~A" arquivo))
    (loop for linha in linhas for y from 0 do
      (loop with inicio = nil for x from 0 to largura
            for solido = (and (< x largura) (char= (char linha x) #\#)) do
        (when (and solido (null inicio)) (setf inicio x))
        (when (and inicio (not solido))
          (push (list (+ origem (* inicio 16)) (* y 16) (* (- x inicio) 16) 16
                      (if (>= y 15) 0 (incf identificador))) retangulos)
          (setf inicio nil))))
    (nreverse retangulos)))

(defun novo-mundo (&optional (classe :fighter))
  (let* ((regioes (copy-tree (getf *campanha* :regioes)))
         (mundo (criar-mundo :heroi (criar-heroi :classe classe)
                  :largura (reduce #'+ regioes :key (lambda (r) (getf r :largura)))
                  :regioes regioes
                  :plataformas (loop for r in regioes append
                    (carregar-plataformas (getf r :arquivo) (getf r :inicio)))
                  :zonas-umidas (copy-tree (getf *campanha* :zonas-umidas)))))
    (setf (mundo-entidades mundo)
          (loop for registro in (getf *campanha* :entidades)
                for tipo = (getf registro :tipo) for especie = (especificacao-especie tipo)
                for x = (getf registro :x)
                collect (criar-entidade :id (getf registro :id) :tipo tipo
                         :categoria (getf especie :categoria) :hp (getf especie :hp)
                         :x x :origem-x x
                         ;; Sem uma altura explícita, o pivô da entidade acompanha
                         ;; a superfície. Isso mantém coleta e combate alinhados em
                         ;; plataformas elevadas.
                         :y (if (member :y registro) (getf registro :y)
                                (altura-chao mundo x))
                         :molhada (getf registro :molhada))))
    mundo))

(defun fotografar (mundo)
  "Cópia dos fatos consultáveis. Avaliadores nunca recebem objetos mutáveis do jogo."
  (let ((copia (copiar-mundo mundo)))
    (setf (mundo-heroi copia) (copiar-heroi (mundo-heroi mundo))
          (mundo-entidades copia) (mapcar #'copiar-entidade (mundo-entidades mundo))
          (mundo-falhas copia) (copiar-tabela (mundo-falhas mundo)))
    (let ((h (mundo-heroi copia)))
      (setf (heroi-inventario h) (copy-list (heroi-inventario h))
            (heroi-construcoes h) (copy-list (heroi-construcoes h))
            (heroi-objetivos h) (copy-list (heroi-objetivos h))
            (heroi-regioes-descobertas h) (copy-list (heroi-regioes-descobertas h))
            (heroi-abates h) (copy-list (heroi-abates h))
            (heroi-conhecimentos h) (copy-list (heroi-conhecimentos h))
            (heroi-desbloqueios h) (copy-list (heroi-desbloqueios h))
            (heroi-acao h) nil))
    copia))

(defun copiar-tabela (tabela)
  ;; Implementação local para manter o núcleo dependente apenas de CL/UIOP.
  (let ((copia (make-hash-table :test (hash-table-test tabela))))
    (maphash (lambda (chave valor) (setf (gethash chave copia) valor)) tabela)
    copia))

(defun registrar (mundo mensagem &rest propriedades)
  (push (append (list (mundo-tick mundo) mensagem) propriedades) (mundo-eventos mundo))
  (when (> (length (mundo-eventos mundo)) 80)
    (setf (mundo-eventos mundo) (subseq (mundo-eventos mundo) 0 80))))

(defun buscar-entidade (mundo identificador)
  (find identificador (mundo-entidades mundo) :key #'entidade-id :test #'equal))

(defun distancia (heroi entidade)
  (sqrt (+ (expt (- (heroi-x heroi) (entidade-x entidade)) 2)
           (expt (- (heroi-y heroi) (entidade-y entidade)) 2))))

(defun mais-proxima (mundo tipo)
  (first (stable-sort
          (remove-if-not (lambda (entidade)
                           (and (corresponde-tipo-p entidade tipo)
                                (plusp (entidade-hp entidade))
                                (not (passagem-entre-p mundo (heroi-x (mundo-heroi mundo)) (entidade-x entidade)))))
                         (copy-list (mundo-entidades mundo)))
          (lambda (a b)
            (let ((da (distancia (mundo-heroi mundo) a))
                  (db (distancia (mundo-heroi mundo) b)))
              (or (< da db) (and (= da db) (< (entidade-id a) (entidade-id b)))))))))

(defun altura-chao (mundo x)
  (loop for (esquerda topo largura) in (mundo-plataformas mundo)
        when (<= esquerda x (+ esquerda largura)) minimize topo into altura
        finally (return (or altura 240))))

(defun rota-para (mundo x)
  "Grafo de superfícies da fase: arestas de caminhada e salto, no máximo 64 px de subida."
  (when (and (realp x) (<= 12 x (- (mundo-largura mundo) 12))
             (not (passagem-entre-p mundo (heroi-x (mundo-heroi mundo)) x)))
    (let* ((inicio (heroi-x (mundo-heroi mundo))) (direcao (if (> x inicio) 1 -1))
           (obstaculos (remove-if-not
                         (lambda (plataforma)
                           (and (/= 0 (fifth plataforma))
                                (< (min inicio x) (+ (first plataforma) (third plataforma)))
                                (> (max inicio x) (first plataforma))))
                         (mundo-plataformas mundo))))
      (when (every (lambda (p) (<= (- 240 (second p)) 64)) obstaculos)
        (append
         (mapcar (lambda (p) (list :salto (if (plusp direcao)
                                             (- (first p) 20)
                                             (+ (first p) (third p) 20))))
                 (sort (copy-list obstaculos) (if (plusp direcao) #'< #'>) :key #'first))
         (list (list :andar x)))))))

(defun alcancavel-p (mundo alvo)
  (and alvo (rota-para mundo (if (entidade-p alvo) (entidade-x alvo) alvo)) t))

(defun linha-livre-p (mundo entidade)
  (and entidade (plusp (entidade-hp entidade))
       (not (passagem-entre-p mundo (heroi-x (mundo-heroi mundo)) (entidade-x entidade)))
       (let* ((heroi (mundo-heroi mundo))
              (xa (heroi-x heroi)) (ya (- (heroi-y heroi) 16))
              (xb (entidade-x entidade)) (yb (- (entidade-y entidade) 12)))
         (loop for fracao from 0 to 20
               for x = (+ xa (* (/ fracao 20) (- xb xa)))
               for y = (+ ya (* (/ fracao 20) (- yb ya)))
               never (some (lambda (p)
                             (destructuring-bind (px py largura altura id) p
                               (declare (ignore id))
                               (and (< px x (+ px largura)) (< py y (+ py altura)))))
                           (mundo-plataformas mundo))))))

(defun marcos-progressao (classe)
  (declare (ignore classe))
  '((30 "ponto") (60 "ponto") (100 "ponto")))
(defun proximo-marco (heroi)
  (find-if (lambda (marco) (> (first marco) (heroi-xp heroi)))
           (marcos-progressao (heroi-classe heroi))))
(defun adicionar-efeito (mundo tipo x y &key valor (duracao 1.2))
  (push (list :tipo tipo :x x :y y :tempo 0 :duracao duracao :valor valor)
        (mundo-efeitos mundo)))
(defun conceder-xp (mundo pontos)
  (let* ((heroi (mundo-heroi mundo)) (anterior (heroi-xp heroi)))
    (incf (heroi-xp heroi) pontos)
    (atualizar-desbloqueios heroi)
    (dolist (marco (marcos-progressao (heroi-classe heroi)))
      (when (< anterior (first marco) (1+ (heroi-xp heroi)))
        (registrar mundo "Novo conhecimento disponível." :desbloqueio (second marco))))
    (adicionar-efeito mundo :xp (heroi-x heroi) (- (heroi-y heroi) 38) :valor pontos)))

(defun cancelar-acao (mundo &optional (motivo "Ação interrompida."))
  (let ((heroi (mundo-heroi mundo)))
    (when (heroi-acao heroi) (registrar mundo motivo))
    (setf (heroi-acao heroi) nil (heroi-estado heroi) :idle (heroi-vx heroi) 0)))

(defun acoes-validas-p (mundo intencao)
  (let ((heroi (mundo-heroi mundo)))
    (and (>= (heroi-mana heroi) (intencao-mana intencao))
         (every (lambda (acao)
                  (let ((alvo (buscar-entidade mundo (second acao))))
                    (case (first acao)
                      (:esperar t)
                      (:mover (alcancavel-p mundo (or alvo (second acao))))
                      (:coletar (and (coletavel-p mundo alvo)
                                     (eq (entidade-tipo alvo) :wood)))
                      (:minerar (and (coletavel-p mundo alvo)
                                     (member (entidade-tipo alvo) '(:iron-ore :arcane-crystal))))
                      ((:fugir :atacar :magia) (and alvo (inimigo-p alvo) (plusp (entidade-hp alvo))))
                      (otherwise nil))))
                (intencao-acoes intencao)))))

(defun iniciar-intencao (mundo intencao)
  (when (acoes-validas-p mundo intencao)
    (setf (heroi-acao (mundo-heroi mundo))
          (criar-execucao :intencao intencao :restantes (copy-tree (intencao-acoes intencao))
                         :alvos-movimento (loop for acao in (intencao-acoes intencao)
                                                when (and (eq (first acao) :mover)
                                                          (buscar-entidade mundo (second acao)))
                                                  collect (second acao))))
    t))

(defun mover-heroi (mundo destino)
  (let* ((heroi (mundo-heroi mundo)) (diferenca (- destino (heroi-x heroi)))
         (direcao (signum diferenca)))
    (setf (heroi-vx heroi) (* direcao 72) (heroi-estado heroi) :walk)
    (unless (zerop direcao) (setf (heroi-direcao heroi) direcao))
    (when (and (= (heroi-vy heroi) 0)
               (< (altura-chao mundo (+ (heroi-x heroi) (* direcao 22)))
                  (heroi-y heroi)))
      (setf (heroi-vy heroi) -300 (heroi-estado heroi) :jump))
    (when (< (abs diferenca) 3) (setf (heroi-vx heroi) 0) t)))

(defun subir-proxima-acao (heroi execucao)
  (pop (execucao-restantes execucao))
  (setf (execucao-tempo execucao) 0 (execucao-iniciada execucao) nil)
  (unless (execucao-restantes execucao)
    (setf (heroi-acao heroi) nil (heroi-estado heroi) :idle)))

(defun executar-acao (mundo)
  (let* ((heroi (mundo-heroi mundo)) (execucao (heroi-acao heroi)))
    (when execucao
      (let* ((acao (first (execucao-restantes execucao))) (tipo (first acao))
             (alvo (buscar-entidade mundo (second acao)))
             (intencao (execucao-intencao execucao)))
        (when (and (not (execucao-iniciada execucao))
                   (or (member tipo '(:fugir :coletar :minerar :atacar :magia))
                       (and (eq tipo :mover) (member (second acao) (execucao-alvos-movimento execucao))))
                   (or (null alvo) (not (plusp (entidade-hp alvo)))))
          (cancelar-acao mundo "O alvo deixou de existir.")
          (return-from executar-acao))
        (incf (execucao-tempo execucao) +passo+)
        (setf (heroi-vx heroi) 0)
        (case tipo
          (:mover
           (if (alcancavel-p mundo (or alvo (second acao)))
               (when (mover-heroi mundo (if alvo (entidade-x alvo) (second acao)))
                 (subir-proxima-acao heroi execucao))
               (cancelar-acao mundo "Não há caminho até o destino.")))
          (:fugir
           (let ((destino (max 12 (min (- (mundo-largura mundo) 12) (+ (heroi-x heroi)
                                  (* (if (< (entidade-x alvo) (heroi-x heroi)) 1 -1) 100))))))
             (mover-heroi mundo destino)
             (when (>= (execucao-tempo execucao) 1) (subir-proxima-acao heroi execucao))))
          (:esperar
           (setf (heroi-estado heroi) :idle)
           (when (>= (execucao-tempo execucao) (or (second acao) 0.5))
             (subir-proxima-acao heroi execucao)))
          ((:coletar :minerar :atacar :magia)
           (let ((alcance (if (eq tipo :magia) 160 30)))
             (unless (or (execucao-iniciada execucao)
                         (and (<= (distancia heroi alvo) alcance)
                          (or (not (eq tipo :magia)) (linha-livre-p mundo alvo)))
                         )
               (cancelar-acao mundo "O alvo saiu do alcance ou da linha de visão.")
               (return-from executar-acao)))
           (setf (heroi-estado heroi) (case tipo ((:coletar :minerar) :gather) (:magia :cast) (t :attack)))
           (when (and alvo (/= (entidade-x alvo) (heroi-x heroi)))
             (setf (heroi-direcao heroi) (signum (- (entidade-x alvo) (heroi-x heroi)))))
           ;; O efeito ocorre no impacto; a recuperação visual termina depois.
           (when (and (not (execucao-iniciada execucao))
                      (>= (execucao-tempo execucao)
                          (case tipo (:coletar 0.4) (:minerar (getf (especificacao-especie (entidade-tipo alvo)) :duracao)) (:atacar 0.3)
                            (t (intencao-duracao intencao)))))
             (when (eq tipo :magia)
               (when (< (heroi-mana heroi) (intencao-mana intencao))
                 (cancelar-acao mundo "Mana insuficiente ao concluir a conjuração.")
                 (return-from executar-acao))
               (decf (heroi-mana heroi) (intencao-mana intencao)))
             (setf (execucao-iniciada execucao) t)
             (if (member tipo '(:coletar :minerar))
                 (when (coletavel-p mundo alvo)
                   (let ((especie (especificacao-especie (entidade-tipo alvo))))
                     (incf (quantidade-material heroi (entidade-tipo alvo)))
                     (conceder-xp mundo (getf especie :xp))
                     (setf (entidade-hp alvo) 0 (entidade-retorno alvo) (getf especie :retorno))
                     (registrar mundo (format nil "~A coletado." (getf especie :nome)))))
                 (progn
                   (unless (member (entidade-fase alvo) '(:windup :recovery))
                     (setf (entidade-animacao alvo) :hurt (entidade-tempo-animacao alvo) 0))
                   (when (eq tipo :magia)
                     (adicionar-efeito mundo (third acao) (entidade-x alvo) (- (entidade-y alvo) 16) :duracao 0.4))
                   (let ((dano (+ (bonus-dano heroi)
                                 (cond ((equal (third acao) "lightning") 40)
                                       ((eq tipo :magia) 24)
                                       ((equal (third acao) ":heavy-strike") 28) (t 18)))))
                     (when (and (eq (entidade-tipo alvo) :guardian) (eq (entidade-fase alvo) :windup))
                       (setf dano (/ dano 2)))
                     (decf (entidade-hp alvo) dano)
                     (adicionar-efeito mundo :dano (entidade-x alvo) (- (entidade-y alvo) 32) :valor dano))
                   (when (<= (entidade-hp alvo) 0) (derrotar-entidade mundo alvo)))))
           (when (>= (execucao-tempo execucao)
                     (case tipo (:magia (intencao-duracao intencao))
                       (:minerar (+ 0.2 (getf (especificacao-especie (entidade-tipo alvo)) :duracao))) (t 0.6)))
             (subir-proxima-acao heroi execucao))))))))

(defun aplicar-fisica (mundo)
  (let* ((heroi (mundo-heroi mundo)) (antes-x (heroi-x heroi)) (antes-y (heroi-y heroi)))
    (incf (heroi-vy heroi) (* 600 +passo+))
    (setf (heroi-x heroi) (max 12 (min (- (mundo-largura mundo) 12) (+ antes-x (* (heroi-vx heroi) +passo+)))))
    (incf (heroi-y heroi) (* (heroi-vy heroi) +passo+))
    (dolist (p (append (mundo-plataformas mundo) (colisoes-passagens mundo)))
      (destructuring-bind (px py largura altura id) p
        (declare (ignore id))
        (when (and (< (- (heroi-x heroi) 7) (+ px largura)) (> (+ (heroi-x heroi) 7) px)
                   (<= antes-y py) (>= (heroi-y heroi) py) (>= (heroi-vy heroi) 0))
          (setf (heroi-y heroi) py (heroi-vy heroi) 0))
        (when (and (< (- (heroi-x heroi) 7) (+ px largura)) (> (+ (heroi-x heroi) 7) px)
                   (>= (- antes-y 26) (+ py altura)) (< (- (heroi-y heroi) 26) (+ py altura))
                   (minusp (heroi-vy heroi)))
          (setf (heroi-y heroi) (+ py altura 26) (heroi-vy heroi) 0))
        (when (and (< (- (heroi-y heroi) 26) (+ py altura)) (> (heroi-y heroi) (+ py 1)))
          (cond ((and (<= (+ antes-x 7) px) (> (+ (heroi-x heroi) 7) px))
                 (setf (heroi-x heroi) (- px 7)))
                ((and (>= (- antes-x 7) (+ px largura))
                      (< (- (heroi-x heroi) 7) (+ px largura)))
                 (setf (heroi-x heroi) (+ px largura 7)))))))
    (unless (zerop (heroi-vy heroi)) (setf (heroi-estado heroi) :jump))))

(defun atualizar-inimigos (mundo)
  (let ((heroi (mundo-heroi mundo)))
    (dolist (entidade (mundo-entidades mundo))
      (incf (entidade-tempo-animacao entidade) +passo+)
      (let ((especie (especificacao-especie (entidade-tipo entidade))))
        (cond
          ((<= (entidade-hp entidade) 0)
           (when (plusp (getf especie :retorno 0))
             (decf (entidade-retorno entidade) +passo+)
             (when (<= (entidade-retorno entidade) 0) (restaurar-entidade mundo entidade))))
          ((and (inimigo-p entidade) (eq (entidade-tipo entidade) :slime))
           (when (>= (entidade-tempo-animacao entidade) 0.4) (mudar-animacao entidade :idle))
           (setf (entidade-recarga entidade) (max 0 (- (entidade-recarga entidade) +passo+)))
           (when (and (< (distancia heroi entidade) (getf especie :alcance))
                      (<= (entidade-recarga entidade) 0) (plusp (heroi-hp heroi))
                      (linha-livre-p mundo entidade))
             (ferir-heroi mundo (getf especie :dano))
             (setf (entidade-recarga entidade) 1) (mudar-animacao entidade :attack)))
          ((inimigo-p entidade) (atualizar-inimigo-anunciado mundo entidade especie)))))))

(defun avancar (mundo avaliador)
  "Executa exatamente um tick. AVALIADOR recebe apenas uma fotografia dos fatos."
  (incf (mundo-tick mundo))
  (dolist (efeito (mundo-efeitos mundo)) (incf (getf efeito :tempo) +passo+))
  (setf (mundo-efeitos mundo) (remove-if (lambda (efeito) (>= (getf efeito :tempo) (getf efeito :duracao 0.4))) (mundo-efeitos mundo)))
  (setf (heroi-ferimento (mundo-heroi mundo)) (max 0 (- (heroi-ferimento (mundo-heroi mundo)) +passo+)))
  (let* ((heroi (mundo-heroi mundo)) (estado-anterior (heroi-estado heroi)))
    (cond
      ((not (plusp (heroi-hp heroi)))
       (unless (eq (heroi-estado heroi) :death)
         (cancelar-acao mundo "Autômato derrotado.")
         (reiniciar-chefe mundo)
         (setf (heroi-morte heroi) 3 (heroi-estado heroi) :death))
       (decf (heroi-morte heroi) +passo+)
       (when (<= (heroi-morte heroi) 0)
         (setf (heroi-hp heroi) (heroi-hp-max heroi) (heroi-x heroi) (getf (regiao-atual mundo) :entrada)
               (heroi-y heroi) 240 (heroi-vy heroi) 0 (heroi-estado heroi) :idle)))
      (t
       (setf (heroi-mana heroi) (min (heroi-mana-max heroi) (+ (heroi-mana heroi) (* 4 +passo+))))
       ;; Recupera-se em segurança também ao esperar ou se deslocar, sem
       ;; depender do intervalo de um tick entre intenções consecutivas.
       (when (and (> (distancia-seguranca mundo) 90)
                  (not (and (heroi-acao heroi)
                            (member (caar (execucao-restantes (heroi-acao heroi)))
                                    '(:atacar :magia :coletar :minerar)))))
         (setf (heroi-hp heroi) (min (heroi-hp-max heroi) (+ (heroi-hp heroi) (* 3 +passo+)))))
       (let* ((resultado (funcall avaliador (fotografar mundo)))
              (intencao (resultado-intencao resultado)) (atual (heroi-acao heroi)))
         (setf (mundo-ultimo-resultado mundo) resultado (mundo-diagnostico mundo) (resultado-motivo resultado))
         (dolist (falha (resultado-falhas resultado))
           (setf (gethash (first falha) (mundo-falhas mundo)) (+ (mundo-tick mundo) 60))
           (adicionar-efeito mundo :fizzle (heroi-x heroi) (- (heroi-y heroi) 42) :duracao 0.8)
           (registrar mundo (format nil "Fizzle: ~A — ~A" (first falha) (second falha))
                      :nome (first falha) :motivo (second falha) :idioma (third falha)))
         (when (and intencao
                    (or (null atual)
                        (and (or (zerop (execucao-tempo atual))
                                 (not (member (first (first (execucao-restantes atual))) '(:atacar :magia :coletar :minerar))))
                             (> (intencao-prioridade intencao)
                                (intencao-prioridade (execucao-intencao atual))))))
           (when atual (cancelar-acao mundo))
           (iniciar-intencao mundo intencao)))
       (executar-acao mundo)
       (aplicar-fisica mundo)
       (atualizar-inimigos mundo)))
    (setf (heroi-tempo-animacao heroi)
          (if (eq estado-anterior (heroi-estado heroi))
              (+ (heroi-tempo-animacao heroi) +passo+) 0)))
  (atualizar-campanha mundo)
  mundo)

(defun distancia-seguranca (mundo)
  (let ((alvo (mais-proxima mundo :inimigo)))
    (if alvo (distancia (mundo-heroi mundo) alvo) 9999)))
(defun simular (mundo avaliador segundos)
  (dotimes (indice (round (* segundos 60)) mundo)
    (declare (ignorable indice)) (avancar mundo avaliador)))
(defun estado-resumido (mundo)
  (let ((heroi (mundo-heroi mundo)))
    (list :tick (mundo-tick mundo) :classe (heroi-classe heroi)
          :x (heroi-x heroi) :y (heroi-y heroi) :hp (heroi-hp heroi)
          :mana (heroi-mana heroi) :xp (heroi-xp heroi) :madeira (heroi-madeira heroi))))
