(in-package #:qed.nucleo)

(defparameter *ontologia*
  (let ((*read-eval* nil))
    (with-open-file (fluxo (asdf:system-relative-pathname "qed/core" "dados/ontologia.sexp")
                           :external-format :utf-8)
      (read fluxo))))

(defun areas-ontologia (classe)
  (remove-if-not (lambda (area) (member classe (getf area :classes))) *ontologia*))
(defun buscar-area (heroi identificador)
  (find identificador (areas-ontologia (heroi-classe heroi))
        :key (lambda (area) (getf area :id)) :test #'equal))
(defun area-liberada-p (heroi identificador)
  (let ((area (buscar-area heroi identificador)))
    (and area (or (zerop (getf area :custo))
                  (member identificador (heroi-conhecimentos heroi) :test #'equal)) t)))
(defun pontos-conhecimento (heroi)
  (- (+ (heroi-pontos-bonus heroi)
        (count-if (lambda (xp) (>= (heroi-xp heroi) xp)) '(30 60 100)))
     (loop for id in (heroi-conhecimentos heroi)
           sum (getf (buscar-area heroi id) :custo 0))))
(defun situacao-area (heroi identificador)
  (let ((area (buscar-area heroi identificador)))
    (cond ((null area) :inexistente)
          ((area-liberada-p heroi identificador) :liberada)
          ((not (every (lambda (id) (area-liberada-p heroi id)) (getf area :requisitos))) :requisitos)
          ((< (pontos-conhecimento heroi) (getf area :custo)) :sem-pontos)
          (t :disponivel))))
(defun atualizar-desbloqueios (heroi)
  (setf (heroi-desbloqueios heroi)
        (loop for area in (areas-ontologia (heroi-classe heroi))
              when (and (getf area :libera) (area-liberada-p heroi (getf area :id)))
                collect (getf area :libera))
        (heroi-slots heroi) (if (area-liberada-p heroi "composicao") 5 4)))
(defun desbloquear-area (mundo identificador)
  "Compra atômica: validar classe, dependências e saldo antes de liberar vocabulário."
  (let* ((heroi (mundo-heroi mundo)) (situacao (situacao-area heroi identificador)))
    (when (eq situacao :disponivel)
      (push identificador (heroi-conhecimentos heroi))
      (atualizar-desbloqueios heroi)
      (clrhash (mundo-falhas mundo))
      (registrar mundo "Área de ontologia desbloqueada." :area identificador)
      (return-from desbloquear-area (values t :liberada)))
    (values nil situacao)))
