;; Gera o executável local com o runtime SBCL e os sistemas já carregados.
(require :asdf)
(unless (find-package :ql)
  (load (or (uiop:getenv "QED_QUICKLISP")
            (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))))
(let ((raiz (uiop:pathname-directory-pathname *load-truename*)))
  (asdf:load-asd (merge-pathnames "qed.asd" raiz))
  (uiop:symbol-call :ql :quickload "qed/app" :silent t)
  ;; O handle FreeType é memória C, que não pode atravessar a imagem SBCL.
  (let* ((biblioteca (symbol-value (find-symbol "*LIBRARY*" :ft2)))
         (ponteiro (uiop:symbol-call :ft2-types :fw-ptr biblioteca)))
    (uiop:symbol-call :trivial-garbage :cancel-finalization biblioteca)
    (uiop:symbol-call :freetype2-ffi :ft-done-freetype (uiop:symbol-call :cffi :mem-ref ponteiro :pointer))
    (uiop:symbol-call :ft2-types :libc-free ponteiro)
    (setf (symbol-value (find-symbol "*LIBRARY*" :ft2)) nil))
  (let ((destino (merge-pathnames "build/qed" raiz)))
    (ensure-directories-exist destino)
    (format t "Compilando QED em ~A~%" destino)
    (sb-ext:save-lisp-and-die (namestring destino)
                            :toplevel (find-symbol "INICIAR-EXECUTAVEL" :qed.aplicativo)
                            :executable t :compression t :save-runtime-options t)))
