;; Entrada portátil: SBCL --script iniciar.lisp [opções].
(require :asdf)
(unless (find-package :ql)
  (let ((configuracao (or (uiop:getenv "QED_QUICKLISP") (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))))
    (unless (probe-file configuracao) (error "Quicklisp ausente. Defina QED_QUICKLISP."))
    (load configuracao)))
(asdf:load-asd (merge-pathnames "qed.asd" *load-truename*))
(let* ((argumentos (uiop:command-line-arguments))
       (testes (member "--testes" argumentos :test #'equal))
       (simulacao (member "--simular" argumentos :test #'equal))
       (sistema (cond (testes "qed/tests") (simulacao "qed/logic") (t "qed/app"))))
  (uiop:symbol-call :ql :quickload sistema :silent t)
  (cond
    (testes (asdf:test-system "qed/tests"))
    (simulacao
     (let ((sessao (uiop:symbol-call :qed.logica :nova-sessao))
           (segundos (parse-integer (or (second simulacao) "1800"))))
       (dotimes (classe 2)
         (declare (ignorable classe))
         (dotimes (tick (* segundos 60)) (declare (ignorable tick)) (uiop:symbol-call :qed.logica :avancar-sessao sessao))
         (format t "~S~%" (uiop:symbol-call :qed.nucleo :estado-resumido (uiop:symbol-call :qed.logica :mundo-ativo sessao)))
         (uiop:symbol-call :qed.logica :alternar-personagem sessao))))
    (t
     (let ((quadros (second (member "--quadros" argumentos :test #'equal)))
           (captura (second (member "--captura" argumentos :test #'equal)))
           (duracao (second (member "--duracao" argumentos :test #'equal)))
           (largura (second (member "--largura" argumentos :test #'equal)))
           (altura (second (member "--altura" argumentos :test #'equal)))
           (posicao (second (member "--posicao" argumentos :test #'equal))))
       (uiop:symbol-call :qed.aplicativo :executar
                        :quadros (and quadros (parse-integer quadros))
                        :duracao (and duracao (parse-integer duracao))
                        :ensaio-real (member "--ensaio-real" argumentos :test #'equal)
                        :mundo-ampliado (member "--mundo" argumentos :test #'equal)
                        :ontologia (member "--ontologia" argumentos :test #'equal)
                        :acampamento (member "--acampamento" argumentos :test #'equal)
                        :largura-inicial (if largura (parse-integer largura) 1440)
                        :altura-inicial (if altura (parse-integer altura) 900)
                        :posicao-inicial (and posicao (parse-integer posicao))
                        :captura (and captura (pathname captura))
                        :oculta (member "--oculta" argumentos :test #'equal)
                        :ensaio (member "--ensaio" argumentos :test #'equal)
                        :salvar (not (member "--sem-salvar" argumentos :test #'equal)))))))
