(defpackage #:qed.testes
  (:use #:cl #:fiveam #:qed.nucleo #:qed.logica)
  (:export #:executar))
(in-package #:qed.testes)
(def-suite suite-qed)
(in-suite suite-qed)
(defun biblioteca-guerreiro (texto) (ler-biblioteca texto :classe :fighter))
(defun biblioteca-mago (texto) (ler-biblioteca texto :classe :wizard))
(defun avaliar-texto (texto &optional (mundo (novo-mundo)))
  (avaliar-biblioteca (ler-biblioteca texto :classe (heroi-classe (mundo-heroi mundo))) mundo))
(defun nome-vencedor (resultado)
  (and (resultado-intencao resultado) (intencao-nome (resultado-intencao resultado))))
(defun mago-centelha (&optional (dados "") (efeito "(manifest :spark :target enemy)"))
  (format nil "(theorem conjurar :class wizard :goal (prove (strikes spark enemy) :given (~A)) :on-success ~A :on-failure (fizzle :reason))" dados efeito))

(test prioridade-e-desempate
  (is (equal "primeiro" (nome-vencedor (avaliar-texto
    "(teorema baixo :prioridade 1 :premissas () :conclusao (esperar))
     (teorema primeiro :prioridade 20 :premissas () :conclusao (esperar))
     (teorema segundo :prioridade 20 :premissas () :conclusao (esperar))")))))
(test ocioso-sem-regra
  (let ((resultado (avaliar-texto "(teorema nunca :premissas ((< (atributo :vida) 0)) :conclusao (esperar))")))
    (is (null (resultado-intencao resultado))) (is (eq :nenhuma-correspondencia (resultado-motivo resultado)))))
(test bilingue
  (let ((ingles (biblioteca-guerreiro "(theorem exemplo :priority 10 :premises ((state :idle)) :conclusion (move-to (nearest resource :wood)))"))
        (portugues (biblioteca-guerreiro "(teorema exemplo :prioridade 10 :premissas ((estado :ocioso)) :conclusao (mover-para (mais-proximo recurso :madeira)))")))
    (is (equal (definicao-arvore (first (biblioteca-definicoes ingles))) (definicao-arvore (first (biblioteca-definicoes portugues)))))
    (is (eq :en (definicao-idioma (first (biblioteca-definicoes ingles)))))
    (is (eq :pt (definicao-idioma (first (biblioteca-definicoes portugues)))))))
(test mistura-e-acentos
  (is (equal "ação" (nome-vencedor (avaliar-texto "(teorema ação :priority 2 :premissas ((não (< (stat :vida) 1))) :conclusão (wait))")))))
(test lemas-e-existencial
  (is (equal "recolher" (nome-vencedor (avaliar-texto
    "(lema tem-madeira () (existe (r recurso) (tipo-recurso r :madeira)))
     (teorema recolher :premissas ((tem-madeira)) :conclusao (esperar))"))))
  (is (equal "teste" (nome-vencedor (avaliar-texto
    "(lema menor (valor limite) (< valor limite))
     (teorema teste :premissas ((menor 2 3)) :conclusao (esperar))")))))
(test nomes-vinculados-preservados
  (let ((biblioteca (biblioteca-guerreiro "(lema comparar (estado) (< estado 3)) (teorema testar :premissas ((comparar 2)) :conclusao (esperar))")))
    (is (equal '(("comparar" ("estado") ("<" "estado" 3))) (biblioteca-lemas biblioteca)))
    (is (equal "testar" (nome-vencedor (avaliar-biblioteca biblioteca (novo-mundo)))))))
(test rejeicoes-sintaticas
  (dolist (texto '("#. (progn (delete-file \"alvo\"))" "(cl:eval 1)" "(a . b)" "#1=(a . #1#)" "'(x)"
                   "(teorema x :premissas () :conclusao (eval 1))"
                   "(teorema x :premissas ((esperar)) :conclusao (esperar))"
                   "(teorema x :prioridade 1 :prioridade 2 :premissas () :conclusao (esperar))"
                   "(lema a () (b)) (lema b () (a))"
                   "(teorema x :premissas ((< nao-vinculada 2)) :conclusao (esperar))"
                   "(hipótese futuro)" "(teorema x :classe paladino :premissas () :conclusao (esperar))"))
    (signals erro-dsl (biblioteca-guerreiro texto))))
(test limites-leitura
  (signals erro-dsl (ler-dados-seguros (make-string 65537 :initial-element #\a)))
  (signals erro-dsl (ler-dados-seguros (concatenate 'string (make-string 49 :initial-element #\() "1" (make-string 49 :initial-element #\)))))
  (signals erro-dsl (ler-dados-seguros "1000000001")))
(test biblioteca-atomica
  (let* ((sessao (nova-sessao)) (anterior (biblioteca-ativa sessao)))
    (signals erro-dsl (aplicar-biblioteca sessao "(teorema incompleto"))
    (is (eq anterior (biblioteca-ativa sessao)))))
(test dependencias-compartilhadas-nao-expandem-validacao
  (let ((texto (with-output-to-string (saida)
                 (write-line "(lema p0 () (< 1 2))" saida)
                 (loop for indice from 1 to 30 do
                   (format saida "(lema p~D () (e (p~D) (p~D)))~%" indice (1- indice) (1- indice)))
                 (write-line "(teorema verificar :premissas ((p30)) :conclusao (esperar))" saida))))
    (is (equal "verificar" (nome-vencedor (avaliar-texto texto))))))
(test unificacao
  (multiple-value-bind (vinculos sucesso) (unificar '("p" "?x" "?y") '("p" "?y" "?x"))
    (is (not (null sucesso))) (is (equal (substituir "?x" vinculos) (substituir "?y" vinculos))))
  (multiple-value-bind (vinculos sucesso) (unificar '("p" 1) '("p" 1))
    (is (not (null sucesso))) (is (null vinculos)))
  (multiple-value-bind (vinculos sucesso) (unificar "?x" '("f" "?x"))
    (declare (ignore vinculos)) (is (null sucesso)))
  (multiple-value-bind (vinculos sucesso) (unificar '("p" "?x" "?x") '("p" 1 2))
    (declare (ignore vinculos)) (is (null sucesso))))
(test prova-e-retrocesso
  (let ((axiomas (list (criar-axioma :nome "falha" :cabeca '("p" "?x") :corpo '(("impossivel" "?x")))
                       (criar-axioma :nome "sucesso" :cabeca '("p" 7) :corpo nil))))
    (let ((qed.logica::*resolucoes* 256) (qed.logica::*operacoes* 8192))
      (multiple-value-bind (vinculos prova sucesso) (provar '("p" "?alvo") (novo-mundo :wizard) axiomas)
        (is (not (null sucesso))) (is (= 7 (substituir "?alvo" vinculos))) (is (equal "sucesso" (getf (first prova) :axioma)))))))
(test limite-prova
  (let ((qed.logica::*resolucoes* 20) (qed.logica::*operacoes* 8192))
    (multiple-value-bind (vinculos prova sucesso motivo)
        (provar '("ciclo" 1) (novo-mundo :wizard)
                (list (criar-axioma :nome "circular" :cabeca '("ciclo" "?x") :corpo '(("ciclo" "?x")))))
      (declare (ignore vinculos prova))
      (is (null sucesso)) (is (eq :orcamento-esgotado motivo)))))
(test prova-mago-real
  (let* ((mundo (novo-mundo :wizard)) (heroi (mundo-heroi mundo)))
    (setf (heroi-x heroi) 280)
    (let* ((antes (estado-resumido mundo)) (resultado (avaliar-texto (mago-centelha) mundo)) (intencao (resultado-intencao resultado)))
      (is (not (null intencao))) (is (plusp (intencao-passos intencao)))
      (is (= (intencao-mana intencao) (+ 8 (* 2 (intencao-passos intencao)))))
      (is (equal antes (estado-resumido mundo)))
      (is (equal '((:magia 2 "spark")) (intencao-acoes intencao))))))
(test prova-mago-vincula-alvo
  (let ((mundo (novo-mundo :wizard)))
    (setf (heroi-x (mundo-heroi mundo)) 280)
    (let* ((texto "(theorem escolher :class wizard :goal (prove (strikes spark ?alvo)) :on-success (manifest :spark :target ?alvo) :on-failure (fizzle :reason))")
           (resultado (avaliar-texto texto mundo))
           (intencao (resultado-intencao resultado)))
      (is (not (null intencao)))
      (is (equal '((:magia 2 "spark")) (intencao-acoes intencao))))))
(test dado-falso-nao-cria-fato
  (let ((mundo (novo-mundo :wizard)))
    (setf (heroi-x (mundo-heroi mundo)) 280)
    (let ((resultado (avaliar-texto (mago-centelha "(mana-available 999)") mundo)))
      (is (null (resultado-intencao resultado))) (is (eq :dado-falso (second (first (resultado-falhas resultado))))))))
(test axiomas-vazios-nao-liberam-base-inteira
  (let ((resultado (avaliar-texto
                    "(teorema aguardar :classe mago :objetivo (provar (pode-esperar) :usando-axiomas ()) :ao-sucesso (esperar) :ao-falha (falhar :motivo))"
                    (novo-mundo :wizard))))
    (is (null (resultado-intencao resultado)))))
(test fuga-exige-inimigo
  (let* ((mundo (novo-mundo :wizard))
         (resultado (avaliar-texto
                     "(teorema recuar :classe mago :objetivo (provar (pode-fugir 1)) :ao-sucesso (fugir 1) :ao-falha (falhar :motivo))"
                     mundo)))
    (is (null (resultado-intencao resultado)))))
(test conducao-e-relampago-bilingues
  (let* ((mundo (novo-mundo :wizard))
         (portugues "(teorema tempestade-local :classe mago :objetivo (provar (atinge relâmpago inimigo) :dado ((molhado inimigo)) :usando-axiomas (afinidade-elemental condução-tempestade lei-relâmpago)) :ao-sucesso (manifestar :raio :alvo inimigo) :ao-falha (falhar :motivo))")
         (ingles "(theorem tempestade-local :class wizard :goal (prove (strikes lightning enemy) :given ((wet enemy)) :using-axioms (elemental-affinity storm-conduction lightning-law)) :on-success (manifest :lightning-bolt :target enemy) :on-failure (fizzle :reason))"))
    (setf (heroi-x (mundo-heroi mundo)) 690)
    (is (null (resultado-intencao (avaliar-texto portugues mundo))))
    (conceder-xp mundo 60)
    (desbloquear-area mundo "conducao")
    (desbloquear-area mundo "tempestade")
    (let ((pt (resultado-intencao (avaliar-texto portugues mundo)))
          (en (resultado-intencao (avaliar-texto ingles mundo))))
      (is (not (null pt)))
      (is (equal '((:magia 4 "lightning")) (intencao-acoes pt)))
      (is (equal (intencao-acoes pt) (intencao-acoes en)))
      (is (= (intencao-mana pt) (intencao-mana en))))))
(test lema-reutilizado-cobra-dependencias
  (let* ((mundo (novo-mundo :wizard))
         (texto "(lema preparado () (e (mana-disponivel 0) (linha-de-visao inimigo)))
                 (teorema conjurar :classe mago :objetivo (provar (atinge centelha inimigo) :dado ((preparado) (preparado))) :ao-sucesso (manifestar :centelha :alvo inimigo) :ao-falha (falhar :motivo))"))
    (setf (heroi-x (mundo-heroi mundo)) 280)
    (let* ((intencao (resultado-intencao (avaliar-texto texto mundo)))
           (prova (intencao-prova intencao)))
      (is (= 4 (getf (first prova) :custo)))
      (is (= 1 (getf (second prova) :custo)))
      (is (= (intencao-mana intencao)
             (+ 8 (* 2 (reduce #'+ prova :key (lambda (no) (getf no :custo))))))))))
(test efeito-incompativel
  (let ((mundo (novo-mundo :wizard)))
    (setf (heroi-x (mundo-heroi mundo)) 280)
    (let ((resultado (avaliar-texto (mago-centelha "" "(manifest :lightning-bolt :target enemy)") mundo)))
      (is (null (resultado-intencao resultado))) (is (eq :efeito-incompativel (second (first (resultado-falhas resultado))))))))
(test mana-e-fizzle
  (let ((sessao (nova-sessao)))
    (alternar-personagem sessao)
    (setf (heroi-x (mundo-heroi (mundo-ativo sessao))) 280 (heroi-mana (mundo-heroi (mundo-ativo sessao))) 0)
    (aplicar-biblioteca sessao (mago-centelha))
    (avancar-sessao sessao)
    (is (null (heroi-acao (mundo-heroi (mundo-ativo sessao)))))
    (is (> (gethash "conjurar" (mundo-falhas (mundo-ativo sessao)) 0) 1))
    (is (= (heroi-mana (mundo-heroi (mundo-ativo sessao))) 1/15))))
(test mago-utilitario
  (let ((resultado (avaliar-texto
     "(teorema andar :classe mago :objetivo (provar (pode-mover (mais-proximo recurso :madeira))) :ao-sucesso (mover-para (mais-proximo recurso :madeira)) :ao-falha (falhar :motivo))"
     (novo-mundo :wizard))))
    (is (equal '((:mover 1)) (intencao-acoes (resultado-intencao resultado))))
    (is (= 0 (intencao-mana (resultado-intencao resultado))))))
(test mago-coleta-em-plataforma-e-retoma-movimento
  (let* ((mundo (novo-mundo :wizard))
         (heroi (mundo-heroi mundo))
         (madeira-elevada (buscar-entidade mundo 7))
         (biblioteca (biblioteca-mago
          "(theorem gather :class wizard :priority 60
             :goal (prove (can-gather (nearest resource :wood)) :using-axioms (gather-law))
             :on-success (interact :chop) :on-failure (fizzle :reason))
           (theorem explore :class wizard :priority 50
             :goal (prove (can-move (nearest resource :wood)) :using-axioms (travel-law))
             :on-success (move-to (nearest resource :wood)) :on-failure (fizzle :reason))")))
    (is (= (entidade-y madeira-elevada) (altura-chao mundo (entidade-x madeira-elevada))))
    (setf (heroi-x heroi) (entidade-x madeira-elevada)
          (heroi-y heroi) (entidade-y madeira-elevada))
    (let ((madeira-antes (heroi-madeira heroi)))
      (simular mundo (lambda (foto) (avaliar-biblioteca biblioteca foto)) 2)
      (is (> (heroi-madeira heroi) madeira-antes))
      (is (/= (heroi-x heroi) (entidade-x madeira-elevada))))))
(test vocabulario-bloqueado
  (let ((mundo (novo-mundo)))
    (setf (heroi-x (mundo-heroi mundo)) 280)
    (is (null (resultado-intencao (avaliar-texto "(teorema golpe :premissas () :conclusao (atacar :golpe-pesado))" mundo))))
    (conceder-xp mundo 60)
    (desbloquear-area mundo "impacto")
    (is (not (null (resultado-intencao (avaliar-texto "(teorema golpe :premissas () :conclusao (atacar :golpe-pesado))" mundo)))))))
(test desbloqueios-e-slots
  (let ((mundo (novo-mundo)) (mago (novo-mundo :wizard)))
    (conceder-xp mundo 30)
    (is (= 1 (pontos-conhecimento (mundo-heroi mundo))))
    (is (null (heroi-desbloqueios (mundo-heroi mundo))))
    (is (desbloquear-area mundo "estados"))
    (is (member "status" (heroi-desbloqueios (mundo-heroi mundo)) :test #'equal))
    (conceder-xp mundo 30)
    (is (desbloquear-area mundo "impacto"))
    (is (member ":heavy-strike" (heroi-desbloqueios (mundo-heroi mundo)) :test #'equal))
    (conceder-xp mundo 40)
    (is (= 4 (heroi-slots (mundo-heroi mundo))))
    (is (desbloquear-area mundo "composicao"))
    (is (= 5 (heroi-slots (mundo-heroi mundo))))
    (conceder-xp mago 60)
    (is (null (find "lightning-law" (axiomas-iniciais mago) :key #'axioma-nome :test #'equal)))
    (is (desbloquear-area mago "conducao"))
    (is (desbloquear-area mago "tempestade"))
    (is (find "lightning-law" (axiomas-iniciais mago) :key #'axioma-nome :test #'equal))))
(test simulacao-deterministica
  (let ((a (nova-sessao)) (b (nova-sessao)))
    (dotimes (i 1800) (declare (ignorable i)) (avancar-sessao a))
    (dotimes (quadro 900) (declare (ignorable quadro)) (dotimes (i 2) (declare (ignorable i)) (avancar-sessao b)))
    (is (equal (estado-resumido (mundo-ativo a)) (estado-resumido (mundo-ativo b))))
    (is (plusp (heroi-xp (mundo-heroi (mundo-ativo a)))))
    (is (plusp (heroi-madeira (mundo-heroi (mundo-ativo a)))))))
(test alternancia-congela
  (let ((sessao (nova-sessao)))
    (dotimes (i 120) (declare (ignorable i)) (avancar-sessao sessao))
    (let* ((guerreiro (mundo-ativo sessao)) (antes (estado-resumido guerreiro)))
      (alternar-personagem sessao)
      (dotimes (i 120) (declare (ignorable i)) (avancar-sessao sessao))
      (is (equal antes (estado-resumido guerreiro)))
      (is (null (heroi-acao (mundo-heroi guerreiro)))))))
(test salto-e-colisao
  (let* ((mundo (novo-mundo)) (heroi (mundo-heroi mundo)) (saltou nil))
    (setf (heroi-x heroi) 330)
    (dotimes (i 250)
      (declare (ignorable i))
      (avancar mundo (lambda (foto) (declare (ignore foto))
                      (criar-resultado :intencao (criar-intencao :nome "rota" :acoes '((:mover 470))))))
      (when (< (heroi-y heroi) 208) (setf saltou t)))
    (is (not (null saltou))) (is (> (heroi-x heroi) 440)) (is (<= (heroi-y heroi) 240))))
(test prioridade-interrompe-movimento
  (let* ((mundo (novo-mundo)) (heroi (mundo-heroi mundo)) (passo 0))
    (labels ((avaliador (fotografia)
               (declare (ignore fotografia))
               (incf passo)
               (criar-resultado
                :intencao (if (< passo 3)
                              (criar-intencao :nome "andar" :prioridade 10 :acoes '((:mover 900)))
                              (criar-intencao :nome "urgente" :prioridade 100 :acoes '((:esperar 0.5)))))))
      (avancar mundo #'avaliador)
      (is (equal "andar" (intencao-nome (execucao-intencao (heroi-acao heroi)))))
      (avancar mundo #'avaliador)
      (avancar mundo #'avaliador)
      (is (equal "urgente" (intencao-nome (execucao-intencao (heroi-acao heroi)))))
      (is (find "Ação interrompida." (mundo-eventos mundo) :key #'second :test #'equal)))))
(test remover-alvo-cancela-deslocamento
  (let* ((mundo (novo-mundo)) (heroi (mundo-heroi mundo)))
    (qed.nucleo::iniciar-intencao mundo (criar-intencao :nome "andar" :acoes '((:mover 1))))
    (setf (mundo-entidades mundo) (remove 1 (mundo-entidades mundo) :key #'entidade-id))
    (qed.nucleo::executar-acao mundo)
    (is (null (heroi-acao heroi)))
    (is (= 48 (heroi-x heroi)))
    (is (find "O alvo deixou de existir." (mundo-eventos mundo) :key #'second :test #'equal))))
(test teto-solido-bloqueia-salto
  (let* ((mundo (novo-mundo)) (heroi (mundo-heroi mundo)))
    (setf (mundo-plataformas mundo) '((0 180 200 16 1))
          (heroi-y heroi) 225 (heroi-vy heroi) -300)
    (qed.nucleo::aplicar-fisica mundo)
    (is (= 222 (heroi-y heroi)))
    (is (zerop (heroi-vy heroi)))))
(test sequencia-interrompida-entre-golpes
  (let* ((mundo (novo-mundo)) (heroi (mundo-heroi mundo)))
    (setf (heroi-x heroi) 290)
    (qed.nucleo::iniciar-intencao mundo
      (criar-intencao :nome "duplo" :prioridade 1 :acoes '((:atacar 2 ":basic") (:atacar 2 ":basic"))))
    (dotimes (indice 37) (declare (ignorable indice)) (qed.nucleo::executar-acao mundo))
    (let ((vida-alvo (entidade-hp (buscar-entidade mundo 2))))
      (avancar mundo (lambda (foto) (declare (ignore foto))
                      (criar-resultado :intencao (criar-intencao :nome "emergencia" :prioridade 100 :acoes '((:esperar 1))))))
      (is (equal "emergencia" (intencao-nome (execucao-intencao (heroi-acao heroi)))))
      (is (= vida-alvo (entidade-hp (buscar-entidade mundo 2)))))))
(test macros-confiaveis-geram-dados
  (let ((biblioteca (definir-teorema aguardar :class fighter :premises () :conclusion (wait))))
    (is (equal "aguardar" (definicao-nome (first (biblioteca-definicoes biblioteca))))))
  (let ((biblioteca (definir-teorema aguardar :class wizard :goal (prove (can-wait))
                                   :on-success (wait) :on-failure (fizzle :reason))))
    (is (eq :wizard (definicao-classe (first (biblioteca-definicoes biblioteca)))))))

(test definicao-preserva-fonte-e-posicao
  (let* ((texto (format nil "; comentário~%(teorema escolher :classe guerreiro~%  :premissas ((estado ocioso)) :conclusao (esperar))"))
         (definicao (first (biblioteca-definicoes (biblioteca-guerreiro texto)))))
    (is (= 13 (definicao-posicao definicao)))
    (is (search "(teorema escolher" (definicao-texto-original definicao)))
    (is (search ":conclusao (esperar)" (definicao-texto-original definicao)))))
(test documento-conserva-lemas-e-ordem
  (let* ((texto (format nil "(lema criterio () (< 1 2))~%; comentário da próxima forma~%(teorema primeiro :prioridade 1 :premissas ((criterio)) :conclusao (esperar))~%(teorema segundo :prioridade 10 :premissas () :conclusao (esperar))"))
         (biblioteca (biblioteca-guerreiro texto))
         (documento (biblioteca-documento biblioteca)))
    (is (equal '("criterio" "primeiro" "segundo") (mapcar #'definicao-nome documento)))
    (is (eq :lema (definicao-tipo (first documento))))
    (is (equal "(lema criterio () (< 1 2))" (definicao-texto-original (first documento))))
    (is (equal '("segundo" "primeiro") (mapcar #'definicao-nome (biblioteca-definicoes biblioteca))))))
(test morte-preserva-progresso
  (let* ((mundo (novo-mundo)) (heroi (mundo-heroi mundo)))
    (setf (heroi-hp heroi) 0 (heroi-xp heroi) 50 (heroi-madeira heroi) 12)
    (dotimes (i 181) (declare (ignorable i)) (avancar mundo (lambda (foto) (declare (ignore foto)) (criar-resultado))))
    (is (= 100 (heroi-hp heroi))) (is (= 50 (heroi-xp heroi))) (is (= 12 (heroi-madeira heroi)))))
(test salvar-carregar-e-backup
  (let* ((caminho (merge-pathnames (format nil "qed-~A.sexp" (gensym)) (uiop:temporary-directory)))
         (backup (pathname (concatenate 'string (namestring caminho) ".bak"))) (sessao (nova-sessao)))
    (unwind-protect
         (progn
           (dotimes (i 600) (declare (ignorable i)) (avancar-sessao sessao))
           (alternar-personagem sessao)
           (dotimes (i 600) (declare (ignorable i)) (avancar-sessao sessao))
           (salvar-partida sessao caminho)
           (let ((outra (carregar-partida caminho)))
             (is (equal (estado-resumido (mundo-ativo sessao)) (estado-resumido (mundo-ativo outra))))
             (is (equal (biblioteca-texto (biblioteca-ativa sessao)) (biblioteca-texto (biblioteca-ativa outra)))))
           (salvar-partida sessao caminho)
           (with-open-file (fluxo caminho :direction :output :if-exists :supersede) (write-string "#. (error 1)" fluxo))
           (multiple-value-bind (outra aviso) (carregar-partida caminho)
             (is (not (null outra))) (is (stringp aviso))))
      (when (probe-file caminho) (delete-file caminho)) (when (probe-file backup) (delete-file backup)))))
(test rascunho-nao-aplicado-persiste-separado
  (let* ((caminho (merge-pathnames (format nil "qed-rascunho-~A.sexp" (gensym))
                                   (uiop:temporary-directory)))
         (sessao (nova-sessao))
         (biblioteca-antes (biblioteca-texto (biblioteca-ativa sessao))))
    (unwind-protect
         (progn
           (setf (aref (sessao-rascunhos sessao) 0) "(teorema ainda-invalido")
           (salvar-partida sessao caminho)
           (let ((outra (carregar-partida caminho)))
             (is (equal "(teorema ainda-invalido" (aref (sessao-rascunhos outra) 0)))
             (is (equal biblioteca-antes (biblioteca-texto (biblioteca-ativa outra))))))
      (when (probe-file caminho) (delete-file caminho)))))
(defun executar () (run! 'suite-qed))

(test escolhas-ontologicas-atomicas
  (let* ((mundo (novo-mundo :wizard)) (heroi (mundo-heroi mundo)))
    (is (null (desbloquear-area mundo "conducao")))
    (conceder-xp mundo 100)
    (is (= 3 (pontos-conhecimento heroi)))
    (is (null (desbloquear-area mundo "tempestade")))
    (is (null (desbloquear-area mundo "impacto")))
    (is (= 3 (pontos-conhecimento heroi)))
    (is (desbloquear-area mundo "composicao"))
    (is (= 5 (heroi-slots heroi)))
    (is (null (desbloquear-area mundo "composicao")))
    (is (= 2 (pontos-conhecimento heroi)))
    (is (desbloquear-area mundo "conducao"))
    (is (find "storm-conduction" (axiomas-iniciais mundo) :key #'axioma-nome :test #'equal))
    (is (desbloquear-area mundo "tempestade"))
    (is (= 0 (pontos-conhecimento heroi)))
    (conceder-xp mundo 1000)
    (is (= 0 (pontos-conhecimento heroi)))))

(test impacto-unico-e-recuperacao
  (let* ((mundo (novo-mundo)) (heroi (mundo-heroi mundo)) (alvo (buscar-entidade mundo 2)))
    (setf (heroi-x heroi) 330 (entidade-hp alvo) 10)
    (qed.nucleo::iniciar-intencao mundo (criar-intencao :nome "golpear" :acoes '((:atacar 2 ":basic"))))
    (dotimes (tick 20) (qed.nucleo::executar-acao mundo))
    (is (= -8 (entidade-hp alvo)))
    (is (= -1 (heroi-direcao heroi)))
    (is (= 10 (heroi-xp heroi)))
    (is (not (null (heroi-acao heroi))))
    (dotimes (tick 20) (qed.nucleo::executar-acao mundo))
    (is (= -8 (entidade-hp alvo)))
    (is (= 10 (heroi-xp heroi)))
    (is (null (heroi-acao heroi)))
    (is (not (find "O alvo deixou de existir." (mundo-eventos mundo) :key #'second :test #'equal)))))

(test recuperacao-durante-espera-segura
  (let* ((mundo (novo-mundo)) (heroi (mundo-heroi mundo)))
    (setf (heroi-hp heroi) 20)
    (simular mundo (lambda (foto) (declare (ignore foto))
                    (criar-resultado :intencao (criar-intencao :acoes '((:esperar 5))))) 2)
    (is (> (heroi-hp heroi) 25))
    (is (plusp (heroi-tempo-animacao heroi)))))

(test ontologia-persiste-por-personagem
  (let* ((sessao (nova-sessao))
         (caminho (merge-pathnames (format nil "qed-ontologia-~A.sexp" (gensym)) (uiop:temporary-directory))))
    (unwind-protect
         (progn
           (conceder-xp (mundo-ativo sessao) 60)
           (desbloquear-area (mundo-ativo sessao) "impacto")
           (salvar-partida sessao caminho)
           (let* ((outra (carregar-partida caminho)) (heroi (mundo-heroi (mundo-ativo outra))))
             (is (area-liberada-p heroi "impacto"))
             (is (not (area-liberada-p heroi "estados")))
             (is (= 1 (pontos-conhecimento heroi)))
             (alternar-personagem outra)
             (is (= 0 (pontos-conhecimento (mundo-heroi (mundo-ativo outra)))))))
      (when (probe-file caminho) (delete-file caminho)))))

(test migracao-preserva-conhecimento-antigo
  (dolist (classe '(:fighter :wizard))
    (dolist (xp '(0 30 60 100))
      (let* ((mundo (novo-mundo classe))
             (biblioteca (ler-biblioteca (fonte-exemplo classe) :classe classe)))
        (conceder-xp mundo xp)
        (let* ((dados (qed.logica::serializar-mundo mundo biblioteca (biblioteca-texto biblioteca)))
               (migrado (qed.logica::desserializar-mundo dados classe 1))
               (heroi (mundo-heroi migrado)))
          (is (>= (pontos-conhecimento heroi) 0))
          (is (= (if (>= xp 100) 5 4) (heroi-slots heroi)))
          (when (eq classe :wizard) (is (area-liberada-p heroi "conducao")))
          (when (>= xp 60)
            (is (area-liberada-p heroi (if (eq classe :wizard) "tempestade" "impacto")))))))))

(test progresso-rejeita-ontologia-invalida
  (let* ((mundo (novo-mundo :wizard))
         (biblioteca (biblioteca-mago (fonte-exemplo :wizard)))
         (dados (qed.logica::serializar-mundo mundo biblioteca (biblioteca-texto biblioteca))))
    (setf (getf (getf dados :heroi) :conhecimentos) '("tempestade"))
    (signals erro-dsl (qed.logica::desserializar-mundo dados :wizard))
    (setf (getf (getf dados :heroi) :conhecimentos) '("conducao"))
    (signals erro-dsl (qed.logica::desserializar-mundo dados :wizard))))

(test campanha-tem-sete-telas-e-passagens
  (let* ((mundo (novo-mundo)) (heroi (mundo-heroi mundo)))
    (is (= 3360 (mundo-largura mundo)))
    (is (= 3 (length (mundo-regioes mundo))))
    (is (null (rota-para mundo 1500)))
    (setf (heroi-madeira heroi) 100)
    (is (construir mundo :shelter))
    (is (= 125 (heroi-hp-max heroi)))
    (is (= 70 (heroi-madeira heroi)))
    (setf (getf (heroi-abates heroi) :slime) 8)
    (is (construir mundo :workshop))
    (is (not (null (rota-para mundo 1500))))
    (is (= 20 (heroi-madeira heroi)))
    (is (null (construir mundo :workshop)))))

(test construcoes-sao-atomicas-e-concedem-efeitos
  (let* ((mundo (novo-mundo :wizard)) (heroi (mundo-heroi mundo)))
    (setf (heroi-madeira heroi) 29)
    (is (null (construir mundo :shelter)))
    (is (= 29 (heroi-madeira heroi)))
    (setf (heroi-madeira heroi) 200 (getf (heroi-abates heroi) :slime) 8)
    (construir mundo :shelter) (construir mundo :workshop)
    (setf (quantidade-material heroi :iron-ore) 40
          (quantidade-material heroi :arcane-crystal) 10
          (getf (heroi-abates heroi) :sentinel) 6)
    (is (construir mundo :arsenal))
    (is (= 4 (bonus-dano heroi)))
    (is (construir mundo :observatory))
    (is (= 100 (heroi-mana-max heroi)))
    (is (= 80 (heroi-mana heroi)))
    (is (not (null (rota-para mundo 2500))))))

(test fatos-novos-e-aliases
  (let* ((mundo (novo-mundo)) (heroi (mundo-heroi mundo))
         (sentinela (buscar-entidade mundo 12)))
    (setf (heroi-madeira heroi) 37 (entidade-fase sentinela) :windup)
    (is (equal "inventory" (qed.logica::canonico "inventário")))
    (is (equal "enemy-state" (qed.logica::canonico "estado-inimigo")))
    (is (equal "quest-target" (qed.logica::canonico "alvo-da-missão")))
    (is (equal "consultar" (nome-vencedor (avaliar-texto
      "(theorem consultar :premises ((>= (inventory :wood) 30) (enemy-state 12 :windup)) :conclusion (wait))" mundo))))
    (setf (heroi-madeira heroi) 0)
    (is (= 1 (qed.logica::consultar '("quest-target") mundo)))
    (is (qed.logica::consultar '("resource-type" 12 "enemy") mundo))))

(test mineracao-exige-oficina-e-autoriza-material
  (let* ((mundo (novo-mundo)) (heroi (mundo-heroi mundo))
         (texto "(theorem mine-now :class fighter :premises () :conclusion (interact :mine))"))
    (setf (heroi-x heroi) 1530)
    (is (null (resultado-intencao (avaliar-texto texto mundo))))
    (setf (heroi-construcoes heroi) '(:workshop :shelter)
          (getf (heroi-abates heroi) :slime) 8)
    (let ((intencao (resultado-intencao (avaliar-texto texto mundo))))
      (is (not (null intencao)))
      (is (equal '((:minerar 10)) (intencao-acoes intencao))))
    (is (qed.logica::consultar '("gatherable" 10) mundo))))

(test mineracao-do-mago-preserva-alvo-provado
  (let* ((mundo (novo-mundo :wizard)) (heroi (mundo-heroi mundo))
         (ferro (buscar-entidade mundo 13)) (cristal (buscar-entidade mundo 16))
         (texto "(theorem mine-iron :class wizard
                   :goal (prove (can-gather (nearest resource :iron-ore))
                     :using-axioms (gather-law))
                   :on-success (interact :mine)
                   :on-failure (fizzle :reason))"))
    (setf (heroi-construcoes heroi) '(:workshop :shelter)
          (getf (heroi-abates heroi) :slime) 8
          (entidade-x ferro) 100 (entidade-y ferro) 240
          (entidade-x cristal) 101 (entidade-y cristal) 240
          (heroi-x heroi) 101 (heroi-y heroi) 240)
    ;; O cristal está mais perto no conjunto de minerais, porém a prova nomeia
    ;; explicitamente o ferro. A intenção deve conservar esse vínculo.
    (let ((intencao (resultado-intencao (avaliar-texto texto mundo))))
      (is (not (null intencao)))
      (is (equal '((:minerar 13)) (intencao-acoes intencao))))))

(test sentinela-anuncia-ataca-e-recupera
  (let* ((mundo (novo-mundo)) (heroi (mundo-heroi mundo)) (sentinela (buscar-entidade mundo 12))
         (vazio (lambda (foto) (declare (ignore foto)) (criar-resultado))))
    (setf (heroi-x heroi) 1700)
    (let ((antes (entidade-x sentinela)))
      (avancar mundo vazio)
      (is (< (entidade-x sentinela) antes)))
    (setf (heroi-x heroi) 1860)
    (avancar mundo vazio)
    (is (eq :windup (entidade-fase sentinela)))
    (dotimes (i 48) (declare (ignore i)) (avancar mundo vazio))
    (is (= 86 (heroi-hp heroi)))
    (is (eq :recovery (entidade-fase sentinela)))
    (dotimes (i 72) (declare (ignore i)) (avancar mundo vazio))
    (is (eq :idle (entidade-fase sentinela)))))

(test guardiao-mitigacao-vitoria-e-retorno-regional
  (let* ((mundo (novo-mundo)) (heroi (mundo-heroi mundo)) (guardiao (buscar-entidade mundo 21)))
    (setf (heroi-x heroi) 3200 (entidade-fase guardiao) :windup)
    (qed.nucleo::iniciar-intencao mundo (criar-intencao :nome "teste" :acoes '((:atacar 21 ":basic"))))
    (dotimes (i 20) (declare (ignore i)) (qed.nucleo::executar-acao mundo))
    (is (= 291 (entidade-hp guardiao)))
    (setf (heroi-acao heroi) nil (entidade-fase guardiao) :recovery)
    (qed.nucleo::iniciar-intencao mundo (criar-intencao :nome "teste" :acoes '((:atacar 21 ":basic"))))
    (dotimes (i 20) (declare (ignore i)) (qed.nucleo::executar-acao mundo))
    (is (= 273 (entidade-hp guardiao)))
    (setf (heroi-acao heroi) nil (entidade-hp guardiao) 1)
    (qed.nucleo::iniciar-intencao mundo (criar-intencao :nome "fim" :acoes '((:atacar 21 ":basic"))))
    (dotimes (i 20) (declare (ignore i)) (qed.nucleo::executar-acao mundo))
    (is (= 1 (getf (heroi-abates heroi) :guardian)))
    (qed.nucleo::atualizar-inimigos mundo)
    (is (<= (entidade-hp guardiao) 0))
    (setf (heroi-x heroi) 1800 (heroi-hp heroi) 0)
    (dotimes (i 181) (declare (ignore i))
      (avancar mundo (lambda (foto) (declare (ignore foto)) (criar-resultado))))
    (is (= 1472 (heroi-x heroi)))))

(test persistencia-v3-preserva-campanha
  (let* ((mundo (novo-mundo)) (heroi (mundo-heroi mundo))
         (biblioteca (biblioteca-guerreiro (fonte-exemplo :fighter))))
    (setf (heroi-madeira heroi) 100 (getf (heroi-abates heroi) :slime) 8)
    (construir mundo :shelter) (construir mundo :workshop)
    (setf (quantidade-material heroi :iron-ore) 7 (heroi-x heroi) 1700)
    (qed.nucleo::atualizar-campanha mundo)
    (let* ((dados (qed.logica::serializar-mundo mundo biblioteca (biblioteca-texto biblioteca)))
           (carregado (qed.logica::desserializar-mundo dados :fighter))
           (outro (mundo-heroi carregado)))
      (is (= 7 (quantidade-material outro :iron-ore)))
      (is (construcao-pronta-p outro :workshop))
      (is (member :mina (heroi-regioes-descobertas outro)))
      (is (= 125 (heroi-hp-max outro))))
    (let ((dados (qed.logica::serializar-mundo mundo biblioteca (biblioteca-texto biblioteca))))
      (setf (getf (getf dados :heroi) :construcoes) '(:observatory))
      (signals erro-dsl (qed.logica::desserializar-mundo dados :fighter)))))

(defun biblioteca-guiada (classe tipo)
  (ler-biblioteca
   (if (eq classe :fighter)
       (case tipo
         (:wood "(theorem guided-gather :class fighter :premises () :conclusion (interact :chop))")
         ((:iron-ore :arcane-crystal) "(theorem guided-mine :class fighter :premises () :conclusion (interact :mine))")
         (otherwise "(theorem guided-combat :class fighter :premises () :conclusion (attack :basic))"))
       (case tipo
         (:wood "(theorem guided-gather :class wizard :goal (prove (can-gather (nearest resource :wood)) :using-axioms (gather-law)) :on-success (interact :chop) :on-failure (fizzle :reason))")
         (:iron-ore "(theorem guided-mine :class wizard :goal (prove (can-gather (nearest resource :iron-ore)) :using-axioms (gather-law)) :on-success (interact :mine) :on-failure (fizzle :reason))")
         (:arcane-crystal "(theorem guided-mine :class wizard :goal (prove (can-gather (nearest resource :arcane-crystal)) :using-axioms (gather-law)) :on-success (interact :mine) :on-failure (fizzle :reason))")
         (otherwise "(theorem guided-combat :class wizard :goal (prove (strikes spark enemy) :using-axioms (elemental-affinity spark-law)) :on-success (manifest :spark :target enemy) :on-failure (fizzle :reason))")))
   :classe classe))

(defun executar-evento-guiado (mundo tipo)
  (let* ((heroi (mundo-heroi mundo))
         (alvo (find tipo (mundo-entidades mundo) :key #'entidade-tipo))
         (biblioteca (biblioteca-guiada (heroi-classe heroi) tipo))
         (antes (if (recurso-p alvo) (quantidade-material heroi tipo)
                    (getf (heroi-abates heroi) tipo 0))))
    (qed.nucleo::restaurar-entidade mundo alvo)
    (when (inimigo-p alvo) (setf (entidade-hp alvo) 1))
    (setf (heroi-x heroi) (- (entidade-x alvo) 10) (heroi-y heroi) 240
          (heroi-mana heroi) (heroi-mana-max heroi))
    (loop repeat 180
          until (> (if (recurso-p alvo) (quantidade-material heroi tipo)
                       (getf (heroi-abates heroi) tipo 0)) antes)
          do (avancar mundo (lambda (foto) (avaliar-biblioteca biblioteca foto))))
    (cancelar-acao mundo)
    (> (if (recurso-p alvo) (quantidade-material heroi tipo)
           (getf (heroi-abates heroi) tipo 0)) antes)))

(test campanha-guiada-completa-pelas-duas-classes
  (dolist (classe '(:fighter :wizard))
    (let* ((mundo (novo-mundo classe)) (heroi (mundo-heroi mundo)))
      (is (executar-evento-guiado mundo :wood))
      (setf (heroi-madeira heroi) 30) (is (construir mundo :shelter))
      (is (executar-evento-guiado mundo :slime))
      (setf (getf (heroi-abates heroi) :slime) 8 (heroi-madeira heroi) 50)
      (is (construir mundo :workshop))
      (is (executar-evento-guiado mundo :iron-ore))
      (setf (heroi-madeira heroi) 30 (quantidade-material heroi :iron-ore) 20)
      (is (construir mundo :arsenal))
      (is (executar-evento-guiado mundo :arcane-crystal))
      (is (executar-evento-guiado mundo :sentinel))
      (setf (getf (heroi-abates heroi) :sentinel) 6
            (quantidade-material heroi :iron-ore) 20
            (quantidade-material heroi :arcane-crystal) 10)
      (is (construir mundo :observatory))
      (is (executar-evento-guiado mundo :guardian))
      (is (eq :concluida (etapa-campanha heroi)))
      (is (= 4 (bonus-dano heroi)))
      (is (= 125 (heroi-hp-max heroi)))
      (is (= 100 (heroi-mana-max heroi))))))
