(in-package #:qed.logica)

(define-condition falha-avaliacao (error)
  ((motivo :initarg :motivo :reader motivo-falha)))
(defvar *operacoes* 8192)
(defvar *resolucoes* 256)
(defvar *cache-lemas* nil)
(defvar *custo-consulta* 0)
(defun gastar-operacao ()
  (incf *custo-consulta*)
  (when (minusp (decf *operacoes*)) (error 'falha-avaliacao :motivo :orcamento-esgotado)))
(defun tipo-entidade (nome)
  (cond ((member nome '("resource" ":wood") :test #'equal) :wood)
        ((member nome '("enemy" ":slime") :test #'equal) :slime)))
(defun valor (expressao mundo lemas vinculos)
  (cond ((consp expressao) (consultar expressao mundo lemas vinculos))
        ((assoc expressao vinculos :test #'equal) (cdr (assoc expressao vinculos :test #'equal)))
        ((equal expressao "enemy") (let ((alvo (mais-proxima mundo :slime))) (and alvo (entidade-id alvo))))
        ((equal expressao "nil") nil) ((equal expressao "t") t)
        (t expressao)))
(defun objeto-alvo (termo mundo lemas vinculos)
  (buscar-entidade mundo (valor termo mundo lemas vinculos)))
(defun numero-seguro (numero)
  (unless (and (realp numero) (<= (abs numero) 1000000000))
    (error 'falha-avaliacao :motivo :tipo-invalido))
  numero)
(defun consultar (expressao mundo &optional lemas vinculos)
  "Interpreta exclusivamente primitivas puras; não chama funções nomeadas pelo jogador."
  (gastar-operacao)
  (unless (consp expressao) (return-from consultar (valor expressao mundo lemas vinculos)))
  (let* ((operador (first expressao)) (argumentos (rest expressao)) (heroi (mundo-heroi mundo))
         (lema (assoc operador lemas :test #'equal)))
    (labels ((v (termo) (valor termo mundo lemas vinculos))
             (alvo (termo) (objeto-alvo termo mundo lemas vinculos)))
      (cond
        (lema
         (let* ((valores (mapcar #'v argumentos)) (chave (cons operador valores)))
           (multiple-value-bind (resultado presente) (and *cache-lemas* (gethash chave *cache-lemas*))
             (if presente resultado
                 (let ((resultado (consultar (third lema) mundo lemas
                                             (append (pairlis (second lema) valores) vinculos))))
                   (when *cache-lemas* (setf (gethash chave *cache-lemas*) resultado)) resultado)))))
        ((equal operador "and") (every (lambda (p) (consultar p mundo lemas vinculos)) argumentos))
        ((equal operador "or") (some (lambda (p) (consultar p mundo lemas vinculos)) argumentos))
        ((equal operador "not") (not (consultar (first argumentos) mundo lemas vinculos)))
        ((equal operador "exists")
         (let ((vinculo (first argumentos)))
           (some (lambda (entidade)
                   (and (eq (entidade-tipo entidade) (tipo-entidade (second vinculo)))
                        (plusp (entidade-hp entidade))
                        (consultar (second argumentos) mundo lemas
                                   (acons (first vinculo) (entidade-id entidade) vinculos))))
                 (mundo-entidades mundo))))
        ((member operador '("+" "-" "*" "/" "<" ">" "<=" ">=" "=") :test #'equal)
         (let ((numeros (mapcar (lambda (p) (numero-seguro (v p))) argumentos)))
           (cond ((equal operador "<") (< (first numeros) (second numeros)))
                 ((equal operador ">") (> (first numeros) (second numeros)))
                 ((equal operador "<=") (<= (first numeros) (second numeros)))
                 ((equal operador ">=") (>= (first numeros) (second numeros)))
                 ((equal operador "=") (= (first numeros) (second numeros)))
                 (t (numero-seguro
                     (cond ((equal operador "+") (reduce #'+ numeros))
                           ((equal operador "-") (- (first numeros) (second numeros)))
                           ((equal operador "*") (reduce #'* numeros))
                           ((zerop (second numeros)) (error 'falha-avaliacao :motivo :divisao-por-zero))
                           (t (/ (first numeros) (second numeros)))))))))
        ((equal operador "state") (equal (v (first argumentos))
                                           (concatenate 'string ":" (string-downcase (symbol-name (heroi-estado heroi))))))
        ((equal operador "stat")
         (let ((nome (v (first argumentos))))
           (cond ((equal nome ":hp") (heroi-hp heroi)) ((equal nome ":max-hp") (heroi-hp-max heroi))
                 ((equal nome ":mana") (heroi-mana heroi)) ((equal nome ":max-mana") (heroi-mana-max heroi))
                 ((equal nome ":xp") (heroi-xp heroi))
                 (t (error 'falha-avaliacao :motivo :atributo-desconhecido)))))
        ((equal operador "nearest")
         (let ((entidade (mais-proxima mundo (tipo-entidade (or (second argumentos) (first argumentos))))))
           (and entidade (entidade-id entidade))))
        ((equal operador "nearest-threat") (let ((e (mais-proxima mundo :slime))) (and e (entidade-id e))))
        ((equal operador "position")
         (if (equal (first argumentos) "self") (list (heroi-x heroi) (heroi-y heroi))
             (let ((e (alvo (first argumentos)))) (and e (list (entidade-x e) (entidade-y e))))))
        ((equal operador "resource-type")
         (let ((e (alvo (first argumentos))))
           (and e (eq (entidade-tipo e) (tipo-entidade (v (second argumentos)))))))
        ((equal operador "within-range")
         (let ((e (alvo (first argumentos))))
           ;; Distâncias da DSL são tiles de 16 pixels.
           (and e (plusp (entidade-hp e))
                (<= (distancia heroi e) (* 16 (numero-seguro (v (second argumentos))))))))
        ((equal operador "enemy-in-range")
         (let ((e (mais-proxima mundo :slime)))
           (and e (<= (distancia heroi e) (if (equal (first argumentos) ":melee") 30 160)))))
        ((equal operador "resource-nearby") (not (null (mais-proxima mundo :wood))))
        ((equal operador "enemy-nearby") (let ((e (mais-proxima mundo :slime))) (and e (< (distancia heroi e) 200))))
        ((equal operador "line-of-sight") (linha-livre-p mundo (alvo (first argumentos))))
        ((equal operador "mana-available") (>= (heroi-mana heroi) (numero-seguro (v (first argumentos)))))
        ((equal operador "reachable") (let ((destino (v (first argumentos))))
                                          (alcancavel-p mundo (or (buscar-entidade mundo destino) destino))))
        ((member operador '("wet" "status") :test #'equal)
         (when (and (equal operador "status") (not (member "status" (heroi-desbloqueios heroi) :test #'equal)))
           (error 'falha-avaliacao :motivo :vocabulario-bloqueado))
         (let ((e (alvo (first argumentos))))
           (and e (or (equal operador "wet") (equal (second argumentos) ":wet")) (entidade-molhada e))))
        ((equal operador "focus-equipped") (and (eq (heroi-classe heroi) :wizard) (equal (first argumentos) "self")))
        (t (error 'falha-avaliacao :motivo :operador-desconhecido))))))

(defun substituir (termo vinculos)
  (cond ((and (variavel-p termo) (assoc termo vinculos :test #'equal))
         (substituir (cdr (assoc termo vinculos :test #'equal)) vinculos))
        ((consp termo) (cons (substituir (car termo) vinculos) (substituir (cdr termo) vinculos)))
        (t termo)))
(defun ocorre-p (variavel termo vinculos)
  (let ((termo (substituir termo vinculos)))
    (or (equal variavel termo) (and (consp termo) (or (ocorre-p variavel (car termo) vinculos)
                                                    (ocorre-p variavel (cdr termo) vinculos))))))
(defun unificar (esquerda direita &optional vinculos)
  "Retorna ambiente e sucesso separadamente: NIL também é um ambiente válido."
  (let ((esquerda (substituir esquerda vinculos)) (direita (substituir direita vinculos)))
    (cond ((equal esquerda direita) (values vinculos t))
          ((variavel-p esquerda) (if (ocorre-p esquerda direita vinculos) (values nil nil)
                                    (values (acons esquerda direita vinculos) t)))
          ((variavel-p direita) (unificar direita esquerda vinculos))
          ((and (consp esquerda) (consp direita))
           (multiple-value-bind (novos sucesso) (unificar (car esquerda) (car direita) vinculos)
             (if sucesso (unificar (cdr esquerda) (cdr direita) novos) (values nil nil))))
          (t (values nil nil)))))

(defstruct (axioma (:constructor criar-axioma)) nome cabeca corpo)
(defun axiomas-iniciais (mundo)
  (let ((axiomas
          (list
           (criar-axioma :nome "travel-law" :cabeca '("can-move" "?alvo") :corpo '(("reachable" "?alvo")))
           (criar-axioma :nome "gather-law" :cabeca '("can-gather" "?alvo")
                         :corpo '(("resource-type" "?alvo" ":wood") ("within-range" "?alvo" 1.875)))
           (criar-axioma :nome "flee-law" :cabeca '("can-flee" "?alvo")
                         :corpo '(("resource-type" "?alvo" ":slime") ("within-range" "?alvo" 12.5)))
           (criar-axioma :nome "wait-law" :cabeca '("can-wait") :corpo nil)
           (criar-axioma :nome "elemental-affinity" :cabeca '("affinity" "storm" "self")
                         :corpo '(("focus-equipped" "self")))
           (criar-axioma :nome "spark-law" :cabeca '("strikes" "spark" "?alvo")
                         :corpo '(("affinity" "storm" "self") ("resource-type" "?alvo" ":slime") ("within-range" "?alvo" 10)
                                  ("line-of-sight" "?alvo") ("mana-available" 8))))))
    (when (member "storm-conduction" (heroi-desbloqueios (mundo-heroi mundo)) :test #'equal)
      (setf axiomas (append axiomas (list (criar-axioma :nome "storm-conduction"
                    :cabeca '("conductive" "?alvo") :corpo '(("wet" "?alvo")))))))
    (when (member "lightning-law" (heroi-desbloqueios (mundo-heroi mundo)) :test #'equal)
      (setf axiomas (append axiomas
                    (list (criar-axioma :nome "lightning-law" :cabeca '("strikes" "lightning" "?alvo")
                                       :corpo '(("affinity" "storm" "self") ("conductive" "?alvo")
                                                ("resource-type" "?alvo" ":slime") ("within-range" "?alvo" 10) ("line-of-sight" "?alvo")
                                                ("mana-available" 8)))))))
    axiomas))
(defun renomear-axioma (axioma contador)
  (let ((nomes nil))
    (labels ((renomear (termo)
               (cond ((variavel-p termo)
                      (or (cdr (assoc termo nomes :test #'equal))
                          (let ((novo (format nil "?~A/~D" termo contador)))
                            (push (cons termo novo) nomes) novo)))
                     ((consp termo) (mapcar #'renomear termo)) (t termo))))
      (values (renomear (axioma-cabeca axioma)) (renomear (axioma-corpo axioma))))))

(defun primeira-variavel (termo)
  (cond ((variavel-p termo) termo)
        ((consp termo) (or (primeira-variavel (car termo)) (primeira-variavel (cdr termo))))))

(defun provar (objetivo mundo axiomas &key lemas dados (profundidade-maxima 16))
  "Resolução SLD sobre uma agenda de (profundidade . objetivo), sem cortes implícitos."
  (let ((contador 0) (corte nil) (faltou-mana nil) (dado-falso nil)
        (dominio (cons "self" (loop for entidade in (mundo-entidades mundo)
                                    when (plusp (entidade-hp entidade)) collect (entidade-id entidade)))))
    (labels
        ((gastar-resolucao ()
           (when (minusp (decf *resolucoes*)) (error 'falha-avaliacao :motivo :orcamento-esgotado))
           (gastar-operacao))
         (resolver-fato (atual restantes ambiente profundidade limite)
           (let* ((instancia (substituir atual ambiente)) (livre (primeira-variavel instancia)))
             (when livre
               (dolist (candidato dominio)
                 (gastar-resolucao)
                 (let ((*cache-lemas* (qed.nucleo::copiar-tabela *cache-lemas*)))
                   (multiple-value-bind (vinculos prova sucesso)
                       (resolver-fato atual restantes (acons livre candidato ambiente) profundidade limite)
                     (when sucesso (return-from resolver-fato (values vinculos prova t))))))
               (return-from resolver-fato (values nil nil nil)))
             (let ((antes *custo-consulta*))
               (unless (consultar instancia mundo lemas)
                 (when (member atual dados :test #'equal) (setf dado-falso t))
                 (when (equal (first instancia) "mana-available") (setf faltou-mana t))
                 (return-from resolver-fato (values nil nil nil)))
               (let ((custo (- *custo-consulta* antes)))
                 (multiple-value-bind (vinculos rastro sucesso) (buscar restantes ambiente limite)
                   (values vinculos (cons (list :objetivo instancia :axioma :fato
                                               :profundidade profundidade :custo custo) rastro) sucesso))))))
         (buscar (agenda ambiente limite)
           (when (null agenda) (return-from buscar (values ambiente nil t)))
           (let* ((profundidade (caar agenda)) (atual (substituir (cdar agenda) ambiente))
                  (operador (first atual)))
             (when (> profundidade limite) (setf corte t) (return-from buscar (values nil nil nil)))
             (gastar-resolucao)
             (when (or (assoc operador lemas :test #'equal)
                       (and (assoc operador *assinaturas* :test #'equal)
                            (not (member operador *operadores-objetivo* :test #'equal))))
               (return-from buscar (resolver-fato atual (rest agenda) ambiente profundidade limite)))
             (dolist (axioma axiomas (values nil nil nil))
               (gastar-resolucao)
               (let ((*cache-lemas* (qed.nucleo::copiar-tabela *cache-lemas*)))
                 (multiple-value-bind (cabeca corpo) (renomear-axioma axioma (incf contador))
                   (multiple-value-bind (novos unificou) (unificar atual cabeca ambiente)
                     (when unificou
                       (let ((continuacao (append (mapcar (lambda (forma) (cons (1+ profundidade) forma)) corpo)
                                                   (rest agenda))))
                         (multiple-value-bind (finais rastro terminou) (buscar continuacao novos limite)
                           (when terminou
                             (return-from buscar
                               (values finais (cons (list :objetivo (substituir atual finais)
                                                          :axioma (axioma-nome axioma)
                                                          :profundidade profundidade :custo 1) rastro) t)))))))))))))
      (handler-case
          (loop for limite from 0 to profundidade-maxima do
            (setf corte nil)
            (let ((*cache-lemas* (make-hash-table :test 'equal)))
              (multiple-value-bind (ambiente rastro sucesso)
                  (buscar (mapcar (lambda (forma) (cons 0 forma)) (append dados (list objetivo))) nil limite)
                (when sucesso (return-from provar (values ambiente rastro t :provado)))))
            (unless corte
              (return-from provar (values nil nil nil (cond (dado-falso :dado-falso)
                                                           (faltou-mana :mana-insuficiente) (t :nao-provado)))))
            finally (return (values nil nil nil :profundidade-esgotada)))
        (falha-avaliacao (erro) (values nil nil nil (motivo-falha erro)))))))

(defun preparar-objetivo (objetivo mundo lemas)
  (cons (first objetivo) (mapcar (lambda (p) (valor p mundo lemas nil)) (rest objetivo))))
(defun construir-acoes (expressao mundo lemas)
  (let* ((operador (first expressao)) (argumentos (rest expressao)))
    (cond
      ((equal operador "do") (mapcan (lambda (acao) (construir-acoes acao mundo lemas)) argumentos))
      ((equal operador "move-to") (list (list :mover (valor (first argumentos) mundo lemas nil))))
      ((equal operador "flee") (list (list :fugir (valor (first argumentos) mundo lemas nil))))
      ((equal operador "wait") (list (list :esperar (if argumentos (max 0.1 (min 60 (numero-seguro (valor (first argumentos) mundo lemas nil)))) 0.5))))
      ((equal operador "interact") (let ((e (mais-proxima mundo :wood))) (and e (list (list :coletar (entidade-id e))))))
      ((equal operador "attack")
       (when (and (equal (first argumentos) ":heavy-strike")
                  (not (member ":heavy-strike" (heroi-desbloqueios (mundo-heroi mundo)) :test #'equal)))
         (error 'falha-avaliacao :motivo :vocabulario-bloqueado))
       (let ((e (mais-proxima mundo :slime))) (and e (list (list :atacar (entidade-id e) (first argumentos))))))
      ((equal operador "manifest")
       (list (list :magia (valor (third argumentos) mundo lemas nil)
                   (if (equal (first argumentos) ":spark") "spark" "lightning"))))
      (t nil))))
(defun efeito-autorizado-p (objetivo acoes)
  (and (= (length acoes) 1)
       (let ((acao (first acoes)))
         (cond ((equal (first objetivo) "can-move") (equal acao (list :mover (second objetivo))))
               ((equal (first objetivo) "can-gather") (equal acao (list :coletar (second objetivo))))
               ((equal (first objetivo) "can-flee") (equal acao (list :fugir (second objetivo))))
               ((equal (first objetivo) "can-wait") (eq (first acao) :esperar))
               ((equal (first objetivo) "strikes")
                (equal acao (list :magia (third objetivo) (second objetivo))))))))

(defun avaliar-biblioteca (biblioteca mundo)
  (let ((*operacoes* 8192) (*resolucoes* 256) (*cache-lemas* (make-hash-table :test 'equal))
        (*custo-consulta* 0) (detalhes nil) (falhas nil) (lemas (biblioteca-lemas biblioteca)))
    (dolist (definicao (biblioteca-definicoes biblioteca))
      (let* ((campos (cddr (definicao-arvore definicao))) (nome (definicao-nome definicao))
             (motivo :nenhuma-correspondencia) (acoes nil) (rastro nil) (passos 0) (mana 0) (duracao 0)
             (magico nil) (premissa-falsa nil))
        (handler-case
            (cond
              ((eq (definicao-classe definicao) :fighter)
               (let ((falsa (find-if-not (lambda (p) (consultar p mundo lemas)) (campo campos ":premises"))))
                 (if falsa (setf motivo :premissa-falsa premissa-falsa falsa)
                     (setf acoes (construir-acoes (campo campos ":conclusion") mundo lemas)))))
              ((> (gethash nome (mundo-falhas mundo) 0) (mundo-tick mundo)) (setf motivo :recarga))
              (t
               (let* ((forma (campo campos ":goal")) (objetivo (preparar-objetivo (second forma) mundo lemas))
                      (dados (campo (cddr forma) ":given"))
                      (permitidos (campo (cddr forma) ":using-axioms"))
                      (axiomas (axiomas-iniciais mundo)))
                 (setf magico (equal (first objetivo) "strikes"))
                 (when (and permitidos (some (lambda (a) (not (find a axiomas :key #'axioma-nome :test #'equal))) permitidos))
                   (error 'falha-avaliacao :motivo :vocabulario-bloqueado))
                 (when (member ":using-axioms" (cddr forma) :test #'equal)
                   (setf axiomas (remove-if-not (lambda (a) (member (axioma-nome a) permitidos :test #'equal)) axiomas)))
                 (progn
                     (multiple-value-bind (vinculos prova sucesso razao) (provar objetivo mundo axiomas :lemas lemas :dados dados)
                       (setf motivo razao rastro prova)
                       (when sucesso
                         (setf passos (reduce #'+ prova :key (lambda (no) (getf no :custo)) :initial-value 0)
                               mana (if magico (+ 8 (* 2 passos)) 0)
                               duracao (if magico (+ 0.2 (* 0.05 passos)) 0)
                               acoes (construir-acoes (substituir (campo campos ":on-success") vinculos) mundo lemas))
                         (unless (efeito-autorizado-p (substituir objetivo vinculos) acoes)
                           (setf acoes nil motivo :efeito-incompativel))
                         (when (< (heroi-mana (mundo-heroi mundo)) mana)
                           (setf acoes nil motivo :mana-insuficiente))))))))
          (falha-avaliacao (erro) (setf motivo (motivo-falha erro) acoes nil))
          (arithmetic-error () (setf motivo :tipo-invalido acoes nil))
          (type-error () (setf motivo :tipo-invalido acoes nil)))
        (when (and magico (null acoes) (not (eq motivo :recarga)))
          (push (list nome motivo (definicao-idioma definicao)) falhas))
        (when acoes (setf motivo :justificado))
        (push (list nome motivo :premissa premissa-falsa :passos passos :prova rastro
                    :mana mana :duracao duracao :idioma (definicao-idioma definicao)) detalhes)
        (when acoes
          (return-from avaliar-biblioteca
            (criar-resultado :motivo :justificado :detalhes (nreverse detalhes) :falhas falhas :passos passos :prova rastro
                             :intencao (criar-intencao :nome nome :prioridade (definicao-prioridade definicao)
                                                       :acoes acoes :mana mana :duracao duracao :passos passos :prova rastro
                                                       :idioma (definicao-idioma definicao)))))))
    (criar-resultado :motivo :nenhuma-correspondencia :detalhes (nreverse detalhes) :falhas falhas)))

(defun traduzir-motivo (motivo &optional (idioma :pt))
  (let ((entrada (assoc motivo
    '((:justificado "Ação justificada" "Action justified")
      (:nenhuma-correspondencia "Nenhum teorema aplicável" "No matching theorem")
      (:nao-provado "Objetivo não provado" "Goal not proven")
      (:provado "Prova encontrada" "Proof found") (:premissa-falsa "Premissa falsa" "False premise")
      (:dado-falso "Dado não confirmado pelo mundo" "Given fact not confirmed")
      (:mana-insuficiente "Mana insuficiente" "Insufficient mana")
      (:recarga "Aguardando nova tentativa" "Waiting to retry")
      (:efeito-incompativel "Efeito não autorizado pela prova" "Effect not authorized by proof")
      (:vocabulario-bloqueado "Vocabulário ainda bloqueado" "Vocabulary still locked")
      (:orcamento-esgotado "Orçamento de operações esgotado" "Operation budget exhausted")
      (:profundidade-esgotada "Limite de profundidade atingido" "Depth limit reached")
      (:tipo-invalido "Tipo de argumento inválido" "Invalid argument type")
      (:divisao-por-zero "Divisão por zero" "Division by zero")))))
    (if entrada (if (eq idioma :en) (third entrada) (second entrada)) (format nil "~A" motivo))))

(defun traduzir-evento (evento idioma)
  (let* ((dados (cddr evento)) (motivo (getf dados :motivo))
         (idioma (if (eq idioma :auto) (getf dados :idioma :pt) idioma))
         (mensagem (second evento)))
    (cond (motivo (format nil "Fizzle: ~A — ~A" (getf dados :nome) (traduzir-motivo motivo idioma)))
          ((eq idioma :en)
           (or (cdr (assoc mensagem
                          '(("Ação interrompida." . "Action interrupted.")
                            ("O alvo deixou de existir." . "The target no longer exists.")
                            ("Não há caminho até o destino." . "No path to the destination.")
                            ("O alvo saiu do alcance ou da linha de visão." . "Target out of range or line of sight.")
                            ("Mana insuficiente ao concluir a conjuração." . "Insufficient mana at the end of casting.")
                            ("Madeira coletada: +2 XP." . "Wood gathered: +2 XP.")
                            ("Slime derrotado: +10 XP." . "Slime defeated: +10 XP.")
                            ("Autômato derrotado." . "Automaton defeated.")
                            ("Personagem alternado." . "Character switched.")
                            ("Biblioteca atualizada." . "Library updated.")) :test #'equal)) mensagem))
          (t mensagem))))
