(in-package #:qed.logica)

(define-condition erro-dsl (error)
  ((mensagem :initarg :mensagem :reader mensagem-erro)
   (posicao :initarg :posicao :initform 0 :reader posicao-erro))
  (:report (lambda (erro fluxo) (format fluxo "~A (posição ~D)" (mensagem-erro erro) (posicao-erro erro)))))
(defun rejeitar (mensagem &optional (posicao 0))
  (error 'erro-dsl :mensagem mensagem :posicao posicao))

(defun conferir-limites (texto &key (limite 65536))
  "Varredura de limites e sintaxe perigosa; a estrutura continua sendo lida por READ."
  (when (> (length texto) limite) (rejeitar "Texto excede o limite permitido."))
  (let ((profundidade 0) (nos 0) (comentario nil) (cadeia nil) (escape nil)
        (tamanho-token 0) (inicio-token 0))
    (loop for caractere across texto for posicao from 0 do
      (cond
        (comentario (when (char= caractere #\Newline) (setf comentario nil)))
        (cadeia (cond (escape (setf escape nil))
                      ((char= caractere #\\) (setf escape t))
                      ((char= caractere #\") (setf cadeia nil))))
        ((char= caractere #\;) (setf comentario t tamanho-token 0))
        ((char= caractere #\") (setf cadeia t tamanho-token 0) (incf nos))
        ((find caractere '(#\Space #\Tab #\Newline #\Return)) (setf tamanho-token 0))
        ((char= caractere #\() (incf profundidade) (incf nos) (setf tamanho-token 0)
         (when (> profundidade 48) (rejeitar "Aninhamento excede 48 níveis." posicao)))
        ((char= caractere #\)) (decf profundidade) (setf tamanho-token 0)
         (when (minusp profundidade) (rejeitar "Parêntese de fechamento excedente." posicao)))
        (t
         (when (zerop tamanho-token) (setf inicio-token posicao) (incf nos))
         (incf tamanho-token)
         (when (> tamanho-token 80) (rejeitar "Token excede 80 caracteres." posicao))
         (when (or (find caractere '(#\# #\' #\` #\, #\| #\\))
                   (and (char= caractere #\:) (/= inicio-token posicao)))
           (rejeitar "Sintaxe de execução, dispatch ou package não permitida." posicao))))
      (when (> nos 8192) (rejeitar "Quantidade de nós excede 8192." posicao)))
    (when cadeia (rejeitar "Cadeia de texto não terminada."))
    (unless (zerop profundidade) (rejeitar "Parênteses incompletos."))))

(defun ler-chave-isolada (fluxo caractere)
  (declare (ignore caractere))
  ;; Evita internar nomes fornecidos pelo jogador no package global KEYWORD.
  (let ((nome (with-output-to-string (saida)
                (loop for c = (peek-char nil fluxo nil nil)
                      while (and c (not (find c '(#\Space #\Tab #\Newline #\Return #\( #\) #\;))))
                      do (write-char (read-char fluxo) saida)))))
    (when (zerop (length nome)) (rejeitar "Palavra-chave vazia."))
    (make-symbol (concatenate 'string ":" (string-upcase nome)))))

(defun ler-dados-seguros (texto &key (limite 65536))
  "Lê dados limitados, sem avaliação nem símbolos persistentes. Retorna formas e posições."
  (conferir-limites texto :limite limite)
  (let* ((pacote (make-package (symbol-name (gensym "QED-LEITURA-")) :use nil))
         (*package* pacote) (*read-eval* nil) (*readtable* (copy-readtable nil))
         (*read-default-float-format* 'double-float))
    (set-macro-character #\: #'ler-chave-isolada nil *readtable*)
    (unwind-protect
         (handler-case
             (with-input-from-string (fluxo texto)
               (labels ((inicio-da-proxima-forma ()
                          (loop for caractere = (peek-char nil fluxo nil nil) do
                            (cond ((null caractere) (return (file-position fluxo)))
                                  ((find caractere '(#\Space #\Tab #\Newline #\Return))
                                   (read-char fluxo))
                                  ((char= caractere #\;)
                                   (read-line fluxo nil nil))
                                  (t (return (file-position fluxo)))))))
                 (loop with fim = (gensym) with formas = nil with posicoes = nil with finais = nil
                       for posicao = (inicio-da-proxima-forma)
                       for forma = (read fluxo nil fim)
                       until (eq forma fim)
                       do (labels ((verificar (objeto)
                                     (cond ((consp objeto)
                                            (unless (listp (cdr objeto)) (rejeitar "Lista imprópria proibida." posicao))
                                            (verificar (car objeto)) (verificar (cdr objeto)))
                                           ((numberp objeto)
                                            (unless (and (realp objeto) (<= (abs objeto) 1000000000))
                                              (rejeitar "Número fora dos limites." posicao)))
                                           ((or (null objeto) (symbolp objeto) (stringp objeto)) nil)
                                           (t (rejeitar "Tipo de dado não permitido." posicao)))))
                            (verificar forma))
                          (push forma formas) (push posicao posicoes) (push (file-position fluxo) finais)
                       finally (return (values (nreverse formas) (nreverse posicoes) (nreverse finais))))))
           (erro-dsl (erro) (error erro))
           (error (erro) (rejeitar (format nil "Erro de leitura: ~A" erro))))
      (delete-package pacote))))

(defparameter *vocabulario*
  (let ((*read-eval* nil))
    (with-open-file (fluxo (asdf:system-relative-pathname "qed/logic" "dados/vocabulario.sexp")
                          :external-format :utf-8)
      (read fluxo))))
(defparameter *aliases* (make-hash-table :test 'equal))
(loop for entrada in *vocabulario* do
  (dolist (nome entrada)
    (let ((anterior (gethash nome *aliases*)))
      (when (and anterior (not (equal anterior (first entrada))))
        (error "Alias com dois significados na tabela: ~A" nome)))
    (setf (gethash nome *aliases*) (first entrada))))
(defun nome-token (objeto)
  (if (symbolp objeto) (string-downcase (symbol-name objeto)) objeto))
(defun canonico (objeto)
  (let ((nome (nome-token objeto)))
    (if (stringp nome) (gethash nome *aliases* nome) nome)))
(defun arvore-textual (objeto)
  (cond ((null objeto) nil) ((consp objeto) (mapcar #'arvore-textual objeto))
        ((symbolp objeto) (nome-token objeto)) (t objeto)))
