(in-package #:qed.logica)

(defstruct (definicao (:constructor criar-definicao))
  nome classe (tipo :teorema) (prioridade 0) arvore texto-original (idioma :pt) (posicao 0))
(defstruct (biblioteca (:constructor criar-biblioteca)) definicoes lemas texto documento)
(eval-when (:compile-toplevel :load-toplevel :execute)
  (defun escrever-forma-confiavel (forma)
    (with-output-to-string (fluxo)
      (labels ((escrever (objeto)
                 (cond ((listp objeto)
                        (write-char #\( fluxo)
                        (loop for parte in objeto for indice from 0 do
                          (when (plusp indice) (write-char #\Space fluxo)) (escrever parte))
                        (write-char #\) fluxo))
                       ((symbolp objeto)
                        (when (keywordp objeto) (write-char #\: fluxo))
                        (write-string (string-downcase (symbol-name objeto)) fluxo))
                       (t (princ objeto fluxo)))))
        (escrever forma)))))
(defmacro definir-teorema (nome &rest campos)
  "Atalho para definições escritas no código confiável, sem avaliação da DSL."
  (let ((classe (loop for (chave valor) on campos by #'cddr
                     when (member (string-downcase (symbol-name chave)) '("class" "classe") :test #'equal)
                       return (string-downcase (symbol-name valor)))))
    `(ler-biblioteca ,(escrever-forma-confiavel `(theorem ,nome ,@campos))
                     :classe ,(if (member classe '("wizard" "mago") :test #'equal) :wizard :fighter))))
(defmacro definir-lema (nome parametros corpo)
  `(ler-biblioteca ,(escrever-forma-confiavel `(lemma ,nome ,parametros ,corpo))))

(defun campo (lista chave &optional padrao)
  (loop for (nome valor) on lista by #'cddr when (equal nome chave) do (return-from campo valor))
  padrao)
(defun validar-campos (lista permitidos)
  (unless (evenp (length lista)) (rejeitar "Campo sem valor."))
  (let ((vistos nil))
    (loop for (chave valor) on lista by #'cddr do
      (unless (member chave permitidos :test #'equal) (rejeitar (format nil "Campo desconhecido: ~A" chave)))
      (when (member chave vistos :test #'equal) (rejeitar (format nil "Campo repetido: ~A" chave)))
      (push chave vistos))))
(defun variavel-p (termo)
  (and (stringp termo) (> (length termo) 1) (char= (char termo 0) #\?)))

(defun normalizar-expressao (expressao nomes &optional vinculadas)
  (cond
    ((null expressao) nil)
    ((consp expressao)
     (let ((operador (if (member (first expressao) nomes :test #'equal)
                        (first expressao) (canonico (first expressao)))))
       (if (equal operador "exists")
           (let ((vinculo (second expressao)))
             (unless (and (listp vinculo) (= (length vinculo) 2)) (rejeitar "Vínculo de exists inválido."))
             (list operador (list (first vinculo) (canonico (second vinculo)))
                   (normalizar-expressao (third expressao) nomes (cons (first vinculo) vinculadas))))
           (cons operador (mapcar (lambda (parte) (normalizar-expressao parte nomes vinculadas)) (rest expressao))))))
    ((or (member expressao vinculadas :test #'equal) (variavel-p expressao)) expressao)
    (t (canonico expressao))))

(defparameter *assinaturas*
  '(("state" 1 1) ("stat" 1 1) ("position" 1 1) ("resource-type" 2 2)
    ("within-range" 2 2) ("enemy-in-range" 1 1) ("resource-nearby" 0 1) ("enemy-nearby" 0 0)
    ("line-of-sight" 1 1) ("mana-available" 1 1) ("reachable" 1 1) ("status" 2 2)
    ("nearest" 1 2) ("nearest-threat" 0 0) ("and" 1 16) ("or" 1 16) ("not" 1 1)
    ("<" 2 2) (">" 2 2) ("<=" 2 2) (">=" 2 2) ("=" 2 2)
    ("+" 2 8) ("-" 2 2) ("*" 2 8) ("/" 2 2) ("exists" 2 2)
    ("move-to" 1 1) ("attack" 1 1) ("interact" 1 1) ("flee" 1 1) ("wait" 0 1)
    ("do" 1 8) ("manifest" 3 3) ("fizzle" 1 1)
    ("can-move" 1 1) ("can-gather" 1 1) ("can-flee" 1 1) ("can-wait" 0 0)
    ("strikes" 2 2) ("affinity" 2 2) ("conductive" 1 1) ("wet" 1 1) ("focus-equipped" 1 1)))
(defparameter *operadores-acao* '("move-to" "attack" "interact" "flee" "wait" "do" "manifest" "fizzle"))
(defparameter *operadores-objetivo* '("can-move" "can-gather" "can-flee" "can-wait" "strikes" "affinity" "conductive"))

(defun validar-expressao (expressao lemas &optional (contexto :condicao) vinculadas)
  (unless (and (consp expressao) (stringp (first expressao))) (rejeitar "Esperada uma expressão Lisp."))
  (let* ((operador (first expressao)) (argumentos (rest expressao))
         (lema (assoc operador lemas :test #'equal))
         (assinatura (or (assoc operador *assinaturas* :test #'equal)
                        (when lema (list operador (length (second lema)) (length (second lema)))))))
    (unless assinatura (rejeitar (format nil "Operador desconhecido: ~A" operador)))
    (unless (<= (second assinatura) (length argumentos) (third assinatura))
      (rejeitar (format nil "Quantidade de argumentos inválida em ~A." operador)))
    (when (and (member operador *operadores-acao* :test #'equal) (not (eq contexto :acao)))
      (rejeitar "Ações não podem aparecer em condições ou provas."))
    (when (and (eq contexto :acao) (not (member operador *operadores-acao* :test #'equal)))
      (rejeitar "Conclusão precisa ser uma ação."))
    (when (and (member operador *operadores-objetivo* :test #'equal) (eq contexto :condicao))
      (rejeitar "Objetivo lógico não é uma premissa de produção."))
    (cond
      ((equal operador "exists")
       (let ((vinculo (first argumentos)))
         (unless (and (listp vinculo) (= (length vinculo) 2) (stringp (first vinculo))
                      (member (second vinculo) '("resource" "enemy") :test #'equal))
           (rejeitar "Existe exige (variável recurso/inimigo)."))
         (validar-expressao (second argumentos) lemas :condicao (cons (first vinculo) vinculadas))))
      (t
       (dolist (argumento argumentos)
         (cond ((consp argumento)
                (validar-expressao argumento lemas (if (equal operador "do") :acao :condicao) vinculadas))
               ((or (numberp argumento) (member argumento vinculadas :test #'equal)
                    (and (variavel-p argumento) (eq contexto :objetivo))
                    (and (stringp argumento) (gethash argumento *aliases*))) nil)
               (t (rejeitar (format nil "Nome ou variável sem vínculo: ~A" argumento)))))))
    (when (and (equal operador "attack")
               (not (member (second expressao) '(":basic" ":heavy-strike") :test #'equal)))
      (rejeitar "Ataque não disponível."))
    (when (and (equal operador "interact") (not (equal (second expressao) ":chop")))
      (rejeitar "Interação não disponível."))
    (when (and (equal operador "manifest")
               (not (and (member (second expressao) '(":spark" ":lightning-bolt") :test #'equal)
                         (equal (third expressao) ":target"))))
      (rejeitar "Manifestação deve informar elemento conhecido e :target."))))

(defun validar-ciclos-lemas (lemas)
  (let ((visitados (make-hash-table :test 'equal)))
    (labels ((visitar (nome)
               (case (gethash nome visitados)
                 (:em-visita (rejeitar "Lemas recursivos não são permitidos."))
                 (:concluido (return-from visitar)))
               (setf (gethash nome visitados) :em-visita)
               (percorrer (third (assoc nome lemas :test #'equal)))
               (setf (gethash nome visitados) :concluido))
             (percorrer (forma)
               (when (consp forma)
                 (when (assoc (first forma) lemas :test #'equal) (visitar (first forma)))
                 (dolist (parte (rest forma)) (percorrer parte)))))
      (dolist (lema lemas) (visitar (first lema))))))

(defun ler-biblioteca (texto &key (classe :fighter) (slots 64))
  (multiple-value-bind (formas posicoes finais) (ler-dados-seguros texto)
    (labels ((sem-cadeias (objeto)
               (when (stringp objeto) (rejeitar "Cadeias entre aspas não fazem parte da DSL."))
               (when (consp objeto) (sem-cadeias (car objeto)) (sem-cadeias (cdr objeto)))))
      (dolist (forma formas) (sem-cadeias forma)))
    (let* ((arvores (mapcar #'arvore-textual formas))
           (nomes (mapcar #'second arvores)) (lemas nil) (definicoes nil))
      (unless (= (length nomes) (length (remove-duplicates nomes :test #'equal)))
        (rejeitar "Nomes de definições devem ser únicos."))
      (dolist (arvore arvores)
        (unless (and (consp arvore) (stringp (second arvore))
                     (not (gethash (second arvore) *aliases*)))
          (rejeitar "A definição precisa de nome próprio não reservado."))
        (when (equal (canonico (first arvore)) "lemma")
          (unless (and (= (length arvore) 4) (listp (third arvore))
                       (every #'stringp (third arvore))
                       (= (length (third arvore)) (length (remove-duplicates (third arvore) :test #'equal))))
            (rejeitar "Formato de lema inválido."))
          (push (list (second arvore) (third arvore)
                      (normalizar-expressao (fourth arvore) nomes (third arvore))) lemas)))
      (dolist (lema lemas) (validar-expressao (third lema) lemas :condicao (second lema)))
      (validar-ciclos-lemas lemas)
      (loop for arvore in arvores
            for posicao in posicoes
            for proxima-posicao in finais do
        (let ((forma (canonico (first arvore))))
          (cond
            ((equal forma "lemma") nil)
            ((member forma '("hypothesis" "default" "oath") :test #'equal)
             (rejeitar "Esta forma pertence a uma classe futura, indisponível na v1." posicao))
            ((not (equal forma "theorem")) (rejeitar "Esperado teorema ou lema." posicao))
            (t
             (let* ((campos (loop for (chave valor) on (cddr arvore) by #'cddr
                                  append (list (canonico chave) valor)))
                    (classe-nome (canonico (campo campos ":class" (string-downcase (symbol-name classe)))))
                    (prioridade (campo campos ":priority" 0))
                    (arvore-final (list "theorem" (second arvore))))
               (unless (member classe-nome '("fighter" "wizard") :test #'equal)
                 (rejeitar "Classe ainda não implementada." posicao))
               (unless (equal classe-nome (string-downcase (symbol-name classe)))
                 (rejeitar "O teorema pertence à outra classe." posicao))
               (unless (and (integerp prioridade) (<= -100000 prioridade 100000))
                 (rejeitar "Prioridade deve ser um inteiro entre -100000 e 100000." posicao))
               (validar-campos campos (if (equal classe-nome "fighter")
                                         '(":class" ":priority" ":premises" ":conclusion")
                                         '(":class" ":priority" ":goal" ":on-success" ":on-failure")))
               (if (equal classe-nome "fighter")
                   (let ((premissas (campo campos ":premises" :ausente))
                         (conclusao (normalizar-expressao (campo campos ":conclusion") nomes)))
                     (unless (listp premissas) (rejeitar "Faltam premissas em lista." posicao))
                     (setf premissas (mapcar (lambda (p) (normalizar-expressao p nomes)) premissas))
                     (dolist (p premissas) (validar-expressao p lemas))
                     (validar-expressao conclusao lemas :acao)
                     (labels ((conferir (acao)
                                (when (member (first acao) '("manifest" "fizzle") :test #'equal)
                                  (rejeitar "Guerreiro não pode manifestar magia."))
                                (when (equal (first acao) "do") (mapc #'conferir (rest acao)))))
                       (conferir conclusao))
                     (setf arvore-final (append arvore-final (list ":premises" premissas ":conclusion" conclusao))))
                   (let* ((objetivo (campo campos ":goal"))
                          (sucesso (normalizar-expressao (campo campos ":on-success") nomes))
                          (falha (normalizar-expressao (campo campos ":on-failure") nomes)))
                     (unless (and (consp objetivo) (equal (canonico (first objetivo)) "prove"))
                       (rejeitar "O Mago exige :goal (prove ...)." posicao))
                     (let* ((proposicao (normalizar-expressao (second objetivo) nomes))
                            (opcoes (loop for (k v) on (cddr objetivo) by #'cddr append (list (canonico k) v)))
                            (dados (mapcar (lambda (p) (normalizar-expressao p nomes)) (campo opcoes ":given")))
                            (axiomas (mapcar #'canonico (campo opcoes ":using-axioms"))))
                       (validar-campos opcoes '(":given" ":using-axioms"))
                       (validar-expressao proposicao lemas :objetivo)
                       (dolist (p dados) (validar-expressao p lemas))
                       (unless (every (lambda (a) (member a '("travel-law" "gather-law" "flee-law" "wait-law"
                                                            "elemental-affinity" "storm-conduction" "spark-law" "lightning-law")
                                                         :test #'equal)) axiomas)
                         (rejeitar "Axioma desconhecido." posicao))
                       (let ((variaveis nil))
                         (labels ((coletar (termo)
                                    (cond ((variavel-p termo) (pushnew termo variaveis :test #'equal))
                                          ((consp termo) (mapc #'coletar termo)))))
                           (coletar proposicao))
                         (validar-expressao sucesso lemas :acao variaveis))
                       (unless (equal falha '("fizzle" ":reason")) (rejeitar "Use :on-failure (fizzle :reason)."))
                       (setf arvore-final (append arvore-final
                            (list ":goal" (append (list "prove" proposicao ":given" dados)
                                                    (when (member ":using-axioms" opcoes :test #'equal)
                                                      (list ":using-axioms" axiomas)))
                                  ":on-success" sucesso ":on-failure" falha))))))
               (push (criar-definicao :nome (second arvore) :classe classe :prioridade prioridade
                                     :arvore arvore-final
                                     :texto-original (string-trim '(#\Space #\Tab #\Newline #\Return)
                                                                  (subseq texto posicao proxima-posicao))
                                     :posicao posicao
                                     :idioma (if (equal (first arvore) "theorem") :en :pt)) definicoes))))))
      (when (> (length definicoes) slots) (rejeitar (format nil "A biblioteca excede ~D slots." slots)))
      (let ((documento
              (loop for arvore in arvores for posicao in posicoes for fim in finais collect
                (if (equal (canonico (first arvore)) "lemma")
                    (criar-definicao :nome (second arvore) :classe classe :tipo :lema
                                     :arvore (cons "lemma" (assoc (second arvore) lemas :test #'equal))
                                     :texto-original (string-trim '(#\Space #\Tab #\Newline #\Return)
                                                                  (subseq texto posicao fim))
                                     :posicao posicao
                                     :idioma (if (equal (first arvore) "lemma") :en :pt))
                    (find (second arvore) definicoes :key #'definicao-nome :test #'equal)))))
        (criar-biblioteca :definicoes (stable-sort (nreverse definicoes) #'> :key #'definicao-prioridade)
                        :lemas lemas :texto texto :documento documento)))))
