(in-package #:qed.logica)

(defstruct (sessao (:constructor criar-sessao)) mundos bibliotecas rascunhos (ativa 0) (idioma :pt) (pausada nil))
(defun fonte-exemplo (classe)
  (uiop:read-file-string (asdf:system-relative-pathname "qed/logic"
                          (if (eq classe :wizard) "exemplos/mago.lisp" "exemplos/guerreiro.lisp"))
                        :external-format :utf-8))
(defun nova-sessao ()
  (criar-sessao :rascunhos (vector (fonte-exemplo :fighter) (fonte-exemplo :wizard)) :mundos (vector (novo-mundo :fighter) (novo-mundo :wizard))
               :bibliotecas (vector (ler-biblioteca (fonte-exemplo :fighter) :classe :fighter :slots 4)
                                     (ler-biblioteca (fonte-exemplo :wizard) :classe :wizard :slots 4))))
(defun mundo-ativo (sessao) (aref (sessao-mundos sessao) (sessao-ativa sessao)))
(defun biblioteca-ativa (sessao) (aref (sessao-bibliotecas sessao) (sessao-ativa sessao)))
(defun alternar-personagem (sessao)
  (cancelar-acao (mundo-ativo sessao) "Personagem alternado.")
  (setf (sessao-ativa sessao) (- 1 (sessao-ativa sessao)))
  (mundo-ativo sessao))
(defun aplicar-biblioteca (sessao texto)
  "A substituição ocorre somente depois da validação completa."
  (let* ((heroi (mundo-heroi (mundo-ativo sessao)))
         (nova (ler-biblioteca texto :classe (heroi-classe heroi) :slots (heroi-slots heroi))))
    (cancelar-acao (mundo-ativo sessao) "Biblioteca atualizada.")
    (clrhash (mundo-falhas (mundo-ativo sessao)))
    (setf (aref (sessao-bibliotecas sessao) (sessao-ativa sessao)) nova)))
(defun avancar-sessao (sessao)
  (unless (sessao-pausada sessao)
    (avancar (mundo-ativo sessao) (lambda (mundo) (avaliar-biblioteca (biblioteca-ativa sessao) mundo)))))
(defun salvo-padrao ()
  (merge-pathnames "qed/partida.sexp"
                  (uiop:ensure-directory-pathname
                   (or (uiop:getenv "XDG_DATA_HOME") (namestring (merge-pathnames ".local/share/" (user-homedir-pathname)))))))

(defun serializar-mundo (mundo biblioteca rascunho)
  (let ((heroi (mundo-heroi mundo)))
    (list :rascunho rascunho :texto (biblioteca-texto biblioteca) :tick (mundo-tick mundo)
          :heroi (list :classe (heroi-classe heroi) :x (heroi-x heroi) :y (heroi-y heroi)
                       :vx (heroi-vx heroi) :vy (heroi-vy heroi) :hp (heroi-hp heroi) :mana (heroi-mana heroi)
                       :xp (heroi-xp heroi) :madeira (heroi-madeira heroi) :morte (heroi-morte heroi)
                       :conhecimentos (heroi-conhecimentos heroi) :pontos-bonus (heroi-pontos-bonus heroi))
          :entidades (mapcar (lambda (e) (list :id (entidade-id e) :tipo (entidade-tipo e)
                                             :x (entidade-x e) :y (entidade-y e) :hp (entidade-hp e)
                                             :retorno (entidade-retorno e) :recarga (entidade-recarga e)
                                             :molhada (if (entidade-molhada e) 1 0))) (mundo-entidades mundo))
          :falhas (loop for nome being the hash-keys of (mundo-falhas mundo) using (hash-value tick)
                        collect (list nome tick)))))
(defun salvar-partida (sessao &optional (caminho (salvo-padrao)))
  (ensure-directories-exist caminho)
  (let ((temporario (pathname (concatenate 'string (namestring caminho) ".tmp")))
        (backup (pathname (concatenate 'string (namestring caminho) ".bak")))
        (*print-pretty* t) (*print-readably* nil) (*print-escape* t) (*print-case* :downcase))
    (unwind-protect
         (progn
           (with-open-file (fluxo temporario :direction :output :if-exists :supersede :external-format :utf-8)
             (write (list :versao 2 :ativa (sessao-ativa sessao) :idioma (sessao-idioma sessao)
                          :mundos (loop for mundo across (sessao-mundos sessao)
                                        for biblioteca across (sessao-bibliotecas sessao)
                                        for rascunho across (sessao-rascunhos sessao)
                                        collect (serializar-mundo mundo biblioteca rascunho))) :stream fluxo)
             (terpri fluxo) (finish-output fluxo))
           (when (probe-file caminho) (uiop:copy-file caminho backup))
           (uiop:rename-file-overwriting-target temporario caminho))
      (when (probe-file temporario) (delete-file temporario))))
  caminho)

(defparameter *chaves-salvo*
  '(:versao :ativa :idioma :mundos :texto :rascunho :tick :heroi :classe :x :y :vx :vy :hp :mana :xp :madeira :morte
    :entidades :id :tipo :retorno :recarga :molhada :falhas :fighter :wizard :slime :wood :pt :en :auto
    :conhecimentos :pontos-bonus))
(defun normalizar-salvo (objeto)
  (cond ((null objeto) nil) ((consp objeto) (mapcar #'normalizar-salvo objeto))
        ((and (symbolp objeto) (equal (nome-token objeto) "nil")) nil)
        ((symbolp objeto)
         (or (find (nome-token objeto) *chaves-salvo* :test #'equal
                   :key (lambda (k) (concatenate 'string ":" (string-downcase (symbol-name k)))))
             (and (equal (nome-token objeto) "nil") nil)
             (rejeitar "Símbolo inesperado no arquivo de progresso.")))
        (t objeto)))
(defun numero-campo (dados chave minimo maximo &optional inteiro)
  (let ((valor (getf dados chave)))
    (unless (and (realp valor) (<= minimo valor maximo) (or (not inteiro) (integerp valor)))
      (rejeitar (format nil "Valor inválido no progresso: ~A" chave))) valor))
(defun validar-plist-salvo (dados)
  (unless (and (listp dados) (evenp (length dados))) (rejeitar "Registro de progresso inválido."))
  (let ((chaves (loop for (chave valor) on dados by #'cddr collect chave)))
    (unless (= (length chaves) (length (remove-duplicates chaves))) (rejeitar "Campo de progresso duplicado."))))
(defun desserializar-mundo (dados classe &optional (versao 2))
  (validar-plist-salvo dados)
  (let* ((mundo (novo-mundo classe)) (heroi (mundo-heroi mundo)) (h (getf dados :heroi)))
    (validar-plist-salvo h)
    (unless (eq classe (getf h :classe)) (rejeitar "Ordem de classes incompatível."))
    (setf (mundo-tick mundo) (numero-campo dados :tick 0 1000000000 t)
          (heroi-x heroi) (numero-campo h :x 12 1428) (heroi-y heroi) (numero-campo h :y 0 300)
          (heroi-vx heroi) 0 (heroi-vy heroi) (numero-campo h :vy -1000 1000)
          (heroi-hp heroi) (numero-campo h :hp -100 100) (heroi-mana heroi) (numero-campo h :mana 0 80)
          (heroi-xp heroi) (numero-campo h :xp 0 1000000000 t)
          (heroi-madeira heroi) (numero-campo h :madeira 0 1000000000 t)
          (heroi-morte heroi) (numero-campo h :morte -1 3))
    (when (<= (heroi-hp heroi) 0) (setf (heroi-estado heroi) :death))
    (if (= versao 1)
        ;; Partidas antigas conservam o vocabulário que já estava liberado.
        (let ((xp (heroi-xp heroi)))
          (setf (heroi-conhecimentos heroi)
                (append (if (eq classe :wizard) '("conducao") (when (>= xp 30) '("estados")))
                        (when (>= xp 60) (list (if (eq classe :wizard) "tempestade" "impacto")))
                        (when (>= xp 100) '("composicao"))))
          (setf (heroi-pontos-bonus heroi) (max 0 (- (pontos-conhecimento heroi)))))
        (setf (heroi-conhecimentos heroi) (getf h :conhecimentos)
              (heroi-pontos-bonus heroi) (numero-campo h :pontos-bonus 0 1 t)))
    (let ((areas (heroi-conhecimentos heroi)))
      (unless (and (listp areas) (<= (length areas) 3)
                   (every #'stringp areas) (= (length areas) (length (remove-duplicates areas :test #'equal)))
                   (every (lambda (id) (let ((area (buscar-area heroi id)))
                                        (and area (plusp (getf area :custo))
                                             (every (lambda (requisito) (area-liberada-p heroi requisito))
                                                    (getf area :requisitos))))) areas)
                   (>= (pontos-conhecimento heroi) 0))
        (rejeitar "Escolhas de ontologia inválidas no progresso.")))
    (atualizar-desbloqueios heroi)
    (unless (= (length (getf dados :entidades)) 6) (rejeitar "A fase deve conter seis entidades."))
    (let ((ids nil))
      (dolist (registro (getf dados :entidades))
        (validar-plist-salvo registro)
        (let* ((id (numero-campo registro :id 1 6 t)) (entidade (buscar-entidade mundo id)))
          (when (member id ids) (rejeitar "Entidade duplicada.")) (push id ids)
          (unless (eq (getf registro :tipo) (entidade-tipo entidade)) (rejeitar "Tipo de entidade inválido."))
          (setf (entidade-x entidade) (numero-campo registro :x 12 1428)
                (entidade-y entidade) (numero-campo registro :y 0 300)
                (entidade-hp entidade) (numero-campo registro :hp -100 35)
                (entidade-retorno entidade) (numero-campo registro :retorno -1 10)
                (entidade-recarga entidade) (numero-campo registro :recarga -1000000000 2)
                (entidade-molhada entidade) (= 1 (numero-campo registro :molhada 0 1 t))))))
    (dolist (falha (getf dados :falhas))
      (unless (and (= (length falha) 2) (stringp (first falha)) (integerp (second falha))
                   (<= 0 (second falha) (+ 60 (mundo-tick mundo)))) (rejeitar "Recarga inválida."))
      (setf (gethash (first falha) (mundo-falhas mundo)) (second falha)))
    (values mundo (ler-biblioteca (getf dados :texto) :classe classe :slots (heroi-slots heroi)))))
(defun ler-partida (caminho)
  (with-open-file (fluxo caminho :external-format :utf-8)
    (when (> (file-length fluxo) 524288) (rejeitar "Arquivo de progresso muito grande.")))
  (let* ((formas (ler-dados-seguros (uiop:read-file-string caminho :external-format :utf-8) :limite 524288))
         (dados (and (= (length formas) 1) (normalizar-salvo (first formas)))))
    (validar-plist-salvo dados)
    (unless (member (getf dados :versao) '(1 2)) (rejeitar "Versão de progresso não suportada."))
    (unless (and (member (getf dados :ativa) '(0 1)) (member (getf dados :idioma) '(:pt :en :auto))
                 (= (length (getf dados :mundos)) 2)) (rejeitar "Sessão de progresso inválida."))
    (let ((sessao (criar-sessao :mundos (make-array 2) :bibliotecas (make-array 2) :rascunhos (make-array 2)
                              :ativa (getf dados :ativa) :idioma (getf dados :idioma))))
      (loop for registro in (getf dados :mundos) for classe in '(:fighter :wizard) for indice from 0 do
        (multiple-value-bind (mundo biblioteca) (desserializar-mundo registro classe (getf dados :versao))
          (let ((rascunho (getf registro :rascunho (biblioteca-texto biblioteca))))
            (unless (and (stringp rascunho) (<= (length rascunho) 65536)) (rejeitar "Rascunho inválido no progresso."))
            (setf (aref (sessao-rascunhos sessao) indice) rascunho))
          (setf (aref (sessao-mundos sessao) indice) mundo (aref (sessao-bibliotecas sessao) indice) biblioteca)))
      sessao)))
(defun carregar-partida (&optional (caminho (salvo-padrao)))
  "Segundo valor informa recuperação de backup. Nunca executa conteúdo do arquivo."
  (handler-case (values (ler-partida caminho) nil)
    (error (erro)
      (let ((backup (pathname (concatenate 'string (namestring caminho) ".bak"))))
        (if (probe-file backup) (values (ler-partida backup) (format nil "Backup recuperado: ~A" erro))
            (error erro))))))
