;; Única fonte de aliases. Primeiro elemento: símbolo canônico; demais: português.
(("theorem" "teorema") ("lemma" "lema")
 ("hypothesis" "hipótese" "hipotese") ("default" "padrao" "padrão") ("oath" "juramento")
 (":priority" ":prioridade") (":premises" ":premissas") (":conclusion" ":conclusao" ":conclusão")
 (":class" ":classe") (":goal" ":objetivo") (":given" ":dado")
 (":using-axioms" ":usando-axiomas") (":on-success" ":ao-sucesso") (":on-failure" ":ao-falha")
 (":refute" ":refutar") (":evidence-against" ":evidencia-contra" ":evidência-contra")
 (":publish-axiom" ":publicar-axioma") (":pattern" ":padrao-observado" ":padrão-observado")
 (":confidence-threshold" ":limiar-confianca" ":limiar-confiança") (":on-confirmed" ":ao-confirmar")
 (":forbids" ":proibe" ":proíbe") (":unless" ":a-menos-que")
 (":deontic-status" ":status-deontico" ":status-deôntico")
 (":holds-unless" ":vale-a-menos-que") (":obligatory" ":obrigatorio" ":obrigatório")
 (":permitted" ":permitido") (":forbidden" ":proibido")
 ("fighter" "guerreiro") ("wizard" "mago") ("rogue" "ladino") ("cleric" "clérigo" "clerigo")
 ("ranger" "patrulheiro") ("summoner" "invocador") ("paladin" "paladino")
 ("illusionist" "ilusionista") ("alchemist" "alquimista") ("druid" "druida")
 ("and" "e") ("or" "ou") ("not" "nao" "não") ("exists" "existe") ("prove" "provar")
 ("state" "estado") ("stat" "atributo") ("position" "posicao" "posição")
 ("resource-type" "tipo-recurso") ("within-range" "dentro-do-alcance")
 ("enemy-in-range" "inimigo-em-alcance") ("resource-nearby" "recurso-proximo" "recurso-próximo")
 ("enemy-nearby" "inimigo-proximo" "inimigo-próximo")
 ("line-of-sight" "linha-de-visao" "linha-de-visão") ("mana-available" "mana-disponivel" "mana-disponível")
 ("reachable" "alcancavel" "alcançável") ("status" "condicao" "condição")
 ("self" "eu") ("enemy" "inimigo") ("resource" "recurso")
 ("nearest" "mais-proximo" "mais-próximo") ("nearest-threat" "ameaca-mais-proxima" "ameaça-mais-próxima")
 ("move-to" "mover-para") ("attack" "atacar") ("interact" "interagir")
 ("flee" "fugir") ("wait" "esperar") ("do" "fazer") ("manifest" "manifestar") ("fizzle" "falhar")
 ("can-move" "pode-mover") ("can-gather" "pode-coletar") ("can-flee" "pode-fugir") ("can-wait" "pode-esperar")
 ("strikes" "atinge") ("affinity" "afinidade") ("conductive" "condutor") ("focus-equipped" "foco-equipado")
 ("wet" "molhado") ("spark" "centelha") ("lightning" "relampago" "relâmpago") ("storm" "tempestade")
 ("travel-law" "lei-deslocamento") ("gather-law" "lei-coleta") ("flee-law" "lei-fuga") ("wait-law" "lei-espera")
 ("elemental-affinity" "afinidade-elemental") ("storm-conduction" "conducao-tempestade" "condução-tempestade")
 ("spark-law" "lei-centelha") ("lightning-law" "lei-relampago" "lei-relâmpago")
 (":idle" ":ocioso" "idle" "ocioso") (":walk" ":andando" "walk" "andando")
 (":jump" ":pulando" "jump" "pulando") (":attack" ":atacando" "attacking" "atacando")
 (":gather" ":coletando" "gathering" "coletando") (":cast" ":conjurando" "casting" "conjurando")
 (":hurt" ":ferido" "hurt" "ferido") (":death" ":morto" "death" "morto")
 (":wood" ":madeira" "wood" "madeira") (":slime" ":gosma" "slime" "gosma")
 (":chop" ":cortar" "chop" "cortar") (":basic" ":basico" ":básico" "basic" "basico" "básico")
 (":heavy-strike" ":golpe-pesado" "heavy-strike" "golpe-pesado")
 (":melee" ":corpo-a-corpo" "melee" "corpo-a-corpo")
 (":aggro" ":agressao" ":agressão" "aggro" "agressao" "agressão")
 (":hp" ":vida" "hp" "vida") (":max-hp" ":vida-maxima" ":vida-máxima" "max-hp" "vida-maxima" "vida-máxima")
 (":mana" "mana") (":max-mana" ":mana-maxima" ":mana-máxima" "max-mana" "mana-maxima" "mana-máxima")
 (":xp" ":experiencia" ":experiência" "xp" "experiencia" "experiência")
 (":wet" ":molhado" "wet-state") (":target" ":alvo" "target" "alvo")
 (":reason" ":motivo" "reason" "motivo")
 (":spark" ":centelha" "spark-effect" "centelha-efeito")
 (":lightning-bolt" ":raio" "lightning-bolt" "raio")
 ("t" "verdadeiro") ("nil" "falso") ("<") (">") ("<=") (">=") ("=") ("+") ("-") ("*") ("/"))
