; Interface RGBA. Painéis: nove recortes com bordas de 32 pixels na fonte.
(:versao 1 :recorte-painel 32 :assets (
  (:arquivo "painel.png" :quadro (256 256) :margem 0)
  (:arquivo "grimorio.png" :quadro (256 256) :margem 0)
  (:arquivo "bloqueado.png" :quadro (256 256) :margem 0)
  (:arquivo "liberado.png" :quadro (256 256) :margem 0)
  (:arquivo "selecionado.png" :quadro (256 256) :margem 0)
  (:arquivo "botao.png" :quadro (256 256) :margem 0)
  (:arquivo "existencia.png" :quadro (96 96) :margem 2)
  (:arquivo "espaco.png" :quadro (96 96) :margem 2)
  (:arquivo "materia.png" :quadro (96 96) :margem 2)
  (:arquivo "conflito.png" :quadro (96 96) :margem 2)
  (:arquivo "estados.png" :quadro (96 96) :margem 2)
  (:arquivo "impacto.png" :quadro (96 96) :margem 2)
  (:arquivo "afinidade.png" :quadro (96 96) :margem 2)
  (:arquivo "conducao.png" :quadro (96 96) :margem 2)
  (:arquivo "tempestade.png" :quadro (96 96) :margem 2)
  (:arquivo "composicao.png" :quadro (96 96) :margem 2)
  (:arquivo "cadeado.png" :quadro (96 96) :margem 2)
  (:arquivo "conhecimento.png" :quadro (96 96) :margem 2)
  (:arquivo "fundo.png" :quadro (960 540) :margem 0)))
