;; Capturas reais do renderer para o manual, em uma janela oculta e sem saves.
(require :asdf)
(unless (find-package :ql)
  (load (or (uiop:getenv "QED_QUICKLISP")
            (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))))
(asdf:load-asd (truename (merge-pathnames "../qed.asd" *load-truename*)))
(uiop:symbol-call :ql :quickload "qed/app" :silent t)
(in-package #:qed.aplicativo)
(let* ((sessao (nova-sessao))
       (lwlgl.glfw:*glfw-platform-preference* (if (uiop:getenv "DISPLAY") :x11 :auto)))
  (multiple-value-bind (artes pendencias) (validar-assets)
    (assert (null pendencias))
    (lwlgl.glfw:with-glfw ()
      (lwlgl.glfw:default-window-hints)
      (lwlgl.glfw:window-hint lwlgl.glfw:context-version-major 3)
      (lwlgl.glfw:window-hint lwlgl.glfw:context-version-minor 3)
      (lwlgl.glfw:window-hint lwlgl.glfw:opengl-profile lwlgl.glfw:opengl-core-profile)
      (lwlgl.glfw:window-hint lwlgl.glfw:visible lwlgl.glfw:false)
      (lwlgl.glfw:with-window (janela 1440 900 "QED — capturas do manual")
        (lwlgl.glfw:make-context-current janela)
        (lwlgl.opengl:load-opengl :error-on-missing nil)
        (let ((grafica (iniciar-grafica)))
          (unwind-protect
               (labels ((capturar (nome tela)
                          (mudar-tela grafica tela)
                          (multiple-value-bind (w h) (lwlgl.glfw:framebuffer-size janela)
                            (setf (grafica-largura grafica) w (grafica-altura grafica) h)
                            (lwlgl.opengl:gl-viewport 0 0 w h))
                          (desenhar-interface grafica sessao
                            (novo-editor (biblioteca-texto (biblioteca-ativa sessao))) artes pendencias)
                          (capturar-quadro grafica
                            (asdf:system-relative-pathname "qed/app" (format nil "build/capturas/~A.ppm" nome)))))
                 ;; Aguarda um golpe real, após o primeiro ponto de conhecimento.
                 (loop repeat 18000 for heroi = (mundo-heroi (mundo-ativo sessao))
                       do (avancar-sessao sessao)
                       when (and (>= (heroi-xp heroi) 30) (eq (heroi-estado heroi) :attack)
                                 (< 0.25 (heroi-tempo-animacao heroi) 0.35)) do (return))
                 (capturar "mundo" :mundo)
                 (alternar-personagem sessao)
                 (loop repeat 18000 do (avancar-sessao sessao)
                       when (>= (heroi-xp (mundo-heroi (mundo-ativo sessao))) 60) do (return))
                 (setf (grafica-area-selecionada grafica) "conducao")
                 (assert (comprar-area-selecionada grafica sessao))
                 (setf (grafica-area-selecionada grafica) "tempestade")
                 (capturar "ontologia" :ontologia)
                 (loop repeat 6000 do (avancar-sessao sessao)
                       when (eq (heroi-estado (mundo-heroi (mundo-ativo sessao))) :cast) do (return))
                 (capturar "teoremas" :teoremas)
                 (capturar "guia" :guia)
                 (format t "Quatro capturas reais em build/capturas/. Nenhuma partida foi gravada.~%"))
            (encerrar-grafica grafica artes)))))))
