(in-package #:qed.aplicativo)

(defun nome-material (material)
  (case material (:wood "madeira") (:iron-ore "ferro") (:arcane-crystal "cristais")
    (otherwise (format nil "~(~A~)" material))))

(defun texto-custos (dados)
  (format nil "~{~A~^  +  ~}"
          (loop for (material quantidade) on (getf dados :custos) by #'cddr
                collect (format nil "~D ~A" quantidade (nome-material material)))))

(defun texto-situacao-construcao (situacao)
  (case situacao (:construida "CONSTRUÍDA") (:disponivel "DISPONÍVEL")
    (:requisitos "OBJETIVO PENDENTE") (:materiais "MATERIAIS INSUFICIENTES")
    (otherwise "INDISPONÍVEL")))

(defun comando-acampamento-no-ponto (grafica x y)
  (loop for (comando . retangulo) in (grafica-regioes-acampamento grafica)
        when (dentro-retangulo-p x y retangulo) return comando))

(defun comprar-construcao-selecionada (grafica sessao)
  (multiple-value-bind (sucesso motivo)
      (construir (mundo-ativo sessao) (grafica-construcao-selecionada grafica))
    (setf (grafica-mensagem-acampamento grafica)
          (if sucesso "Construção concluída. O mundo e a ontologia foram atualizados."
              (case motivo (:construida "Esta construção já foi concluída.")
                (:requisitos "Conclua os objetivos anteriores primeiro.")
                (:materiais "O inventário ainda não cobre todos os custos.")
                (otherwise "A construção não está disponível."))))
    sucesso))

(defun desenhar-acampamento (grafica sessao)
  (let* ((largura (grafica-largura grafica)) (altura (grafica-altura grafica))
         (mundo (mundo-ativo sessao)) (heroi (mundo-heroi mundo))
         (margem 24) (topo 100) (largura-cartao (floor (- largura 78) 2))
         (altura-cartao 174))
    (setf (grafica-regioes-acampamento grafica) nil)
    (painel-interface grafica "grimorio" margem topo (- largura (* 2 margem)) (- altura topo 58)
                      :borda 20 :escurecer 0.68)
    (texto grafica "ACAMPAMENTO / CAMPANHA" 54 116 *cor-dourada*)
    (texto grafica (format nil "~A  |  Inventário: ~D madeira, ~D ferro, ~D cristais"
                          (getf (regiao-atual mundo) :nome)
                          (heroi-madeira heroi) (quantidade-material heroi :iron-ore)
                          (quantidade-material heroi :arcane-crystal))
           54 142 *cor-suave*)
    (texto grafica (format nil "Próxima ação: ~A" (resumo-campanha heroi)) 54 166 *cor-verde*)
    (loop for dados in qed.nucleo::*construcoes-campanha*
          for indice from 0
          for coluna = (mod indice 2) for linha = (floor indice 2)
          for x = (+ 48 (* coluna (+ largura-cartao 18)))
          for y = (+ 202 (* linha (+ altura-cartao 18)))
          for id = (getf dados :id)
          for situacao = (situacao-construcao heroi id)
          for selecionada = (eq id (grafica-construcao-selecionada grafica)) do
      (let ((retangulo (list x y largura-cartao altura-cartao)))
        (painel-interface grafica (if selecionada "selecionado"
                                      (if (eq situacao :construida) "liberado" "painel"))
                         x y largura-cartao altura-cartao :borda 14 :escurecer 0.45)
        (texto grafica (string-upcase (getf dados :nome)) (+ x 22) (+ y 18)
               (if (eq situacao :construida) *cor-verde* *cor-dourada*))
        (texto grafica (texto-situacao-construcao situacao) (+ x 22) (+ y 46)
               (if (member situacao '(:construida :disponivel)) *cor-verde* *cor-erro*))
        (texto grafica (format nil "Custo: ~A" (texto-custos dados)) (+ x 22) (+ y 74) *cor-texto*)
        (texto-quebrado grafica (getf dados :descricao) (+ x 22) (+ y 100)
                        (max 18 (floor (- largura-cartao 44) 10)) *cor-suave* 3)
        (push (cons id retangulo) (grafica-regioes-acampamento grafica))))
    (let* ((dados (especificacao-construcao (grafica-construcao-selecionada grafica)))
           (situacao (situacao-construcao heroi (getf dados :id)))
           (x 48) (y (- altura 146)) (w (- largura 96))
           (botao (list (+ x w -220) (+ y 12) 196 48)))
      (painel-interface grafica "painel" x y w 76 :borda 12 :escurecer 0.55)
      (texto-quebrado grafica (grafica-mensagem-acampamento grafica) (+ x 20) (+ y 14)
                      (max 20 (floor (- w 270) 10)) *cor-suave* 2)
      (painel-interface grafica (if (eq situacao :disponivel) "selecionado" "botao")
                       (first botao) (second botao) (third botao) (fourth botao) :borda 10)
      (texto grafica (if (eq situacao :disponivel) "CONSTRUIR [ENTER]" (texto-situacao-construcao situacao))
             (+ (first botao) 14) (+ (second botao) 15)
             (if (eq situacao :disponivel) *cor-dourada* *cor-suave*))
      (push (cons :construir botao) (grafica-regioes-acampamento grafica)))
    (painel-interface grafica "botao" 6 (- altura 42) (- largura 12) 38 :borda 8)
    (texto grafica "F9 volta aos teoremas | Clique numa construção | Enter confirma a compra única" 24 (- altura 32) *cor-suave*)
    (descarregar grafica)))
