(in-package #:qed.aplicativo)

(defparameter *paleta*
  '(#x172038 #x253A5E #x3C5E8B #x4F8FBA #x73BED3 #xA4DDDB
    #x19332D #x25562E #x468232 #x75A743 #xA8CA58 #xD0DA91
    #x4D2B32 #x7A4841 #xAD7757 #xC09473 #xD7B594 #xE7D5B3
    #xA53030 #xCF573C #xDA863E #xE8C170 #x8E478C #xBDA1D8))
(defstruct (animacao (:constructor criar-animacao)) nome arquivo largura altura quadros duracao repeticao pivo textura)
(defparameter *animacoes-exigidas*
  '(("guerreiro" "idle" "walk" "attack" "gather" "hurt" "death" "jump")
    ("mago" "idle" "walk" "attack" "gather" "hurt" "death" "jump" "cast")
    ("slime" "idle" "attack" "hurt" "death")
    ("sentinela" "idle" "windup" "attack" "recovery" "hurt" "death")
    ("guardiao" "idle" "windup" "attack" "recovery" "hurt" "death")
    ("madeira" "idle") ("terreno" "idle") ("magia" "spark" "lightning") ("icones" "idle")
    ("agua" "idle") ("cenario" "idle") ("mina" "idle") ("ruinas" "idle")
    ("minerio" "idle") ("cristal" "idle") ("passagem-mina" "idle")
    ("passagem-observatorio" "idle") ("abrigo" "idle") ("oficina" "idle")
    ("arsenal" "idle") ("observatorio" "idle")))
(defun diretorio-assets () (asdf:system-relative-pathname "qed/app" "assets/"))
(defparameter *interface-exigida*
  (append (mapcar (lambda (nome) (list nome 256 256)) '("painel" "grimorio" "bloqueado" "liberado" "selecionado" "botao"))
          (mapcar (lambda (nome) (list nome 96 96)) '("existencia" "espaco" "materia" "conflito" "estados" "impacto"
                    "afinidade" "conducao" "tempestade" "composicao" "cadeado" "conhecimento"))
          '(("fundo" 960 540))))
(defun especificacao-animacao (grupo estado)
  (let* ((personagem (member grupo '("guerreiro" "mago") :test #'equal))
         (inimigo (member grupo '("slime" "sentinela" "guardiao") :test #'equal))
         (animado (or personagem inimigo))
         (quadro (cond (animado '(64 64))
                       ((member grupo '("cenario" "mina" "ruinas") :test #'equal) '(480 270))
                       ((member grupo '("madeira" "terreno" "icones" "agua") :test #'equal) '(16 16))
                       ((member grupo '("passagem-mina" "passagem-observatorio" "abrigo" "oficina"
                                       "arsenal" "observatorio") :test #'equal) '(64 64))
                       (t '(32 32))))
         (quadros (cond (personagem (if (equal estado "death") 7 8))
                        (inimigo 8)
                        ((equal grupo "terreno") 2)
                        ((equal grupo "icones") 4)))
         (duracao (and animado (cond ((equal estado "idle") 100)
                                    ((and inimigo (not (equal grupo "slime")) (equal estado "windup")) 100)
                                    ((equal estado "hurt") 50)
                                    ((equal estado "death") (if personagem 125 (if (equal grupo "slime") 100 125)))
                                    ((equal estado "recovery") 150)
                                    (t 75)))))
    (list :quadro quadro :quadros quadros :duracao duracao :pivo (and animado '(32 60)))))
(defun configurar-png ()
  (pushnew (asdf:system-relative-pathname "lwlgl/stb" "native/build/")
           cffi:*foreign-library-directories* :test #'equal)
  (lwlgl.core:ensure-native-module :lwlgl-stb))
(defun ler-animacao (caminho grupo estado)
  (let* ((formas (ler-dados-seguros (uiop:read-file-string caminho :external-format :utf-8)))
         (dados (qed.logica::arvore-textual (first formas))))
    (unless (= (length formas) 1) (error "Metadados devem conter um único registro."))
    (qed.logica::validar-campos dados '(":versao" ":arquivo" ":quadro" ":quadros" ":duracao-ms" ":repetir" ":pivo"))
    (flet ((campo (chave) (qed.logica::campo dados chave)))
      (let* ((arquivo (campo ":arquivo")) (quadro (campo ":quadro")) (quantidade (campo ":quadros"))
             (duracao (campo ":duracao-ms")) (pivo (campo ":pivo")) (repetir (campo ":repetir"))
             (especificacao (especificacao-animacao grupo estado)))
        (unless (and (eql (campo ":versao") 1) (stringp arquivo)
                     (not (search ".." arquivo)) (not (find #\/ arquivo)) (not (find #\\ arquivo))
                     (equalp (pathname-type arquivo) "png")
                     (equal quadro (getf especificacao :quadro))
                     (integerp quantidade) (<= 1 quantidade 64)
                     (integerp duracao) (<= 16 duracao 2000)
                     (member repetir '(0 1)) (listp pivo) (= (length pivo) 2)
                     (every #'integerp pivo) (<= 0 (first pivo) (first quadro)) (<= 0 (second pivo) (second quadro)))
          (error "Metadados inválidos: ~A" caminho))
        (unless (and (equal quadro (getf especificacao :quadro))
                     (or (null (getf especificacao :quadros)) (= quantidade (getf especificacao :quadros)))
                     (or (null (getf especificacao :duracao)) (= duracao (getf especificacao :duracao)))
                     (or (null (getf especificacao :pivo)) (equal pivo (getf especificacao :pivo))))
          (error "Animação fora da especificação do guia: ~A/~A" grupo estado))
        (let ((imagem (merge-pathnames arquivo caminho)))
          (multiple-value-bind (largura altura canais) (lwlgl.stb:image-info imagem)
            (declare (ignore canais))
            (unless (and (= largura (* quantidade (first quadro))) (= altura (second quadro)))
              (error "A faixa PNG não corresponde aos metadados: ~A" imagem)))
          (lwlgl.stb:with-image (png imagem :channels 4)
            (dotimes (indice (* (lwlgl.stb:image-width png) (lwlgl.stb:image-height png)))
              (let* ((ponteiro (lwlgl.stb:image-pixels png)) (base (* indice 4))
                     (alfa (cffi:mem-aref ponteiro :unsigned-char (+ base 3)))
                     (cor (+ (ash (cffi:mem-aref ponteiro :unsigned-char base) 16)
                             (ash (cffi:mem-aref ponteiro :unsigned-char (+ base 1)) 8)
                             (cffi:mem-aref ponteiro :unsigned-char (+ base 2)))))
                (unless (and (member alfa '(0 255)) (or (zerop alfa) (member cor *paleta*)))
                  (error "Pixel fora da paleta ou transparência parcial: ~A" imagem)))))
          (criar-animacao :arquivo imagem :largura (first quadro) :altura (second quadro)
                         :quadros quantidade :duracao duracao :repeticao (= repetir 1) :pivo pivo))))))
(defun validar-assets (&optional (diretorio (diretorio-assets)))
  "Retorna tabela de animações e lista de pendências; nunca fabrica arte."
  (configurar-png)
  (let ((arquivo (asdf:system-relative-pathname "qed/app" "dados/paleta-gerada.sexp")))
    (when (probe-file arquivo)
      (let* ((formas (ler-dados-seguros (uiop:read-file-string arquivo :external-format :utf-8)))
             (cores (qed.logica::arvore-textual (first formas))))
        (unless (and (= (length formas) 1) (listp cores) (<= 1 (length cores) 255)
                     (every (lambda (cor) (and (integerp cor) (<= 0 cor #xffffff))) cores))
          (error "Paleta gerada inválida."))
        (setf *paleta* cores))))
  (let ((tabela (make-hash-table :test 'equal)) (pendencias nil))
    (dolist (grupo *animacoes-exigidas*)
      (dolist (estado (rest grupo))
        (let* ((nome (format nil "~A/~A" (first grupo) estado))
               (caminho (merge-pathnames (concatenate 'string nome ".sexp") diretorio)))
          (if (probe-file caminho)
              (handler-case (setf (gethash nome tabela) (ler-animacao caminho (first grupo) estado))
                (error (erro) (push (format nil "~A: ~A" nome erro) pendencias)))
              (push (concatenate 'string nome ".sexp + PNG") pendencias)))))
    ;; A UI usa RGBA próprio, independente da paleta indexada dos sprites.
    (dolist (item *interface-exigida*)
      (destructuring-bind (nome largura altura) item
        (let* ((chave (concatenate 'string "interface/" nome))
               (arquivo (merge-pathnames (concatenate 'string chave ".png") diretorio)))
          (handler-case
              (progn
                (multiple-value-bind (w h canais) (lwlgl.stb:image-info arquivo)
                  (declare (ignore canais))
                  (unless (and (= w largura) (= h altura)) (error "Dimensões de UI inválidas: ~A" nome)))
                (setf (gethash chave tabela)
                      (criar-animacao :arquivo arquivo :largura largura :altura altura
                                     :quadros 1 :duracao 1000 :pivo '(0 0))))
            (error (erro) (push (format nil "~A: ~A" chave erro) pendencias))))))
    (values tabela (nreverse pendencias))))
