(in-package #:qed.aplicativo)

(defstruct (editor (:constructor criar-editor)) (texto "") (cursor 0) ancora (rolagem 0) (coluna-rolagem 0)
  desfazer refazer (mensagem "Ctrl+Enter aplica a biblioteca. F1 alterna personagem.")
  (sujo nil) (revisao 0) (revisao-validada -1) erro)
(defun novo-editor (texto) (criar-editor :texto texto))
(defun limites-selecao (editor)
  (values (min (editor-cursor editor) (or (editor-ancora editor) (editor-cursor editor)))
          (max (editor-cursor editor) (or (editor-ancora editor) (editor-cursor editor)))))
(defun instantaneo-editor (editor)
  (list (editor-texto editor) (editor-cursor editor) (editor-ancora editor)))
(defun restaurar-editor (editor instantaneo)
  (setf (editor-texto editor) (first instantaneo) (editor-cursor editor) (second instantaneo)
        (editor-ancora editor) (third instantaneo) (editor-sujo editor) t)
  (incf (editor-revisao editor)))
(defun substituir-selecao (editor texto)
  (multiple-value-bind (inicio fim) (limites-selecao editor)
    (when (<= (+ (- (length (editor-texto editor)) (- fim inicio)) (length texto)) 65536)
      (push (instantaneo-editor editor) (editor-desfazer editor))
      (when (> (length (editor-desfazer editor)) 100) (setf (editor-desfazer editor) (subseq (editor-desfazer editor) 0 100)))
      (setf (editor-refazer editor) nil
            (editor-texto editor) (concatenate 'string (subseq (editor-texto editor) 0 inicio) texto
                                               (subseq (editor-texto editor) fim))
            (editor-cursor editor) (+ inicio (length texto)) (editor-ancora editor) nil
            (editor-sujo editor) t)
      (incf (editor-revisao editor)))))
(defun desfazer-edicao (editor &optional refazer)
  (let ((origem (if refazer (editor-refazer editor) (editor-desfazer editor))))
    (when origem
      (if refazer
          (progn (push (instantaneo-editor editor) (editor-desfazer editor)) (pop (editor-refazer editor)))
          (progn (push (instantaneo-editor editor) (editor-refazer editor)) (pop (editor-desfazer editor))))
      (restaurar-editor editor (first origem)))))
(defun mover-cursor (editor posicao selecionar)
  (when (and selecionar (null (editor-ancora editor))) (setf (editor-ancora editor) (editor-cursor editor)))
  (unless selecionar (setf (editor-ancora editor) nil))
  (setf (editor-cursor editor) (max 0 (min (length (editor-texto editor)) posicao))))
(defun linha-coluna (texto posicao)
  (let ((inicio (position #\Newline texto :end posicao :from-end t)))
    (values (count #\Newline texto :end posicao) (- posicao (if inicio (1+ inicio) 0)))))
(defun posicao-linha (texto linha coluna)
  (let ((inicio 0))
    (dotimes (indice linha)
      (declare (ignorable indice))
      (setf inicio (let ((fim (position #\Newline texto :start inicio))) (if fim (1+ fim) (length texto)))))
    (min (+ inicio coluna) (or (position #\Newline texto :start inicio) (length texto)))))
(defun mover-vertical (editor deslocamento selecionar)
  (multiple-value-bind (linha coluna) (linha-coluna (editor-texto editor) (editor-cursor editor))
    (mover-cursor editor (posicao-linha (editor-texto editor) (max 0 (+ linha deslocamento)) coluna) selecionar)))
(defun apagar-editor (editor &optional adiante)
  (multiple-value-bind (inicio fim) (limites-selecao editor)
    (when (= inicio fim)
      (setf (editor-ancora editor) (max 0 (min (length (editor-texto editor))
                                             (+ (editor-cursor editor) (if adiante 1 -1))))))
    (substituir-selecao editor "")))
(defun texto-selecionado (editor)
  (multiple-value-bind (inicio fim) (limites-selecao editor) (subseq (editor-texto editor) inicio fim)))
(defun validar-editor (editor sessao)
  (unless (= (editor-revisao editor) (editor-revisao-validada editor))
    (setf (editor-revisao-validada editor) (editor-revisao editor))
    (handler-case
        (progn (ler-biblioteca (editor-texto editor)
                              :classe (heroi-classe (mundo-heroi (mundo-ativo sessao)))
                              :slots (heroi-slots (mundo-heroi (mundo-ativo sessao))))
               (setf (editor-erro editor) nil))
      (error (erro) (setf (editor-erro editor) (princ-to-string erro))))))
(defun aplicar-editor (editor sessao)
  (handler-case
      (progn (aplicar-biblioteca sessao (editor-texto editor))
             (setf (editor-sujo editor) nil (editor-erro editor) nil
                   (editor-mensagem editor) "Biblioteca aplicada. O autômato já está usando suas definições."))
    (error (erro) (setf (editor-erro editor) (princ-to-string erro)
                       (editor-mensagem editor) "A biblioteca anterior continua ativa."))))
(defun par-correspondente (texto cursor)
  "Ignora comentários; não interpreta código para destacar parênteses."
  (let ((pilha nil) (comentario nil) (pares (make-hash-table)))
    (loop for c across texto for i from 0 do
      (cond (comentario (when (char= c #\Newline) (setf comentario nil)))
            ((char= c #\;) (setf comentario t))
            ((char= c #\() (push i pilha))
            ((and (char= c #\)) pilha)
             (let ((abertura (pop pilha))) (setf (gethash abertura pares) i (gethash i pares) abertura)))))
    (let ((posicao (if (and (< cursor (length texto)) (find (char texto cursor) "()")) cursor (1- cursor))))
      (values posicao (gethash posicao pares)))))
