(in-package #:qed.aplicativo)

(defstruct (grafica (:constructor criar-grafica)) programa vao vbo atlas glifos (largura 1440) (altura 900)
  (rolagem-diagnostico 0)
  (mundo-ampliado nil)
  (guia nil) (rolagem-guia 0)
  (ontologia nil) (area-selecionada "existencia") (rolagem-area 0) regioes-ontologia
  (mensagem-ontologia "Selecione uma área para conhecer seu vocabulário.")
  (vertices (make-array 20000 :element-type 'single-float :adjustable t :fill-pointer 0)))
(defparameter *cor-texto* '(0.91 0.87 0.78 1.0))
(defparameter *cor-suave* '(0.56 0.64 0.67 1.0))
(defparameter *cor-verde* '(0.64 0.85 0.68 1.0))
(defparameter *cor-dourada* '(0.91 0.75 0.44 1.0))
(defparameter *cor-erro* '(0.93 0.45 0.36 1.0))
(defun criar-atlas-fonte ()
  (let ((pixels (make-array (* 1024 1024 4) :element-type '(unsigned-byte 8) :initial-element 0))
        (glifos (make-hash-table))
        (arquivo (or (uiop:getenv "QED_FONTE") "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf")))
    (unless (probe-file arquivo) (error "Fonte ausente. Informe um TTF monoespaçado em QED_FONTE."))
    (dotimes (i 4) (setf (aref pixels i) 255))
    (ft2:with-open-face (fonte arquivo)
      (ft2:set-pixel-sizes fonte 0 16)
      (loop for codigo in (append (loop for c from 32 to 383 collect c) '(8212 8594 8804 8805))
            for indice from 1
            for caractere = (code-char codigo) do
        (let ((px (* (mod indice 32) 32)) (py (* (floor indice 32) 32)))
          (ft2:do-string-render (fonte (string caractere) mapa x y)
            (let* ((matriz (ft2:bitmap-to-array mapa)) (altura (array-dimension matriz 0))
                   (largura (array-dimension matriz 1)))
              (dotimes (linha altura)
                (dotimes (coluna largura)
                  (let ((base (* 4 (+ px coluna (* 1024 (+ py linha))))))
                    (setf (aref pixels base) 255 (aref pixels (+ base 1)) 255
                          (aref pixels (+ base 2)) 255 (aref pixels (+ base 3)) (aref matriz linha coluna)))))
              (setf (gethash caractere glifos) (list px py largura altura x y)))))))
    (values (lwlgl.core:with-foreign-array (ponteiro :unsigned-char pixels)
              (lwlgl.opengl:create-texture-2d 1024 1024 ponteiro
                :min-filter lwlgl.opengl:+gl-nearest+ :mag-filter lwlgl.opengl:+gl-nearest+)) glifos)))
(defun iniciar-grafica ()
  (multiple-value-bind (atlas glifos) (criar-atlas-fonte)
    (let ((grafica (criar-grafica :atlas atlas :glifos glifos
                     :vao (lwlgl.opengl:make-vertex-array) :vbo (lwlgl.opengl:make-buffer)
                     :programa (lwlgl.opengl:make-program
"#version 330 core
layout(location=0) in vec2 posicao;
layout(location=1) in vec2 uv;
layout(location=2) in vec4 cor;
uniform vec2 tamanho;
out vec2 coordenada;
out vec4 tonalidade;
void main(){ gl_Position=vec4(posicao.x/tamanho.x*2.0-1.0,1.0-posicao.y/tamanho.y*2.0,0.0,1.0); coordenada=uv; tonalidade=cor; }"
"#version 330 core
in vec2 coordenada;
in vec4 tonalidade;
uniform sampler2D imagem;
out vec4 saida;
void main(){ saida=texture(imagem,coordenada)*tonalidade; }"))))
      (lwlgl.opengl:gl-bind-vertex-array (grafica-vao grafica))
      (lwlgl.opengl:gl-bind-buffer lwlgl.opengl:+gl-array-buffer+ (grafica-vbo grafica))
      (loop for indice from 0 for quantidade in '(2 2 4) for deslocamento in '(0 8 16) do
        (lwlgl.opengl:gl-enable-vertex-attrib-array indice)
        (lwlgl.opengl:gl-vertex-attrib-pointer indice quantidade lwlgl.opengl:+gl-float+ 0 32 (cffi:make-pointer deslocamento)))
      (lwlgl.opengl:gl-enable lwlgl.opengl:+gl-blend+)
      (lwlgl.opengl:gl-blend-func lwlgl.opengl:+gl-src-alpha+ lwlgl.opengl:+gl-one-minus-src-alpha+)
      grafica)))
(defun encerrar-grafica (grafica animacoes)
  (maphash (lambda (nome animacao) (declare (ignore nome))
             (when (animacao-textura animacao) (lwlgl.opengl:delete-texture (animacao-textura animacao)))) animacoes)
  (lwlgl.opengl:delete-texture (grafica-atlas grafica))
  (lwlgl.opengl:delete-buffer (grafica-vbo grafica))
  (lwlgl.opengl:delete-vertex-array (grafica-vao grafica))
  (lwlgl.opengl:gl-delete-program (grafica-programa grafica)))
(defun quadrilatero (grafica x y largura altura cor u v uf vf)
  (let ((vertices (grafica-vertices grafica)))
    (dolist (vertice (list (list x y u v) (list (+ x largura) y uf v) (list (+ x largura) (+ y altura) uf vf)
                          (list x y u v) (list (+ x largura) (+ y altura) uf vf) (list x (+ y altura) u vf)))
      (dolist (valor (append vertice cor)) (vector-push-extend (coerce valor 'single-float) vertices)))))
(defun retangulo (grafica x y largura altura cor)
  (quadrilatero grafica x y largura altura cor (/ 0.5 1024) (/ 0.5 1024) (/ 0.5 1024) (/ 0.5 1024)))
(defun texto (grafica cadeia x y &optional (cor *cor-texto*))
  (loop for caractere across cadeia for coluna from 0 do
    (let ((glifo (or (gethash caractere (grafica-glifos grafica)) (gethash #\? (grafica-glifos grafica)))))
      (destructuring-bind (px py largura altura dx dy) glifo
        (when (plusp largura)
          (quadrilatero grafica (+ x (* coluna 10) dx) (+ y dy) largura altura cor
                         (/ px 1024) (/ py 1024) (/ (+ px largura) 1024) (/ (+ py altura) 1024)))))))
(defun descarregar (grafica &optional textura)
  (let ((vertices (grafica-vertices grafica)) (programa (grafica-programa grafica)))
    (when (plusp (length vertices))
      (lwlgl.opengl:gl-use-program programa)
      (lwlgl.opengl:gl-bind-vertex-array (grafica-vao grafica))
      (lwlgl.opengl:gl-bind-buffer lwlgl.opengl:+gl-array-buffer+ (grafica-vbo grafica))
      (lwlgl.opengl:upload-floats lwlgl.opengl:+gl-array-buffer+ vertices lwlgl.opengl:+gl-stream-draw+)
      (cffi:with-foreign-string (nome "tamanho")
        (lwlgl.opengl:gl-uniform-2f (lwlgl.opengl:gl-get-uniform-location programa nome)
                                  (coerce (grafica-largura grafica) 'single-float)
                                  (coerce (grafica-altura grafica) 'single-float)))
      (lwlgl.opengl:gl-active-texture lwlgl.opengl:+gl-texture0+)
      (lwlgl.opengl:gl-bind-texture lwlgl.opengl:+gl-texture-2d+ (or textura (grafica-atlas grafica)))
      (lwlgl.opengl:gl-draw-arrays lwlgl.opengl:+gl-triangles+ 0 (/ (length vertices) 8))
      (setf (fill-pointer vertices) 0))))
(defun recortar (grafica x y largura altura)
  (descarregar grafica)
  (lwlgl.opengl:gl-enable lwlgl.opengl:+gl-scissor-test+)
  (lwlgl.opengl:gl-scissor (round x) (max 0 (round (- (grafica-altura grafica) y altura)))
                          (max 0 (round largura)) (max 0 (round altura))))
(defun terminar-recorte (grafica)
  (descarregar grafica) (lwlgl.opengl:gl-disable lwlgl.opengl:+gl-scissor-test+))
(defun barra (grafica x y largura altura valor maximo cor)
  (retangulo grafica x y largura altura '(0.08 0.10 0.14 1.0))
  (retangulo grafica x y (* largura (max 0 (min 1 (/ valor (max 1 maximo))))) altura cor))
(defun resumo-progressao (heroi)
  (let ((marco (proximo-marco heroi)))
    (if marco
        (format nil "Faltam ~D XP: ~A" (- (first marco) (heroi-xp heroi)) (nome-conhecimento (second marco)))
        "Todos os pontos desta fatia recebidos")))
(defun desenhar-guia (grafica sessao x y largura altura)
  (retangulo grafica x y largura altura '(0.07 0.105 0.15 1.0))
  (texto grafica "GRIMÓRIO / GUIA DE JOGO" (+ x 18) (+ y 14) *cor-dourada*)
  (texto grafica "F8 editor  |  F7 copiar exemplo  |  Roda: rolar" (+ x 18) (+ y 38) *cor-suave*)
  (let* ((heroi (mundo-heroi (mundo-ativo sessao)))
         (colunas (max 1 (floor (- largura 40) 10)))
         (linhas (loop for linha in (linhas-do-guia heroi (biblioteca-ativa sessao)) append
                   (if (zerop (length linha)) (list "")
                       (loop for inicio from 0 below (length linha) by colunas
                             collect (subseq linha inicio (min (length linha) (+ inicio colunas)))))))
         (visiveis (max 1 (floor (- altura 92) 22))))
    (setf (grafica-rolagem-guia grafica)
          (max 0 (min (grafica-rolagem-guia grafica) (- (length linhas) visiveis))))
    (recortar grafica (+ x 18) (+ y 72) (- largura 36) (- altura 88))
    (loop for linha in (nthcdr (grafica-rolagem-guia grafica) linhas)
          for indice from 0 below visiveis do
            (texto grafica linha (+ x 18) (+ y 72 (* indice 22))
                   (if (or (search "[LIBERADO]" linha) (search "EXEMPLO" linha)) *cor-verde* *cor-texto*)))
    (terminar-recorte grafica)))
(defun sprite (grafica animacao x y tempo escala &optional espelhar quadro-fixo)
  (when animacao
    (unless (animacao-textura animacao)
      (lwlgl.stb:with-image (png (animacao-arquivo animacao) :channels 4)
        (setf (animacao-textura animacao)
              (lwlgl.opengl:create-texture-2d (lwlgl.stb:image-width png) (lwlgl.stb:image-height png)
                (lwlgl.stb:image-pixels png) :min-filter lwlgl.opengl:+gl-nearest+ :mag-filter lwlgl.opengl:+gl-nearest+))))
    (descarregar grafica)
    (let* (;; Personagens têm dois pixels de arte por unidade do mapa.
           (escala (if (= (animacao-largura animacao) 64) (/ escala 2) escala))
           (quantidade (animacao-quadros animacao))
           (indice (floor (* tempo 1000) (animacao-duracao animacao)))
           (quadro (or quadro-fixo (if (animacao-repeticao animacao) (mod indice quantidade) (min indice (1- quantidade)))))
           (u (/ quadro quantidade)) (uf (/ (1+ quadro) quantidade)))
      (quadrilatero grafica (- x (* escala (first (animacao-pivo animacao))))
                            (- y (* escala (second (animacao-pivo animacao))))
                            (* escala (animacao-largura animacao)) (* escala (animacao-altura animacao))
                            '(1.0 1.0 1.0 1.0) (if espelhar uf u) 0 (if espelhar u uf) 1)
      (descarregar grafica (animacao-textura animacao)))))
(defun desenhar-mundo (grafica mundo animacoes x y largura altura)
  (let* ((escala (max 1 (min (floor largura 480) (floor altura 270))))
         (x (+ x (max 0 (floor (- largura (* escala 480)) 2))))
         (y (+ y (max 0 (floor (- altura (* escala 270)) 2))))
         (heroi (mundo-heroi mundo)) (camera (max 0 (min 960 (- (heroi-x heroi) 240))))
         (tempo (* (mundo-tick mundo) +passo+)))
    (recortar grafica x y (min largura (* escala 480)) (min altura (* escala 270)))
    (let ((deslocamento (mod (floor camera 4) 480)))
      (sprite grafica (gethash "cenario/idle" animacoes) (- x (* escala deslocamento)) y 0 escala)
      (sprite grafica (gethash "cenario/idle" animacoes) (+ x (* escala (- 480 deslocamento))) y 0 escala))
    (dolist (plataforma (mundo-plataformas mundo))
      (destructuring-bind (px py comprimento profundidade id) plataforma
        (declare (ignore id))
        (loop for tx from px below (+ px comprimento) by 16 do
          (loop for ty from py below (+ py profundidade) by 16 do
            (sprite grafica (gethash "terreno/idle" animacoes) (+ x (* escala (- tx camera)))
                    (+ y (* escala ty)) 0 escala nil
                    (if (some (lambda (p)
                                (and (<= (first p) tx) (< tx (+ (first p) (third p)))
                                     (<= (second p) (1- ty)) (< (1- ty) (+ (second p) (fourth p)))))
                              (mundo-plataformas mundo)) 1 0))))))
    (loop for tx from 656 below 768 by 16 do
      (sprite grafica (gethash "agua/idle" animacoes) (+ x (* escala (- tx camera)))
              (+ y (* escala 230)) tempo escala))
    (dolist (entidade (mundo-entidades mundo))
      (when (or (plusp (entidade-hp entidade))
                (and (eq (entidade-animacao entidade) :death)
                     (< (entidade-tempo-animacao entidade) 0.9)))
        (sprite grafica
                (gethash (if (eq (entidade-tipo entidade) :wood)
                             "madeira/idle"
                             (format nil "slime/~(~A~)" (entidade-animacao entidade)))
                         animacoes)
                (+ x (* escala (- (entidade-x entidade) camera))) (+ y (* escala (entidade-y entidade)))
                (entidade-tempo-animacao entidade) escala)
        (when (and (eq (entidade-tipo entidade) :slime) (plusp (entidade-hp entidade)))
          (barra grafica (+ x (* escala (- (entidade-x entidade) camera 12)))
                 (+ y (* escala (- (entidade-y entidade) 32)))
                 (* escala 24) (* escala 2) (entidade-hp entidade) 35 *cor-erro*)
          (when (entidade-molhada entidade)
            (texto grafica "MOLHADO" (+ x (* escala (- (entidade-x entidade) camera)) -35)
                   (+ y (* escala (- (entidade-y entidade) 44))) '(0.45 0.80 0.95 1.0))))))
    (sprite grafica (gethash (format nil "~A/~(~A~)"
                                    (if (eq (heroi-classe heroi) :fighter) "guerreiro" "mago")
                                    (if (plusp (heroi-ferimento heroi)) :hurt (heroi-estado heroi)))
                             animacoes)
            (+ x (* escala (- (heroi-x heroi) camera))) (+ y (* escala (heroi-y heroi)))
            (cond ((eq (heroi-estado heroi) :death) (- 3 (heroi-morte heroi)))
                  ((plusp (heroi-ferimento heroi)) (- 0.4 (heroi-ferimento heroi)))
                  (t (heroi-tempo-animacao heroi)))
            escala (minusp (heroi-direcao heroi)))
    (dolist (efeito (mundo-efeitos mundo))
      (if (stringp (getf efeito :tipo))
          (sprite grafica
              (gethash (format nil "magia/~A" (getf efeito :tipo)) animacoes)
              (+ x (* escala (- (getf efeito :x) camera)))
              (+ y (* escala (getf efeito :y)))
              (getf efeito :tempo) escala)
          (let* ((tipo (getf efeito :tipo))
                 (cadeia (case tipo (:xp (format nil "+~D XP" (getf efeito :valor)))
                           (:fizzle "FIZZLE") (t (format nil "-~D" (getf efeito :valor)))))
                 (cor (case tipo (:xp *cor-dourada*) (:ferimento *cor-erro*)
                        (:fizzle '(0.74 0.63 0.84 1.0)) (t *cor-texto*))))
            (texto grafica cadeia (+ x (* escala (- (getf efeito :x) camera)) (* -5 (length cadeia)))
                   (+ y (* escala (- (getf efeito :y) (* 12 (getf efeito :tempo))))) cor))))
  (terminar-recorte grafica)))
(defun texto-quebrado (grafica cadeia x y colunas &optional (cor *cor-texto*) (limite 5))
  (loop for inicio from 0 below (length cadeia) by (max 1 colunas) for linha from 0 below limite do
    (texto grafica (subseq cadeia inicio (min (length cadeia) (+ inicio (max 1 colunas)))) x (+ y (* linha 20)) cor)))
(defun termo-no-idioma (termo idioma)
  (let ((entrada (assoc termo *vocabulario* :test #'equal)))
    (if (and entrada (eq idioma :pt)) (or (second entrada) termo) termo)))
(defun expressao-diagnostica (expressao idioma &optional vinculadas)
  (cond ((null expressao) "()")
        ((consp expressao)
         (if (equal (first expressao) "exists")
             (format nil "(~A (~A ~A) ~A)" (termo-no-idioma "exists" idioma)
                     (first (second expressao)) (termo-no-idioma (second (second expressao)) idioma)
                     (expressao-diagnostica (third expressao) idioma (cons (first (second expressao)) vinculadas)))
             (format nil "(~{~A~^ ~})"
                     (mapcar (lambda (parte) (expressao-diagnostica parte idioma vinculadas)) expressao))))
        ((stringp expressao) (if (member expressao vinculadas :test #'equal) expressao
                                (termo-no-idioma expressao idioma)))
        (t (princ-to-string expressao))))
(defun linhas-diagnostico (sessao mundo intencao idioma)
  (let ((linhas nil))
    (labels ((adicionar (texto) (push texto linhas))
             (prova (rastro idioma)
               (dolist (no rastro)
                 (adicionar
                  (format nil "~V@T~A -> ~A" (* 2 (getf no :profundidade 0))
                          (if (eq (getf no :axioma) :fato) (if (eq idioma :en) "FACT" "FATO")
                              (termo-no-idioma (getf no :axioma) idioma))
                          (expressao-diagnostica (getf no :objetivo) idioma))))))
      (when (and intencao (intencao-prova intencao))
        (prova (intencao-prova intencao) idioma))
      (dolist (detalhe (and (mundo-ultimo-resultado mundo)
                           (resultado-detalhes (mundo-ultimo-resultado mundo))))
        (let* ((dados (cddr detalhe))
               (idioma-forma (if (eq (sessao-idioma sessao) :auto) (getf dados :idioma :pt) idioma)))
          (adicionar (format nil "~A: ~A" (first detalhe) (traduzir-motivo (second detalhe) idioma-forma)))
          (when (getf dados :premissa)
            (adicionar (expressao-diagnostica (getf dados :premissa) idioma-forma)))
          (when (and (getf dados :prova) (not (eq (second detalhe) :justificado)))
            (adicionar (format nil "~D ~A | ~D mana | ~,2F s" (getf dados :passos)
                               (if (eq idioma-forma :en) "steps" "passos")
                               (getf dados :mana) (getf dados :duracao)))
            (prova (getf dados :prova) idioma-forma)))))
    (nreverse linhas)))
(defun desenhar-editor (grafica editor x y largura altura)
  (retangulo grafica x y largura altura '(0.07 0.105 0.15 1.0))
  (texto grafica "BIBLIOTECA DE TEOREMAS" (+ x 18) (+ y 14) *cor-verde*)
  (texto grafica (if (editor-sujo editor) "Alterações não aplicadas" "Biblioteca ativa") (+ x 18) (+ y 38) *cor-suave*)
  (let* ((texto-editor (editor-texto editor)) (topo (+ y 76))
         (linhas-visiveis (max 1 (floor (- altura 130) 22))) (par nil) (par-outro nil))
    (multiple-value-setq (par par-outro) (par-correspondente texto-editor (editor-cursor editor)))
    (multiple-value-bind (linha coluna) (linha-coluna texto-editor (editor-cursor editor))
      (when (< linha (editor-rolagem editor)) (setf (editor-rolagem editor) linha))
      (when (>= linha (+ (editor-rolagem editor) linhas-visiveis)) (setf (editor-rolagem editor) (- linha linhas-visiveis -1)))
      (let ((colunas (max 10 (floor (- largura 85) 10))))
        (when (< coluna (editor-coluna-rolagem editor)) (setf (editor-coluna-rolagem editor) coluna))
        (when (>= coluna (+ (editor-coluna-rolagem editor) colunas))
          (setf (editor-coluna-rolagem editor) (- coluna colunas -1)))))
    (recortar grafica x topo largura (* linhas-visiveis 22))
    (multiple-value-bind (selecao-inicio selecao-fim) (limites-selecao editor)
      (loop with inicio = 0 for linha from 0
            for fim = (or (position #\Newline texto-editor :start inicio) (length texto-editor)) do
        (when (<= (editor-rolagem editor) linha (+ (editor-rolagem editor) linhas-visiveis -1))
          (let ((py (+ topo (* (- linha (editor-rolagem editor)) 22))) (comentario nil) (chave nil))
            (texto grafica (format nil "~3D" (1+ linha)) (+ x 8) py *cor-suave*)
            (loop for indice from inicio below fim for coluna from 0
                  for c = (char texto-editor indice) do
              (when (char= c #\;) (setf comentario t))
              (when (char= c #\:) (setf chave t))
              (when (find c '(#\Space #\Tab #\( #\))) (setf chave nil))
              (when (>= coluna (editor-coluna-rolagem editor))
                (let ((px (+ x 54 (* (- coluna (editor-coluna-rolagem editor)) 10))))
                  (when (<= selecao-inicio indice (1- selecao-fim))
                    (retangulo grafica px py 10 22 '(0.18 0.30 0.39 1.0)))
                  (when (and par-outro (or (= indice par) (= indice par-outro)))
                    (retangulo grafica px py 10 22 '(0.28 0.32 0.24 1.0)))
                  (texto grafica (string c) px py (cond (comentario *cor-suave*) (chave *cor-verde*)
                                                       ((find c "()") *cor-dourada*) (t *cor-texto*))))))
            (when (<= inicio (editor-cursor editor) fim)
              (retangulo grafica (+ x 54 (* (- (editor-cursor editor) inicio (editor-coluna-rolagem editor)) 10))
                          py 2 20 *cor-verde*))))
        (when (= fim (length texto-editor)) (return))
        (setf inicio (1+ fim))))
    (terminar-recorte grafica))
  (recortar grafica (+ x 14) (+ y altura -47) (- largura 28) 44)
  (texto-quebrado grafica (or (editor-erro editor) (editor-mensagem editor)) (+ x 14) (+ y altura -47)
                  (floor (- largura 28) 10) (if (editor-erro editor) *cor-erro* *cor-suave*) 2)
  (terminar-recorte grafica))
(defun desenhar-interface (grafica sessao editor animacoes pendencias)
  (let* ((largura (grafica-largura grafica)) (altura (grafica-altura grafica))
         (divisao (floor (* largura 0.47))) (mundo (mundo-ativo sessao)) (heroi (mundo-heroi mundo))
         (resultado (mundo-ultimo-resultado mundo)) (execucao (heroi-acao heroi))
         (intencao (and execucao (execucao-intencao execucao)))
         (idioma (if (eq (sessao-idioma sessao) :auto) (if intencao (intencao-idioma intencao) :pt) (sessao-idioma sessao))))
    (lwlgl.opengl:gl-clear-color 0.045 0.07 0.105 1.0)
    (lwlgl.opengl:gl-clear lwlgl.opengl:+gl-color-buffer-bit+)
    (retangulo grafica 0 0 largura 86 '(0.08 0.12 0.16 1.0))
    (texto grafica "Q E D" 24 14 *cor-dourada*)
    (texto grafica "Toda ação começa com uma justificativa." 24 42 *cor-suave*)
    (texto grafica (format nil "~A  |  ~A" (if (eq (heroi-classe heroi) :fighter) "GUERREIRO / regras" "MAGO / provas")
                          (if (sessao-pausada sessao) "PAUSADO" "EM EXECUÇÃO")) (+ divisao 20) 20 *cor-verde*)
    (texto grafica "F1 classe  F2 pausa  F4 mundo  F6 ontologia  F8 guia" (+ divisao 20) 48 *cor-suave*)
    (when (grafica-ontologia grafica)
      (desenhar-ontologia grafica sessao)
      (return-from desenhar-interface))
    (when (and (grafica-mundo-ampliado grafica) (not (grafica-guia grafica)) (null pendencias))
      (loop for rotulo in (list (format nil "VIDA ~D/~D" (round (heroi-hp heroi)) (heroi-hp-max heroi))
                               (format nil "MANA ~D/~D" (round (heroi-mana heroi)) (heroi-mana-max heroi))
                               (format nil "XP ~D | SLOTS ~D" (heroi-xp heroi) (heroi-slots heroi))
                               (format nil "MADEIRA ~D" (heroi-madeira heroi)))
            for indice from 0 for px = (+ 24 (* indice (floor (- largura 48) 4))) do
              (texto grafica rotulo px 98)
              (when (< indice 2)
                (barra grafica px 122 160 5
                       (if (zerop indice) (heroi-hp heroi) (heroi-mana heroi))
                       (if (zerop indice) (heroi-hp-max heroi) (heroi-mana-max heroi))
                       (if (zerop indice) *cor-erro* '(0.45 0.74 0.90 1.0)))))
      (desenhar-mundo grafica mundo animacoes 0 140 largura (- altura 228))
      (recortar grafica 24 (- altura 88) (- largura 48) 44)
      (texto grafica (format nil "~A  |  ~A" (if intencao (intencao-nome intencao) "Ocioso")
                            (resumo-progressao heroi)) 24 (- altura 86) *cor-verde*)
      (when (mundo-eventos mundo)
        (texto grafica (traduzir-evento (first (mundo-eventos mundo)) (sessao-idioma sessao))
               24 (- altura 64) *cor-dourada*))
      (terminar-recorte grafica)
      (texto grafica "F4 volta ao editor  |  F1 alterna personagem  |  F2 pausa" 24 (- altura 32) *cor-suave*)
      (descarregar grafica)
      (return-from desenhar-interface))
    (recortar grafica 20 98 (- divisao 40) (- altura 155))
    (sprite grafica (gethash "icones/idle" animacoes) 24 104 0 1 nil 1)
    (texto grafica (format nil "VIDA ~D/100" (round (heroi-hp heroi))) 46 104)
    (sprite grafica (gethash "icones/idle" animacoes) 212 104 0 1 nil 2)
    (texto grafica (format nil "MANA ~D/80" (round (heroi-mana heroi))) 234 104)
    (sprite grafica (gethash "icones/idle" animacoes) 390 104 0 1 nil 3)
    (texto grafica (format nil "XP ~D" (heroi-xp heroi)) 412 104)
    (texto grafica (format nil "Madeira ~D   Slots ~D   Posição ~D,~D" (heroi-madeira heroi) (heroi-slots heroi)
                          (round (heroi-x heroi)) (round (heroi-y heroi))) 24 130 *cor-suave*)
    (texto grafica (format nil "~D ponto~:P de conhecimento | F6 ontologia" (pontos-conhecimento heroi)) 24 148 *cor-dourada*)
    (retangulo grafica 24 166 (- divisao 48) 240 '(0.065 0.095 0.13 1.0))
    (if pendencias
        (progn
          (texto grafica "O mundo aguarda sua pixel art" 44 190 *cor-dourada*)
          (texto-quebrado grafica "A simulação está ativa. Os sprites finais serão integrados após sua exportação no Aseprite/Pixelorama."
                          44 226 (floor (- divisao 88) 10) *cor-suave* 4)
          (texto grafica (format nil "~D exports pendentes — guia em documentacao/" (length pendencias)) 44 326 *cor-suave*)
          (texto grafica (format nil "Estado do autômato: ~A"
                                 (string-left-trim ":" (termo-no-idioma
                                     (format nil ":~(~A~)" (heroi-estado heroi)) idioma))) 44 362 *cor-verde*))
        (progn (terminar-recorte grafica)
               (desenhar-mundo grafica mundo animacoes 24 166 (- divisao 48) 270)
               (recortar grafica 20 98 (- divisao 40) (- altura 155))))
    (let ((topo (if pendencias 428 452)))
      (texto grafica (if (eq (heroi-classe heroi) :fighter) "REGRA ATIVA" "TENTATIVA DE PROVA") 24 topo *cor-verde*)
      (texto grafica (if intencao (intencao-nome intencao) "Autômato ocioso") 24 (+ topo 28) *cor-dourada*)
      (texto grafica (traduzir-motivo (if intencao :justificado (if resultado (resultado-motivo resultado) :nenhuma-correspondencia)) idioma)
             24 (+ topo 52))
      (when (and intencao (eq (heroi-classe heroi) :wizard))
        (texto grafica (format nil "~D passos  |  ~D mana  |  ~,2F s" (intencao-passos intencao) (intencao-mana intencao)
                              (intencao-duracao intencao)) 24 (+ topo 78) *cor-suave*))
      (let* ((colunas (max 1 (floor (- divisao 48) 10)))
             (linhas (loop for linha in (linhas-diagnostico sessao mundo intencao idioma) append
                       (loop for inicio from 0 below (length linha) by colunas
                             collect (subseq linha inicio (min (length linha) (+ inicio colunas))))))
             (visiveis (max 1 (floor (- altura topo 248) 22))))
        (setf (grafica-rolagem-diagnostico grafica)
              (max 0 (min (grafica-rolagem-diagnostico grafica) (- (length linhas) visiveis))))
        (loop for linha in (nthcdr (grafica-rolagem-diagnostico grafica) linhas)
              for indice from 0 below visiveis do
                (texto grafica linha 24 (+ topo 110 (* indice 22)) *cor-suave*))
        (when (> (length linhas) visiveis)
          (texto grafica (if (eq idioma :en) "Scroll here for the full proof" "Role aqui para ler o diagnóstico completo")
                 24 (- altura 144) *cor-verde*)))
      (when (mundo-eventos mundo)
        (texto-quebrado grafica (traduzir-evento (first (mundo-eventos mundo)) (sessao-idioma sessao)) 24 (- altura 118)
                        (floor (- divisao 48) 10) *cor-dourada* 2)))
    (terminar-recorte grafica)
    (if (grafica-guia grafica)
        (desenhar-guia grafica sessao divisao 98 (- largura divisao 18) (- altura 155))
        (desenhar-editor grafica editor divisao 98 (- largura divisao 18) (- altura 155)))
    (retangulo grafica 0 (- altura 42) largura 42 '(0.08 0.12 0.16 1.0))
    (texto grafica "Ctrl+Enter aplicar  |  Ctrl+S salvar  |  Ctrl+Z desfazer  |  Ctrl+Y refazer  |  Esc sair" 24 (- altura 32) *cor-suave*)
    (descarregar grafica)))
