(in-package #:qed.aplicativo)

(defun capturar-quadro (grafica caminho)
  "Grava o framebuffer em PPM, sem alterar imagens ou produzir assets do jogo."
  (let* ((largura (grafica-largura grafica)) (altura (grafica-altura grafica)) (tamanho (* largura altura 3)))
    (ensure-directories-exist caminho)
    (cffi:with-foreign-object (pixels :unsigned-char tamanho)
      (lwlgl.opengl:gl-pixel-storei lwlgl.opengl:+gl-pack-alignment+ 1)
      (lwlgl.opengl:gl-read-pixels 0 0 largura altura lwlgl.opengl:+gl-rgb+ lwlgl.opengl:+gl-unsigned-byte+ pixels)
      (with-open-file (fluxo caminho :direction :output :element-type '(unsigned-byte 8) :if-exists :supersede)
        (loop for caractere across (format nil "P6~%~D ~D~%255~%" largura altura) do (write-byte (char-code caractere) fluxo))
        (loop for linha downfrom (1- altura) to 0 do
          (dotimes (coluna (* largura 3)) (write-byte (cffi:mem-aref pixels :unsigned-char (+ (* linha largura 3) coluna)) fluxo)))))))
(defun tratar-tecla (editor sessao janela tecla modificadores)
  (let ((controle (not (zerop (logand modificadores lwlgl.glfw:mod-control))))
        (selecionar (not (zerop (logand modificadores lwlgl.glfw:mod-shift)))))
    (cond
      ((and controle (= tecla lwlgl.glfw:key-enter)) (aplicar-editor editor sessao))
      ((and controle (= tecla lwlgl.glfw:key-a)) (setf (editor-ancora editor) 0 (editor-cursor editor) (length (editor-texto editor))))
      ((and controle (= tecla lwlgl.glfw:key-c)) (lwlgl.glfw:set-clipboard-string janela (texto-selecionado editor)))
      ((and controle (= tecla lwlgl.glfw:key-x)) (lwlgl.glfw:set-clipboard-string janela (texto-selecionado editor)) (substituir-selecao editor ""))
      ((and controle (= tecla lwlgl.glfw:key-v)) (substituir-selecao editor (or (lwlgl.glfw:clipboard-string janela) "")))
      ((and controle (= tecla lwlgl.glfw:key-z)) (desfazer-edicao editor selecionar))
      ((and controle (= tecla lwlgl.glfw:key-y)) (desfazer-edicao editor t))
      ((= tecla lwlgl.glfw:key-backspace) (apagar-editor editor))
      ((= tecla lwlgl.glfw:key-delete) (apagar-editor editor t))
      ((= tecla lwlgl.glfw:key-left) (mover-cursor editor (1- (editor-cursor editor)) selecionar))
      ((= tecla lwlgl.glfw:key-right) (mover-cursor editor (1+ (editor-cursor editor)) selecionar))
      ((= tecla lwlgl.glfw:key-up) (mover-vertical editor -1 selecionar))
      ((= tecla lwlgl.glfw:key-down) (mover-vertical editor 1 selecionar))
      ((= tecla lwlgl.glfw:key-page-up) (mover-vertical editor -15 selecionar))
      ((= tecla lwlgl.glfw:key-page-down) (mover-vertical editor 15 selecionar))
      ((or (= tecla lwlgl.glfw:key-home) (= tecla lwlgl.glfw:key-end))
       (multiple-value-bind (linha coluna) (linha-coluna (editor-texto editor) (editor-cursor editor))
         (declare (ignore coluna))
         (mover-cursor editor (if controle (if (= tecla lwlgl.glfw:key-home) 0 (length (editor-texto editor)))
                                 (posicao-linha (editor-texto editor) linha (if (= tecla lwlgl.glfw:key-home) 0 65536))) selecionar)))
      ((= tecla lwlgl.glfw:key-enter) (substituir-selecao editor (string #\Newline)))
      ((= tecla lwlgl.glfw:key-tab) (substituir-selecao editor "  ")))))
(defun testar-interface ()
  (assert (equal "(estado :ocioso)" (expressao-diagnostica '("state" ":idle") :pt)))
  (assert (equal "(state :idle)" (expressao-diagnostica '("state" ":idle") :en)))
  (assert (equal "(existe (state recurso) (tipo-recurso state :madeira))"
                 (expressao-diagnostica '("exists" ("state" "resource") ("resource-type" "state" ":wood")) :pt)))
  (let* ((grafica (criar-grafica)) (sessao (nova-sessao))
         (heroi (mundo-heroi (mundo-ativo sessao))))
    (selecionar-area grafica heroi 0 -1)
    (assert (equal "existencia" (grafica-area-selecionada grafica)))
    (selecionar-area grafica heroi 0 1)
    (assert (equal "materia" (grafica-area-selecionada grafica)))
    (selecionar-area grafica heroi 1 0)
    (assert (equal "conflito" (grafica-area-selecionada grafica)))
    (selecionar-area grafica heroi 0 1)
    (assert (equal "impacto" (grafica-area-selecionada grafica)))
    (selecionar-area grafica heroi 1 0)
    (assert (equal "impacto" (grafica-area-selecionada grafica)))
    (selecionar-area grafica heroi -1 0)
    (assert (equal "estados" (grafica-area-selecionada grafica)))
    (setf (grafica-regioes-navegacao grafica) '((:ontologia 10 10 100 40)))
    (assert (eq :ontologia (comando-navegacao-no-ponto grafica 50 30)))
    (assert (null (comando-navegacao-no-ponto grafica 50 60)))
    (dolist (tela '(:ontologia :acampamento :guia :mundo :teoremas))
      (acionar-navegacao grafica sessao tela)
      (assert (eq tela (tela-atual grafica)))
      (assert (eq (eq tela :teoremas) (editor-visivel-p grafica))))
    (acionar-navegacao grafica sessao :pausa)
    (assert (sessao-pausada sessao))
    (acionar-navegacao grafica sessao :pausa)
    (assert (not (sessao-pausada sessao)))
    (format t "Interface: navegação espacial, limites, cliques, telas e pausa verificados.~%"))
  (let ((editor (novo-editor "ação")))
    (mover-cursor editor 4 nil) (substituir-selecao editor " hipótese")
    (assert (equal (editor-texto editor) "ação hipótese"))
    (desfazer-edicao editor) (assert (equal (editor-texto editor) "ação"))
    (desfazer-edicao editor t) (assert (equal (editor-texto editor) "ação hipótese"))
    (mover-cursor editor 0 nil) (mover-cursor editor 4 t)
    (assert (equal (texto-selecionado editor) "ação"))
    (substituir-selecao editor "prova")
    (assert (equal (editor-texto editor) "prova hipótese"))
    (format t "Editor: seleção Unicode, desfazer e refazer verificados.~%")))

(defun executar (&key quadros duracao oculta captura (salvar t) ensaio ensaio-real mundo-ampliado ontologia
                      acampamento posicao-inicial (largura-inicial 1440) (altura-inicial 900))
  (let* ((lwlgl.glfw:*glfw-platform-preference* (if (uiop:getenv "DISPLAY") :x11 :auto))
         (aviso nil)
         (sessao (if (and salvar (probe-file (salvo-padrao)))
                     (handler-case (multiple-value-bind (sessao recuperacao) (carregar-partida)
                                     (setf aviso recuperacao) sessao)
                       (error (erro) (setf salvar nil aviso (format nil "Progresso não carregado; gravação desativada: ~A" erro)) (nova-sessao)))
                     (nova-sessao)))
         (editores (map 'vector (lambda (rascunho biblioteca)
                                  (let ((editor (novo-editor rascunho)))
                                    (setf (editor-sujo editor) (not (equal rascunho (biblioteca-texto biblioteca)))) editor))
                         (sessao-rascunhos sessao) (sessao-bibliotecas sessao))))
    (when posicao-inicial
      (let* ((mundo (mundo-ativo sessao)) (heroi (mundo-heroi mundo))
             (x (max 12 (min (- (mundo-largura mundo) 12) posicao-inicial))))
        (setf (heroi-x heroi) x (heroi-y heroi) (altura-chao mundo x)
              (heroi-vx heroi) 0 (heroi-vy heroi) 0)))
    (when aviso (setf (editor-mensagem (aref editores (sessao-ativa sessao))) aviso))
    (multiple-value-bind (animacoes pendencias) (validar-assets)
      (lwlgl.glfw:with-glfw ()
        (lwlgl.glfw:default-window-hints)
        (lwlgl.glfw:window-hint lwlgl.glfw:context-version-major 3)
        (lwlgl.glfw:window-hint lwlgl.glfw:context-version-minor 3)
        (lwlgl.glfw:window-hint lwlgl.glfw:opengl-profile lwlgl.glfw:opengl-core-profile)
        (when oculta (lwlgl.glfw:window-hint lwlgl.glfw:visible lwlgl.glfw:false))
        (lwlgl.glfw:with-window (janela largura-inicial altura-inicial "QED — prove, então aja")
          (lwlgl.glfw:make-context-current janela) (lwlgl.glfw:swap-interval (if oculta 0 1))
          (lwlgl.opengl:load-opengl :error-on-missing nil)
          (let ((grafica (iniciar-grafica)) (ultimo (lwlgl.glfw:get-time)) (acumulador 0.0d0)
                (contador 0) (arrastando nil) (ultimo-salvo 0) (inicio (lwlgl.glfw:get-time)) (etapa 0))
            (setf (grafica-mundo-ampliado grafica) mundo-ampliado
                  (grafica-ontologia grafica) ontologia
                  (grafica-acampamento grafica) acampamento)
            (unwind-protect
                 (labels
                     ((editor-atual () (aref editores (sessao-ativa sessao)))
                      (salvar-com-rascunhos ()
                        (setf (sessao-rascunhos sessao) (map 'vector #'editor-texto editores))
                        (salvar-partida sessao))
                      (copiar-exemplo ()
                        (let* ((heroi (mundo-heroi (mundo-ativo sessao)))
                               (area (buscar-area heroi (grafica-area-selecionada grafica))))
                          (lwlgl.glfw:set-clipboard-string janela
                            (if (and (grafica-ontologia grafica) area) (getf area :exemplo) (exemplo-do-guia heroi)))
                          (setf (grafica-mensagem-ontologia grafica) "Exemplo copiado. Volte ao editor para colar e aplicar."
                                (editor-mensagem (editor-atual)) "Exemplo copiado. Selecione onde inserir e use Ctrl+V.")))
                      (comprar-area ()
                        (when (comprar-area-selecionada grafica sessao)
                          (setf (editor-revisao-validada (editor-atual)) -1)))
                      (comprar-construcao ()
                        (when (comprar-construcao-selecionada grafica sessao)
                          (setf (editor-mensagem (editor-atual)) "Construção concluída e progresso salvo no próximo ciclo.")))
                      (atualizar-mouse ()
                        (multiple-value-bind (mx my) (lwlgl.glfw:cursor-position janela)
                          (multiple-value-bind (lj aj) (lwlgl.glfw:window-size janela)
                            (setf (grafica-mouse-x grafica) (* mx (/ (grafica-largura grafica) (max 1 lj)))
                                  (grafica-mouse-y grafica) (* my (/ (grafica-altura grafica) (max 1 aj)))))))
                      (posicionar-mouse ()
                        (multiple-value-bind (mx my) (lwlgl.glfw:cursor-position janela)
                          (multiple-value-bind (lj aj) (lwlgl.glfw:window-size janela)
                            (let* ((x (* mx (/ (grafica-largura grafica) (max 1 lj))))
                                   (y (* my (/ (grafica-altura grafica) (max 1 aj))))
                                   (divisao (floor (* (grafica-largura grafica) 0.47)))
                                   (editor (editor-atual)))
                              (when (and (editor-visivel-p grafica) (> x divisao) (> y 174) (< y (- (grafica-altura grafica) 100)))
                                (mover-cursor editor
                                  (posicao-linha (editor-texto editor)
                                                 (+ (editor-rolagem editor) (max 0 (floor (- y 174) 22)))
                                                 (+ (editor-coluna-rolagem editor) (max 0 (floor (- x divisao 54) 10))))
                                  arrastando)))))))
                   (lwlgl.glfw:set-char-handler janela
                     (lambda (janela codigo) (declare (ignore janela))
                       (when (and (editor-visivel-p grafica) (>= codigo 32) (code-char codigo))
                         (substituir-selecao (editor-atual) (string (code-char codigo))))))
                   (lwlgl.glfw:set-key-handler janela
                     (lambda (janela tecla codigo acao modificadores)
                       (declare (ignore codigo))
                       (when (member acao (list lwlgl.glfw:press lwlgl.glfw:repeat))
                         (handler-case
                             (cond ((= tecla lwlgl.glfw:key-escape) (lwlgl.glfw:set-window-should-close janela t))
                                   ((= tecla lwlgl.glfw:key-f1)
                                    (alternar-personagem sessao)
                                    (setf (grafica-area-selecionada grafica) "existencia"
                                          (grafica-rolagem-area grafica) 0
                                          (grafica-mensagem-ontologia grafica) "Selecione uma área para conhecer seu vocabulário."))
                                   ((= tecla lwlgl.glfw:key-f2) (setf (sessao-pausada sessao) (not (sessao-pausada sessao))))
                                   ((= tecla lwlgl.glfw:key-f3)
                                    (setf (sessao-idioma sessao) (case (sessao-idioma sessao) (:pt :en) (:en :auto) (t :pt))))
                                   ((= tecla lwlgl.glfw:key-f4)
                                    (mudar-tela grafica (if (eq (tela-atual grafica) :mundo) :teoremas :mundo)))
                                   ((= tecla lwlgl.glfw:key-f6)
                                    (mudar-tela grafica (if (eq (tela-atual grafica) :ontologia) :teoremas :ontologia)))
                                   ((= tecla lwlgl.glfw:key-f8)
                                    (mudar-tela grafica (if (eq (tela-atual grafica) :guia) :teoremas :guia)))
                                   ((= tecla lwlgl.glfw:key-f9)
                                    (mudar-tela grafica (if (eq (tela-atual grafica) :acampamento) :teoremas :acampamento)))
                                   ((and (= tecla lwlgl.glfw:key-f7) (or (grafica-guia grafica) (grafica-ontologia grafica)))
                                    (copiar-exemplo))
                                   ((= tecla lwlgl.glfw:key-f5)
                                    (multiple-value-bind (novas novas-pendencias) (validar-assets)
                                      (maphash
                                       (lambda (nome nova)
                                         (let ((anterior (gethash nome animacoes)))
                                           (when (and anterior (animacao-textura anterior))
                                             (lwlgl.opengl:delete-texture (animacao-textura anterior)))
                                           (setf (gethash nome animacoes) nova)))
                                       novas)
                                      (setf pendencias novas-pendencias)))
                                   ((and (= tecla lwlgl.glfw:key-s) (logtest modificadores lwlgl.glfw:mod-control))
                                    (when salvar (salvar-com-rascunhos))
                                    (setf (editor-mensagem (editor-atual)) "Progresso, biblioteca ativa e rascunhos salvos."))
                                   ((grafica-ontologia grafica)
                                    (cond ((= tecla lwlgl.glfw:key-enter) (comprar-area))
                                          ((= tecla lwlgl.glfw:key-left)
                                           (selecionar-area grafica (mundo-heroi (mundo-ativo sessao)) -1 0))
                                          ((= tecla lwlgl.glfw:key-right)
                                           (selecionar-area grafica (mundo-heroi (mundo-ativo sessao)) 1 0))
                                          ((= tecla lwlgl.glfw:key-up)
                                           (selecionar-area grafica (mundo-heroi (mundo-ativo sessao)) 0 -1))
                                          ((= tecla lwlgl.glfw:key-down)
                                           (selecionar-area grafica (mundo-heroi (mundo-ativo sessao)) 0 1))))
                                   ((grafica-acampamento grafica)
                                    (when (= tecla lwlgl.glfw:key-enter) (comprar-construcao)))
                                   ((editor-visivel-p grafica) (tratar-tecla (editor-atual) sessao janela tecla modificadores)))
                           (error (erro) (setf (editor-mensagem (editor-atual)) (princ-to-string erro)))))))
                   (lwlgl.glfw:set-mouse-button-handler janela
                     (lambda (janela botao acao modificadores) (declare (ignore janela modificadores))
                       (when (= botao lwlgl.glfw:mouse-button-left)
                         (setf arrastando nil)
                         (when (= acao lwlgl.glfw:press)
                           (atualizar-mouse)
                           (let* ((x (grafica-mouse-x grafica)) (y (grafica-mouse-y grafica))
                                  (navegacao (comando-navegacao-no-ponto grafica x y)))
                             (cond (navegacao (acionar-navegacao grafica sessao navegacao))
                                   ((grafica-ontologia grafica)
                                    (let ((comando (comando-ontologia-no-ponto grafica x y)))
                                      (cond ((eq comando :desbloquear) (comprar-area))
                                            ((eq comando :copiar) (copiar-exemplo))
                                            ((stringp comando)
                                             (setf (grafica-area-selecionada grafica) comando
                                                   (grafica-rolagem-area grafica) 0)))))
                                   ((grafica-acampamento grafica)
                                    (let ((comando (comando-acampamento-no-ponto grafica x y)))
                                      (cond ((eq comando :construir) (comprar-construcao))
                                            ((keywordp comando)
                                             (setf (grafica-construcao-selecionada grafica) comando
                                                   (grafica-mensagem-acampamento grafica)
                                                   "Requisitos e efeitos desta construção estão exibidos abaixo.")))))
                                   ((editor-visivel-p grafica) (posicionar-mouse) (setf arrastando t))))))))
                   (lwlgl.glfw:set-cursor-position-handler janela
                     (lambda (janela x y)
                       (declare (ignore janela x y))
                       (atualizar-mouse)
                       (when arrastando (posicionar-mouse))))
                   (lwlgl.glfw:set-scroll-handler janela
                     (lambda (janela x y)
                       (declare (ignore x))
                       (let ((mx (lwlgl.glfw:cursor-position janela)) (largura (lwlgl.glfw:window-size janela)))
                         (cond ((grafica-ontologia grafica)
                                (when (> mx (* largura 0.64))
                                  (incf (grafica-rolagem-area grafica) (- (round (* y 3))))))
                               ((or (grafica-mundo-ampliado grafica) (grafica-acampamento grafica)) nil)
                               ((< mx (* largura 0.47)) (incf (grafica-rolagem-diagnostico grafica) (- (round (* y 3)))))
                               ((grafica-guia grafica) (incf (grafica-rolagem-guia grafica) (- (round (* y 3)))))
                               (t (mover-vertical (editor-atual) (- (round (* y 3))) nil))))))
                   (when (or ensaio ensaio-real)
                     (testar-interface)
                     (let ((anterior (lwlgl.glfw:clipboard-string janela)))
                       (unwind-protect
                            (progn (lwlgl.glfw:set-clipboard-string janela "hipótese ação")
                                   (assert (equal (lwlgl.glfw:clipboard-string janela) "hipótese ação")))
                         (lwlgl.glfw:set-clipboard-string janela (or anterior "")))))
                   (loop until (lwlgl.glfw:window-should-close-p janela) do
                     (lwlgl.glfw:poll-events)
                     (let* ((agora (lwlgl.glfw:get-time)) (decorrido (- agora ultimo)))
                       (setf ultimo agora)
                       ;; Suspensão e pausas de depuração não são ganhos offline.
                       (when (< decorrido 2) (incf acumulador decorrido))
                       (loop repeat 120 while (>= acumulador +passo+) do
                         (avancar-sessao sessao) (decf acumulador +passo+)))
                     (when ensaio
                       (dotimes (indice 60) (declare (ignorable indice)) (avancar-sessao sessao))
                       (when (= contador 20) (alternar-personagem sessao))
                       (when (= contador 30) (lwlgl.glfw:set-window-size janela 1280 800))
                       (when (= contador 40) (lwlgl.glfw:hide-window janela))
                       (when (and (= contador 50) (not oculta)) (lwlgl.glfw:show-window janela)))
                     (when ensaio-real
                       (let ((decorrido (- (lwlgl.glfw:get-time) inicio)))
                         (cond ((and (= etapa 0) (> decorrido 3))
                                (mover-cursor (editor-atual) (length (editor-texto (editor-atual))) nil)
                                (substituir-selecao (editor-atual) (format nil "~%;; Ensaio prolongado: hipótese e ação.~%"))
                                (aplicar-editor (editor-atual) sessao) (incf etapa))
                               ((and (= etapa 1) (> decorrido 5)) (setf (sessao-pausada sessao) t) (incf etapa))
                               ((and (= etapa 2) (> decorrido 6)) (setf (sessao-pausada sessao) nil) (incf etapa))
                               ((and (= etapa 3) (> decorrido 10))
                                (alternar-personagem sessao) (lwlgl.glfw:set-window-size janela 1280 800) (incf etapa))
                               ((and (= etapa 4) (> decorrido 15)) (lwlgl.glfw:hide-window janela) (incf etapa)))))
                     (validar-editor (editor-atual) sessao)
                     (multiple-value-bind (largura altura) (lwlgl.glfw:framebuffer-size janela)
                       (when (and (plusp largura) (plusp altura))
                         (setf (grafica-largura grafica) largura (grafica-altura grafica) altura)
                         (lwlgl.opengl:gl-viewport 0 0 largura altura)
                         (desenhar-interface grafica sessao (editor-atual) animacoes pendencias)
                         (when (and captura (or (and quadros (= contador (1- quadros)))
                                                (and duracao (>= (- (lwlgl.glfw:get-time) inicio) duracao))))
                           (capturar-quadro grafica captura))
                         (lwlgl.glfw:swap-buffers janela)))
                     (when (and salvar (> (- (lwlgl.glfw:get-time) ultimo-salvo) 30))
                       (handler-case (progn (salvar-com-rascunhos) (setf ultimo-salvo (lwlgl.glfw:get-time)))
                         (error (erro) (setf (editor-mensagem (editor-atual)) (princ-to-string erro)))))
                     (incf contador)
                     (when (and oculta duracao) (sleep 0.015))
                     (when (or (and quadros (>= contador quadros)) (and duracao (>= (- (lwlgl.glfw:get-time) inicio) duracao)))
                       (lwlgl.glfw:set-window-should-close janela t)))
                   (when salvar (salvar-com-rascunhos))
                   (format t "Janela encerrada após ~D quadros e ~,2F segundos reais. ~D assets pendentes.~%"
                           contador (- (lwlgl.glfw:get-time) inicio) (length pendencias))
                   (loop for mundo across (sessao-mundos sessao) do (format t "~S~%" (estado-resumido mundo))))
              (encerrar-grafica grafica animacoes))))))))
