(in-package #:qed.aplicativo)

(defun dentro-retangulo-p (x y retangulo)
  (destructuring-bind (px py largura altura) retangulo
    (and (<= px x (+ px largura)) (<= py y (+ py altura)))))
(defun comando-ontologia-no-ponto (grafica x y)
  (loop for (comando . retangulo) in (grafica-regioes-ontologia grafica)
        when (dentro-retangulo-p x y retangulo) return comando))
(defun editor-visivel-p (grafica)
  (not (or (grafica-mundo-ampliado grafica) (grafica-guia grafica) (grafica-ontologia grafica))))
(defun selecionar-area (grafica heroi direcao-x direcao-y)
  "Move o foco na direção visual pedida, sem retornar pela borda oposta."
  (let* ((areas (areas-ontologia (heroi-classe heroi)))
         (atual (or (buscar-area heroi (grafica-area-selecionada grafica)) (first areas)))
         (origem (getf atual :posicao)) (melhor nil) (menor nil))
    (dolist (area areas)
      (let* ((posicao (getf area :posicao))
             (dx (- (first posicao) (first origem)))
             (dy (- (second posicao) (second origem)))
             (frente (+ (* dx direcao-x) (* dy direcao-y)))
             (lateral (abs (- (* dx direcao-y) (* dy direcao-x))))
             (distancia (+ (* dx dx) (* dy dy) (* 3 lateral lateral))))
        (when (and (plusp frente) (<= lateral frente)
                   (or (null menor) (< distancia menor)))
          (setf melhor area menor distancia))))
    (when melhor
      (setf (grafica-rolagem-area grafica) 0
            (grafica-area-selecionada grafica) (getf melhor :id)))))
(defun comprar-area-selecionada (grafica sessao)
  (multiple-value-bind (sucesso motivo)
      (desbloquear-area (mundo-ativo sessao) (grafica-area-selecionada grafica))
    (setf (grafica-mensagem-ontologia grafica)
          (if sucesso (format nil "~A liberada. Vocabulário disponível nos teoremas."
                              (getf (buscar-area (mundo-heroi (mundo-ativo sessao))
                                                (grafica-area-selecionada grafica)) :titulo))
              (case motivo (:liberada "Esta área já está liberada.")
                (:requisitos "Libere as áreas anteriores primeiro.")
                (:sem-pontos "Ganhe mais XP para receber pontos de conhecimento.")
                (t "Selecione uma área desta classe."))))
    sucesso))
(defun vocabulario-da-area (area heroi)
  (remove-if (lambda (termo)
               (and (eq (heroi-classe heroi) :fighter)
                    (member termo '("travel-law" "flee-law" "gather-law") :test #'equal)))
             (getf area :vocabulario)))
(defun contorno (grafica x y largura altura cor)
  (retangulo grafica x y largura 2 cor) (retangulo grafica x (+ y altura -2) largura 2 cor)
  (retangulo grafica x y 2 altura cor) (retangulo grafica (+ x largura -2) y 2 altura cor))
(defun quebrar-linhas-painel (cadeia colunas)
  (when (zerop (length cadeia)) (return-from quebrar-linhas-painel (list "")))
  (loop for linha in (uiop:split-string cadeia :separator '(#\Newline)) append
    (if (zerop (length linha)) (list "")
        (loop with inicio = 0 while (< inicio (length linha))
              for limite = (min (length linha) (+ inicio (max 1 colunas)))
              for espaco = (and (< limite (length linha))
                                (position #\Space linha :start inicio :end limite :from-end t))
              for fim = (if (and espaco (> espaco inicio)) espaco limite)
              collect (subseq linha inicio fim)
              do (setf inicio (if (and (< fim (length linha)) (char= (char linha fim) #\Space)) (1+ fim) fim))))))
(defun desenhar-ontologia (grafica sessao)
  (let* ((heroi (mundo-heroi (mundo-ativo sessao)))
         (largura (grafica-largura grafica)) (altura (grafica-altura grafica))
         (divisao (floor (* largura 0.64)))
         (areas (areas-ontologia (heroi-classe heroi)))
         (area (or (buscar-area heroi (grafica-area-selecionada grafica)) (first areas)))
         (largura-no (min 205 (floor (- divisao 80) 3)))
         (distancia-x (/ (- divisao largura-no 64) 2))
         (distancia-y (max 90 (min 138 (floor (- altura 280) 3))))
         (posicoes (make-hash-table :test 'equal)))
    (setf (grafica-area-selecionada grafica) (getf area :id)
          (grafica-regioes-ontologia grafica) nil)
    (painel-interface grafica "painel" 20 98 (- divisao 28) (- altura 152) :borda 18 :centro nil :escurecer 0.55)
    (texto grafica "ÁRVORE DE ONTOLOGIA" 44 116 *cor-dourada*)
    (texto grafica (format nil "~D XP  /  Pontos disponíveis: ~D"
                          (heroi-xp heroi) (pontos-conhecimento heroi)) 76 144 *cor-verde*)
    (imagem-interface grafica "conhecimento" 42 138 28 28)
    (texto grafica (resumo-progressao heroi) 44 172 *cor-suave*)
    (recortar grafica 22 192 (- divisao 32) (- altura 268))
    (dolist (item areas)
      (destructuring-bind (coluna linha) (getf item :posicao)
        (setf (gethash (getf item :id) posicoes)
              (list (+ 32 (* coluna distancia-x)) (+ 204 (* linha distancia-y)) largura-no 72))))
    ;; Ligações ficam atrás dos cartões; ramos longos passam pela margem.
    (dolist (item areas)
      (dolist (requisito (getf item :requisitos))
        (let* ((origem (gethash requisito posicoes)) (destino (gethash (getf item :id) posicoes))
               (sx (+ (first origem) (/ largura-no 2))) (sy (+ (second origem) 72))
               (dx (+ (first destino) (/ largura-no 2))) (dy (second destino))
               (cor (if (area-liberada-p heroi requisito) '(0.28 0.48 0.43 1.0) '(0.19 0.24 0.30 1.0))))
          (cond
            ((= (second origem) dy)
             (retangulo grafica (+ (first origem) largura-no) (+ dy 36)
                        (- (first destino) (first origem) largura-no) 2 cor))
            ((> (- dy sy) (* distancia-y 1.1))
             (retangulo grafica 26 (+ sy 8) (- sx 26) 2 cor)
             (retangulo grafica sx sy 2 10 cor)
             (retangulo grafica 26 (+ sy 8) 2 (- dy sy 16) cor)
             (retangulo grafica 26 (- dy 8) (- dx 26) 2 cor)
             (retangulo grafica dx (- dy 8) 2 8 cor))
            (t (let ((meio (floor (+ sy dy) 2)))
                 (retangulo grafica sx sy 2 (- meio sy) cor)
                 (retangulo grafica (min sx dx) meio (+ 2 (abs (- dx sx))) 2 cor)
                 (retangulo grafica dx meio 2 (- dy meio) cor)))))))
    (dolist (item areas)
      (let* ((id (getf item :id)) (situacao (situacao-area heroi id))
             (selecionada (equal id (getf area :id)))
             (cor (case situacao (:liberada *cor-verde*) (:disponivel *cor-dourada*) (t *cor-suave*)))
             (retangulo (gethash id posicoes)))
        (push (cons id retangulo) (grafica-regioes-ontologia grafica))
        (destructuring-bind (x y w h) retangulo
          (painel-interface grafica (cond (selecionada "selecionado")
                                          ((eq situacao :liberada) "liberado")
                                          ((eq situacao :disponivel) "botao") (t "bloqueado"))
                            x y w h :borda 12 :escurecer 0.3)
          (when selecionada (contorno grafica (+ x 2) (+ y 2) (- w 4) (- h 4) *cor-dourada*))
          (imagem-interface grafica id (+ x 10) (+ y 16) 40 40
                            (if (eq situacao :liberada) '(1.0 1.0 1.0 1.0) '(0.6 0.6 0.6 1.0)))
          (texto grafica (getf item :titulo) (+ x 58) (+ y 14) *cor-texto*)
          (texto grafica (case situacao (:liberada "Liberada") (:disponivel "1 ponto")
                          (:requisitos "Requisitos") (t "Sem pontos"))
                 (+ x 58) (+ y 40) cor))))
    (terminar-recorte grafica)
    (let* ((x (+ divisao 12)) (w (- largura divisao 36)) (colunas (max 1 (floor (- w 48) 10)))
           (situacao (situacao-area heroi (getf area :id)))
           (cor (if (eq situacao :liberada) *cor-verde* *cor-dourada*)))
      (painel-interface grafica "grimorio" x 98 w (- altura 152) :borda 20 :escurecer 0.55)
      (imagem-interface grafica (getf area :id) (+ x 20) 112 44 44)
      (texto grafica (getf area :titulo) (+ x 76) 122 cor)
      (recortar grafica (+ x 24) 170 (- w 48) (- altura 382))
      (let ((linha 0))
        (labels ((escrever (cadeia &optional (cor *cor-texto*))
                   (dolist (parte (quebrar-linhas-painel cadeia colunas))
                     (texto grafica parte (+ x 24) (+ 170 (* (- linha (grafica-rolagem-area grafica)) 20)) cor) (incf linha))))
          (escrever (getf area :descricao)) (escrever "")
          (escrever "REQUISITOS" *cor-suave*)
          (escrever (if (getf area :requisitos)
                        (format nil "~{~A~^, ~}" (mapcar (lambda (id) (getf (buscar-area heroi id) :titulo)) (getf area :requisitos)))
                        "Conhecimento inicial"))
          (escrever "") (escrever "VOCABULÁRIO" *cor-suave*)
          (escrever (format nil "~{~A~^, ~}" (vocabulario-da-area area heroi)) *cor-verde*)
          (escrever "") (escrever "EXEMPLO PARA O EDITOR" *cor-suave*)
          (escrever (getf area :exemplo) *cor-dourada*)
          (setf (grafica-rolagem-area grafica)
                (max 0 (min (grafica-rolagem-area grafica) (- linha (floor (- altura 382) 20)))))))
      (terminar-recorte grafica)
      (let ((botao (list (+ x 16) (- altura 194) (- w 32) 38)))
        (push (cons :desbloquear botao) (grafica-regioes-ontologia grafica))
        (apply #'painel-interface grafica (if (eq situacao :disponivel) "selecionado" "bloqueado")
               (append botao (list :borda 8)))
        (texto grafica (case situacao (:liberada "Área liberada") (:disponivel "Liberar: 1 ponto [Enter]")
                        (:requisitos "Requisitos pendentes") (t "Pontos insuficientes")) (+ x 28) (- altura 184) cor))
      (let ((botao (list (+ x 16) (- altura 146) (- w 32) 34)))
        (push (cons :copiar botao) (grafica-regioes-ontologia grafica))
        (apply #'painel-interface grafica "botao" (append botao (list :borda 8)))
        (texto grafica "Copiar exemplo [F7]" (+ x 28) (- altura 138) *cor-verde*))
      (texto-quebrado grafica (grafica-mensagem-ontologia grafica) (+ x 24) (- altura 102) colunas *cor-suave* 2))
    (painel-interface grafica "botao" 6 (- altura 42) (- largura 12) 38 :borda 8)
    (texto grafica "Clique ou use as setas  |  Enter libera  |  F6 volta  |  F1 alterna personagem" 24 (- altura 34) *cor-suave*)
    (descarregar grafica)))
