(in-package #:qed.aplicativo)

(defun arte-interface (grafica nome)
  (and (grafica-artes-interface grafica)
       (gethash (concatenate 'string "interface/" nome) (grafica-artes-interface grafica))))
(defun textura-interface (arte)
  (unless (animacao-textura arte)
    (lwlgl.stb:with-image (png (animacao-arquivo arte) :channels 4)
      (setf (animacao-textura arte)
            (lwlgl.opengl:create-texture-2d (lwlgl.stb:image-width png) (lwlgl.stb:image-height png)
              (lwlgl.stb:image-pixels png) :min-filter lwlgl.opengl:+gl-nearest+ :mag-filter lwlgl.opengl:+gl-nearest+))))
  (animacao-textura arte))
(defun imagem-interface (grafica nome x y largura altura &optional (cor '(1.0 1.0 1.0 1.0)))
  (let ((arte (arte-interface grafica nome)))
    (when arte
      (descarregar grafica)
      (quadrilatero grafica x y largura altura cor 0 0 1 1)
      (descarregar grafica (textura-interface arte)))))
(defun painel-interface (grafica nome x y largura altura &key (borda 20) (centro t) (escurecer 0))
  "Nove recortes: os cantos conservam proporção quando o painel muda de tamanho."
  (let ((arte (arte-interface grafica nome)))
    (if (null arte)
        (retangulo grafica x y largura altura '(0.05 0.08 0.12 1.0))
        (let* ((b (min borda (/ largura 2) (/ altura 2)))
               (xs (list x (+ x b) (+ x largura (- b)) (+ x largura)))
               (ys (list y (+ y b) (+ y altura (- b)) (+ y altura)))
               (uv '(0 1/8 7/8 1)))
          (descarregar grafica)
          (dotimes (linha 3)
            (dotimes (coluna 3)
              (when (or centro (/= linha 1) (/= coluna 1))
                (quadrilatero grafica (nth coluna xs) (nth linha ys)
                               (- (nth (1+ coluna) xs) (nth coluna xs))
                               (- (nth (1+ linha) ys) (nth linha ys)) '(1.0 1.0 1.0 1.0)
                               (nth coluna uv) (nth linha uv) (nth (1+ coluna) uv) (nth (1+ linha) uv)))))
          (descarregar grafica (textura-interface arte))
          (when (plusp escurecer)
            (retangulo grafica (+ x b) (+ y b) (- largura (* 2 b)) (- altura (* 2 b))
                       (list 0.025 0.04 0.06 escurecer)))))))
(defun texto-titulo (grafica cadeia x y)
  (let ((inicio (length (grafica-vertices grafica))))
    (texto grafica cadeia 0 0 *cor-dourada*)
    (loop for i from inicio below (length (grafica-vertices grafica)) by 8 do
      (setf (aref (grafica-vertices grafica) i) (coerce (+ x (* 2 (aref (grafica-vertices grafica) i))) 'single-float)
            (aref (grafica-vertices grafica) (1+ i)) (coerce (+ y (* 2 (aref (grafica-vertices grafica) (1+ i)))) 'single-float)))))
(defun tela-atual (grafica)
  (cond ((grafica-ontologia grafica) :ontologia) ((grafica-guia grafica) :guia)
        ((grafica-mundo-ampliado grafica) :mundo) (t :teoremas)))
(defun mudar-tela (grafica tela)
  (setf (grafica-ontologia grafica) (eq tela :ontologia)
        (grafica-guia grafica) (eq tela :guia)
        (grafica-mundo-ampliado grafica) (eq tela :mundo)))
(defun sob-mouse-p (grafica retangulo)
  (destructuring-bind (x y largura altura) retangulo
    (and (<= x (grafica-mouse-x grafica) (+ x largura))
         (<= y (grafica-mouse-y grafica) (+ y altura)))))
(defun comando-navegacao-no-ponto (grafica x y)
  (loop for (comando . retangulo) in (grafica-regioes-navegacao grafica)
        when (dentro-retangulo-p x y retangulo) return comando))
(defun acionar-navegacao (grafica sessao comando)
  (if (eq comando :pausa)
      (setf (sessao-pausada sessao) (not (sessao-pausada sessao)))
      (when (member comando '(:mundo :teoremas :ontologia :guia))
        (mudar-tela grafica comando))))
(defun desenhar-cabecalho (grafica sessao)
  (let* ((largura (grafica-largura grafica)) (inicio (floor (* largura 0.47)))
         (heroi (mundo-heroi (mundo-ativo sessao)))
         (guerreiro (eq (heroi-classe heroi) :fighter)))
    (painel-interface grafica "painel" 6 4 (- largura 12) 80 :borda 14 :escurecer 0.35)
    (imagem-interface grafica (if guerreiro "conflito" "afinidade") 24 16 54 54)
    (texto-titulo grafica "QED" 94 8)
    (texto grafica "A lógica move o mundo." 94 52 *cor-suave*)
    (texto grafica (format nil "~A  /  ~A" (if guerreiro "GUERREIRO" "MAGO")
                          (if (sessao-pausada sessao) "PAUSADO" "EM EXPLORAÇÃO")) (+ inicio 12) 16 *cor-verde*)
    (setf (grafica-regioes-navegacao grafica) nil)
    (loop with x = inicio
          for (comando rotulo w) in '((:mundo "Mundo" 86) (:teoremas "Teoremas" 114)
                                    (:ontologia "Ontologia" 126) (:guia "Guia" 80) (:pausa "Pausar" 108)) do
      (let* ((retangulo (list x 42 w 34))
             (ativa (if (eq comando :pausa) (sessao-pausada sessao) (eq comando (tela-atual grafica))))
             (estilo (if (or ativa (sob-mouse-p grafica retangulo)) "selecionado" "botao")))
        (painel-interface grafica estilo x 42 w 34 :borda 8)
        (texto grafica (if (and (eq comando :pausa) (sessao-pausada sessao)) "Retomar" rotulo)
               (+ x 12) 50 (if ativa *cor-dourada* *cor-texto*))
        (push (cons comando retangulo) (grafica-regioes-navegacao grafica)))
      (incf x (+ w 6)))))
(defun desenhar-medidor (grafica x y largura valor maximo cor)
  (painel-interface grafica "botao" x y largura 16 :borda 5)
  (barra grafica (+ x 5) (+ y 5) (- largura 10) 6 valor maximo cor))
